// TELC C1 — Test Data
// Добавить новый тест: скопируй один блок и измени данные.
// Форматы: kind="sb" (Sprachbausteine), "lv1" (Teil 1), "lv2" (Teil 2), "lv3" (Teil 3)

var TESTS = [

// ═══════════════════════════════════════════════════════
// SPRACHBAUSTEINE
// ═══════════════════════════════════════════════════════
{
  id:"sb1", type:"Sprachbausteine", kind:"sb",
  title:'Wer hat das "Handy" erfunden?',
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Jeder kennt es, fast jeder Deutsche hat auch <strong>(25)</strong>: das Mobiltelefon oder eben „Handy". Ob auf der Straße, in Bus oder Bahn hört man überall Sätze wie „Gib mir mal das Handy!" – „Handy" gehört inzwischen zur deutschen Sprache. Oder?</p><p>Eine Umfrage hat gezeigt: Die meisten Deutschen (76 %) sind der <strong>(26)</strong>, dass der Begriff „Handy" aus dem Englischen <strong>(27)</strong>. Das ist jedoch falsch. Tatsächlich sind die <strong>(28)</strong> Sprechenden die einzigen, die ihr Mobiltelefon als Handy bezeichnen. Und das Wort <strong>(29)</strong> keineswegs aus dem Englischen – dort <strong>(30)</strong> man das kleine Telefon meist als „mobile phone". Dass die Deutschen sich eines englisch klingenden Phantasiewortes <strong>(31)</strong>, wird von Kulturpessimisten gern als „ins Absurde <strong>(32)</strong> Anglomanie" bezeichnet. Der Begriff „Handy" verdanke sich in Wirklichkeit allein der <strong>(33)</strong>, der Sprache Luthers und Goethes fehlten im Zeitalter der globalen Kommunikation die Worte. Nun kann man darüber <strong>(34)</strong>, wie Luther sein Mobiltelefon genannt hätte – vermutlich <strong>(35)</strong> zu keinem vernünftigen Ergebnis in diesem Punkt gelangen.</p><p>Sicher ist jedoch, dass der Begriff „Handy" keine <strong>(36)</strong> Schöpfung ist. Um dem Ursprung dieses Begriffs etwas <strong>(37)</strong>, muss man sich ein wenig mit der Sprachgeschichte befassen und zurückschauen in die 1930er Jahre. Zu jener Zeit wurden – zunächst <strong>(38)</strong> für den militärischen Einsatz – kleine tragbare Funkgeräte entwickelt. Es <strong>(39)</strong> sich bei diesen Geräten um eine Weiterentwicklung der sogenannten „Walkie Talkies". Während <strong>(40)</strong> meist rucksackgroße Geräte waren, konnte man die neuen Funkgeräte ganz einfach in eine Tasche stecken oder <strong>(41)</strong> in der Hand tragen. Diese Geräte wurden von Soldaten als „Handie Talkies" bezeichnet, und einige amerikanische Soldaten sollen diesen Ausdruck <strong>(42)</strong> sogar zu „Handy" <strong>(43)</strong>.</p><p>Im deutschen Sprachraum tauchte das Handy dann erstmals in einer Anzeige von 1986 auf und <strong>(44)</strong> damals noch ein kleines Amateurfunkgerät, bevor sich die <strong>(45)</strong> dann ab 1990 für Mobiltelefone durchsetzte. Der <strong>(46)</strong> des Handys konnte nicht mehr aufgehalten werden.</p>',
  qs:[
    {n:25,ctx:"fast jeder Deutsche hat auch ___: das Mobiltelefon",
     opts:["a) das","b) ein","c) eines","d) es"],ans:"c) eines",
     exp:"<strong>c) eines</strong> — unbestimmtes Pronomen Neutr. (= один такой предмет). <em>Ein</em> — Artikel vor Nomen, nicht Pronomen. <em>es</em> — Personalpronomen.",
     rule:"<em>eines</em> = неопределённое местоимение ср.р.: «hat auch <strong>eines</strong>» = имеет (один такой предмет). Стоит без существительного."},
    {n:26,ctx:"sind der ___, dass der Begriff aus dem Englischen kommt",
     opts:["a) Auffassung","b) Aufnahme","c) Auslegung","d) Behauptung"],ans:"a) Auffassung",
     exp:"<strong>a) Auffassung</strong> — фиксированная конструкция: <em>der Auffassung sein, dass…</em> = быть того мнения, что. Требует Genitiv.",
     rule:"Фиксация: <em>der Auffassung / Meinung / Ansicht sein</em> = придерживаться мнения (C1). Всегда с Genitiv!"},
    {n:27,ctx:"dass der Begriff aus dem Englischen ___",
     opts:["a) ableitet","b) entlehnt","c) herleitet","d) stammt"],ans:"d) stammt",
     exp:"<strong>d) stammt</strong> — <em>aus etw. stammen</em> = происходить из. <em>Ableiten / herleiten</em> требуют <em>sich</em> (reflexiv).",
     rule:"<em>stammen aus + Dativ</em> = происходить из чего-л. Без Reflexivpronomen!"},
    {n:28,ctx:"sind die ___ Sprechenden die einzigen",
     opts:["a) Deutsch","b) Deutsche","c) Deutschen","d) Deutsches"],ans:"a) Deutsch",
     exp:"<strong>a) Deutsch</strong> — здесь название языка как атрибут к Partizip I: <em>die Deutsch Sprechenden</em> = говорящие по-немецки. Нет артикля → нет окончания.",
     rule:"<em>die Deutsch Sprechenden</em> = субстантивированное Partizip I. Ср.: <em>die Deutschen</em> = немцы (национальность) — другое значение!"},
    {n:29,ctx:"das Wort ___ keineswegs aus dem Englischen",
     opts:["a) entreißt","b) entsteht","c) folgt","d) stammt"],ans:"d) stammt",
     exp:"<strong>d) stammt</strong> — <em>aus etw. stammen</em> = происходить из. Фиксированная предлог: <em>aus</em>.",
     rule:"<em>stammen aus</em> = происходить из · <em>kommen aus</em> = аналогично, но разговорнее"},
    {n:30,ctx:"dort ___ man das kleine Telefon meist als „mobile phone"",
     opts:["a) bedrückt","b) bezeichnet","c) definiert","d) deutet"],ans:"b) bezeichnet",
     exp:"<strong>b) bezeichnet</strong> — <em>etw. als etw. bezeichnen</em> = называть что-л. чем-л. Фиксированная структура с <em>als</em>.",
     rule:"<em>als etw. bezeichnen / nennen / betrachten</em> — всегда с <em>als</em> + Nominativ"},
    {n:31,ctx:"Dass die Deutschen sich eines Phantasiewortes ___",
     opts:["a) bedienen","b) benutzen","c) gebrauchen","d) verdienen"],ans:"a) bedienen",
     exp:"<strong>a) bedienen</strong> — <em>sich einer Sache bedienen</em> (Genitiv!) = пользоваться чем-л. (книжн.). <em>Benutzen/gebrauchen</em> → Akkusativ.",
     rule:"<em>sich einer Sache bedienen</em> (Gen.) = пользоваться чем-л. — ВАЖНО: требует Genitiv, не Akkusativ!"},
    {n:32,ctx:"gern als „ins Absurde ___ Anglomanie" bezeichnet",
     opts:["a) gerächte","b) geführte","c) getriebene","d) geworfene"],ans:"b) geführte",
     exp:"<strong>b) geführte</strong> — <em>ins Absurde führen</em> = доводить до абсурда → Partizip II как атрибут: <em>die ins Absurde geführte Anglomanie</em>.",
     rule:"Partizip II как атрибут перед существительным. Слабое склонение после определённого артикля (Akk. fem. → -e)."},
    {n:33,ctx:"verdanke sich allein der ___, der Sprache fehlten die Worte",
     opts:["a) Annahme","b) Einstellung","c) Stellungnahme","d) Verstellung"],ans:"a) Annahme",
     exp:"<strong>a) Annahme</strong> = предположение. <em>Einstellung</em> = отношение/установка. <em>Stellungnahme</em> = позиция/заявление.",
     rule:"<em>die Annahme</em> = предположение / <em>die Einstellung</em> = отношение / <em>die Stellungnahme</em> = официальное заявление"},
    {n:34,ctx:"Nun kann man darüber ___, wie Luther sein Mobiltelefon genannt hätte",
     opts:["a) ausbrüten","b) denken","c) grübeln","d) lifteln"],ans:"c) grübeln",
     exp:"<strong>c) grübeln</strong> = ломать голову над чем-л. <em>Über etw. grübeln, wie…</em> — идеально подходит.",
     rule:"<em>über etw. grübeln</em> = раздумывать, ломать голову (книжн.)"},
    {n:35,ctx:"vermutlich ___ zu keinem vernünftigen Ergebnis gelangen",
     opts:["a) aber man wird","b) man aber wird","c) wird man aber","d) wird aber man"],ans:"c) wird man aber",
     exp:"<strong>c) wird man aber</strong> — наречие <em>vermutlich</em> на Pos.1 → глагол на Pos.2 → подлежащее → частица. Порядок: vermutlich | wird | man | aber.",
     rule:"Порядок слов: Наречие (Pos.1) + Глагол (Pos.2) + Подлежащее + Частица"},
    {n:36,ctx:"der Begriff „Handy" keine ___ Schöpfung ist",
     opts:["a) rein deutsche","b) reindeutsche","c) reine deutsche","d) reine Deutsche"],ans:"a) rein deutsche",
     exp:"<strong>a) rein deutsche</strong> — <em>rein</em> как наречие (= purely/чисто) перед прилагательным. Оба слова строчные. <em>reine Deutsche</em> = чистокровная немка (существительное).",
     rule:"<em>rein</em> как наречие + прилагательное: <em>rein deutsch</em> = чисто немецкий. Склоняется только последнее прилагательное."},
    {n:37,ctx:"Um dem Ursprung dieses Begriffs etwas ___",
     opts:["a) klarzukommen","b) näherzukommen","c) zu klären","d) zu nähern"],ans:"b) näherzukommen",
     exp:"<strong>b) näherzukommen</strong> — <em>einer Sache näherkommen</em> = приближаться к пониманию чего-л. Отделяемый глагол: <em>zu</em> стоит МЕЖДУ приставкой и глаголом.",
     rule:"Отделяемые глаголы + zu: <em>näher|kommen → näher<strong>zu</strong>kommen</em>. zu всегда между приставкой и глаголом!"},
    {n:38,ctx:"zunächst ___ für den militärischen Einsatz",
     opts:["a) vorbildlich","b) vorgezogen","c) vornehmlich","d) vortrefflich"],ans:"c) vornehmlich",
     exp:"<strong>c) vornehmlich</strong> = hauptsächlich = главным образом, прежде всего. <em>Vorbildlich</em> = образцово, <em>vortrefflich</em> = превосходно.",
     rule:"<em>vornehmlich</em> = hauptsächlich = прежде всего, главным образом (типично для C1)"},
    {n:39,ctx:"Es ___ sich bei diesen Geräten um eine Weiterentwicklung",
     opts:["a) belief","b) ergab","c) ging","d) handelte"],ans:"d) handelte",
     exp:"<strong>d) handelte</strong> — <em>es handelt sich um + Akk.</em> = речь идёт о. Фиксированная безличная конструкция!",
     rule:"ФИКСАЦИЯ: <em>es handelt sich um + Akk.</em> = речь идёт о (ОЧЕНЬ ВАЖНО для C1!)"},
    {n:40,ctx:"Während ___ meist rucksackgroße Geräte waren",
     opts:["a) Letztere","b) letztgesagte","c) letztlich","d) zuletzt"],ans:"a) Letztere",
     exp:"<strong>a) Letztere</strong> (Plural) = последние из упомянутых (Walkie Talkies). Субстантивация, склоняется как прилагательное.",
     rule:"<em>Erstere/Letztere</em> = первые/последние (из упомянутых) — субстантивация"},
    {n:41,ctx:"konnte man in eine Tasche stecken oder ___ in der Hand tragen",
     opts:["a) also","b) eben","c) genau","d) gerade"],ans:"b) eben",
     exp:"<strong>b) eben</strong> = просто так, вот так (модальная частица). <em>Also</em> = итак, <em>gerade</em> = как раз/именно сейчас.",
     rule:"<em>eben</em> как частица = просто, именно так (Modalpartikel C1)"},
    {n:42,ctx:"einige Soldaten sollen diesen Ausdruck ___ sogar zu „Handy" abgekürzt haben",
     opts:["a) dadurch","b) dagegen","c) daraufhin","d) dennoch"],ans:"c) daraufhin",
     exp:"<strong>c) daraufhin</strong> = вследствие этого, затем. Каузальное наречие, стоит на Pos.1.",
     rule:"<em>daraufhin</em> = вследствие этого, затем → всегда на Pos.1 во втором предложении"},
    {n:43,ctx:"zu „Handy\" ___ haben",
     opts:["a) abgekürzt","b) abkürzen","c) gekürzt","d) kürzer gemacht"],ans:"a) abgekürzt",
     exp:"<strong>a) abgekürzt</strong> — Partizip II от <em>abkürzen</em> (отделяемый: ab|kürzen). Инфинитив Перфект с Modalverb: <em>sollen + abgekürzt haben</em>.",
     rule:"Отделяемые глаголы Partizip II: <em>ab|kürzen → abgekürzt</em>. Инфинитив Перфект: <em>abgekürzt haben</em>"},
    {n:44,ctx:"tauchte in einer Anzeige von 1986 auf und ___ damals noch ein Amateurfunkgerät",
     opts:["a) bezeichnete","b) hieß","c) klassifizierte","d) nannte"],ans:"a) bezeichnete",
     exp:"<strong>a) bezeichnete</strong> = обозначало (формально). <em>Hieß</em> тоже возможно, но <em>bezeichnen</em> — формальнее для C1-текстов.",
     rule:"<em>bezeichnen</em> = обозначать (формально) / <em>heißen</em> = называться (разговорнее)"},
    {n:45,ctx:"bevor sich die ___ dann ab 1990 für Mobiltelefone durchsetzte",
     opts:["a) Wörterererschöpfung","b) Worterschopfung","c) Wörterschöpfung","d) Wortschöpfung"],ans:"d) Wortschöpfung",
     exp:"<strong>d) Wortschöpfung</strong> = словотворчество, неологизм. Сложное слово: Wort + Schöpfung. Без умлаута в первой части.",
     rule:"<em>die Wortschöpfung</em> = словотворчество / <em>die Schöpfung</em> = творение, создание"},
    {n:46,ctx:"Der ___ des Handys konnte nicht mehr aufgehalten werden",
     opts:["a) Gewinn","b) Siegeszug","c) Trumpf","d) Vollzug"],ans:"b) Siegeszug",
     exp:"<strong>b) Siegeszug</strong> = триумфальное шествие. <em>Vollzug</em> = исполнение (юрид.).",
     rule:"<em>der Siegeszug</em> = триумфальное шествие / <em>den Siegeszug antreten</em> = начать победное шествие"}
  ],
  vocab:["die Auffassung — мнение, точка зрения","sich einer Sache bedienen (Gen.) — пользоваться чем-л.","es handelt sich um + Akk. — речь идёт о","vornehmlich — главным образом","der Siegeszug — триумфальное шествие","stammen aus — происходить из","daraufhin — вследствие этого"]
},

// ═══════════════════════════════════════════════════════
{
  id:"sb2", type:"Sprachbausteine", kind:"sb",
  title:"Das Gehirn des Rauchers ist weniger flexibel",
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Raucher denken weniger flexibel, sie reagieren weniger stark auf alternative Handlungsszenarien. Genau diese Erkenntnis erklärt auch, warum es Rauchern oftmals so schwerfällt, von ihrer Sucht <strong>(25)</strong>. Dies sind die Resultate einer neuen Studie <strong>(26)</strong> Hirnforscher. Die Ergebnisse dieser Studie wurden nun auch im Fachmagazin „Nature Neuroscience" <strong>(27)</strong>. Wir wollen hier das Wichtigste <strong>(28)</strong>.</p><p>Süchtige sehen die Welt anders – das ist <strong>(29)</strong> nur eine subjektive Behauptung, sondern nun auch wissenschaftlich belegt. Dabei beeinflusst die Sucht das Verhalten der Betroffenen <strong>(30)</strong> vielfältige Weise. Süchtige lassen sich zum Beispiel schwerer sättigen, sie machen exzessiv mit einem Verhalten weiter, wenn andere längst <strong>(31)</strong>.</p><p>Ziel der Forscher war es, die Sucht der Raucher <strong>(32)</strong>. Rauchen verändert die Wahrnehmung – das war bekannt. Beim Rauchen werden Belohnungszentren im Gehirn aktiviert, beim Nichtrauchen fehlt ihm dieser Reiz, was <strong>(33)</strong> zu Schmerzen führen kann.</p><p>Jetzt entdeckten die Hirnforscher: Raucher lassen sich nicht davon <strong>(34)</strong>, was hätte sein können, wenn sie eine andere Entscheidung <strong>(35)</strong> – wenn sie zum Beispiel die letzte Zigarette nicht gebraucht hätten.</p><p>Die Forscher <strong>(36)</strong> Raucher und Nichtraucher an einem Börsenspiel teilnehmen. Die Spieler erhielten jeweils 100 Dollar. Nach jedem Spielzug <strong>(37)</strong> die Spieler, wie sie mehr Geld hätten gewinnen können. Am Ende <strong>(38)</strong> Raucher und Nichtraucher zwar gleich gut ab, doch sie <strong>(39)</strong> unterschiedliche Spielstrategien. Nichtraucher änderten oft ihre Spielweise, sobald sie erfuhren, dass sie in der Vergangenheit mit einer <strong>(40)</strong> Strategie mehr Geld gewonnen hätten. Raucher dagegen <strong>(41)</strong> dem keine Beachtung und spielten weiter. Die Forscher führen dies auf eine Unfähigkeit der Raucher <strong>(42)</strong>, auf alternative Szenarien zu reagieren.</p><p>Um den Unterschied zu erklären, wurde während des Versuchs auch <strong>(43)</strong> die Gehirnaktivität aufgezeichnet. Die Forscher leiteten <strong>(44)</strong> ab, dass Raucher mit denselben Informationen anders umgehen als Nichtraucher: Raucher <strong>(45)</strong> sie einfach. Dies kann auch das Aufhören selbst <strong>(46)</strong>: Für Raucher ist es schwerer, die Vorteile des Nichtrauchens zu erkennen.</p>',
  qs:[
    {n:25,ctx:"warum es Rauchern schwerfällt, von ihrer Sucht ___",
     opts:["a) abzulassen","b) aufzuhören","c) wegzulassen","d) zu beenden"],ans:"a) abzulassen",
     exp:"<strong>a) abzulassen</strong> — <em>von etw. ablassen</em> = отказаться от чего-л. Фиксированная предлог: <em>von</em>. <em>Aufhören</em> требует <em>mit</em>, не <em>von</em>.",
     rule:"<em>von etw. ablassen</em> (von + Dativ) = отказываться от чего-л., бросать (книжн.)"},
    {n:26,ctx:"Resultate einer neuen Studie ___ Hirnforscher",
     opts:["a) drei amerikanischer","b) dreien amerikanischer","c) dreier amerikanischen","d) dreier amerikanischer"],ans:"d) dreier amerikanischer",
     exp:"<strong>d) dreier amerikanischer</strong> — Genitiv Plural после числительного. <em>Drei → dreier</em> (Gen.). Прилагательное без артикля в Gen.Pl.: <em>amerikanischer</em>.",
     rule:"Genitiv Plural без артикля: <em>dreier amerikanischer Hirnforscher</em> = троих американских исследователей мозга"},
    {n:27,ctx:"wurden im Fachmagazin ___ (veröffentlicht)",
     opts:["a) angekündigt","b) geschrieben","c) publiziert","d) weitergegeben"],ans:"c) publiziert",
     exp:"<strong>c) publiziert</strong> = опубликован (в журнале). <em>Veröffentlichen/publizieren</em> = синонимы для научного контекста.",
     rule:"<em>publizieren</em> = публиковать (формально, научный контекст) = <em>veröffentlichen</em>"},
    {n:28,ctx:"Wir wollen hier das Wichtigste ___",
     opts:["a) kurznachfassen","b) kurz zusammenfassen","c) kutz zusammenlegen","d) kurzfassen"],ans:"b) kurz zusammenfassen",
     exp:"<strong>b) kurz zusammenfassen</strong> = кратко резюмировать. <em>Kurzfassen</em> не существует как Kompositum.",
     rule:"<em>kurz zusammenfassen</em> = кратко резюмировать (два слова, не сложное!)"},
    {n:29,ctx:"das ist ___ nur eine subjektive Behauptung, sondern auch wissenschaftlich belegt",
     opts:["a) in keinen Fällen","b) keinfalls","c) keineswegs","d) ohnegleichen"],ans:"c) keineswegs",
     exp:"<strong>c) keineswegs</strong> = ни в коем случае, отнюдь не. Сочетание с <em>nicht nur … sondern auch</em>.",
     rule:"<em>keineswegs</em> = ни в коем случае, отнюдь не (C1, книжн.) = auf keinen Fall"},
    {n:30,ctx:"beeinflusst die Sucht das Verhalten der Betroffenen ___ vielfältige Weise",
     opts:["a) an","b) auf","c) in","d) über"],ans:"b) auf",
     exp:"<strong>b) auf</strong> — <em>auf vielfältige Weise</em> = самыми разными способами. Фиксированная конструкция.",
     rule:"Фиксация: <em>auf + Adjektiv + Weise</em> = каким-л. образом"},
    {n:31,ctx:"wenn andere längst ___",
     opts:["a) aufhören müssten","b) aufhören sollten","c) aufgehört hätten","d) aufzuhören haben"],ans:"c) aufgehört hätten",
     exp:"<strong>c) aufgehört hätten</strong> — Konjunktiv II Perfekt = уже бы бросили (гипотетическое прошлое).",
     rule:"Konj.II Perfekt: <em>hätten + Partizip II</em> = гипотетическое действие в прошлом"},
    {n:32,ctx:"Ziel der Forscher war es, die Sucht der Raucher ___",
     opts:["a) abzuschaffen","b) abzuwägen","c) einzusehen","d) zu verstehen"],ans:"d) zu verstehen",
     exp:"<strong>d) zu verstehen</strong> = понять (суть никотиновой зависимости). <em>Einsehen</em> = признать, <em>abschaffen</em> = отменить.",
     rule:"<em>etw. verstehen</em> = понимать. Infinitiv mit zu после <em>es war das Ziel</em>"},
    {n:33,ctx:"was ___ zu Schmerzen führen kann",
     opts:["a) daraus","b) darüber","c) durchaus","d) hindurch"],ans:"c) durchaus",
     exp:"<strong>c) durchaus</strong> = вполне, очень даже (усилитель). <em>Was durchaus zu Schmerzen führen kann</em> = что вполне может вызвать боль.",
     rule:"<em>durchaus</em> = вполне, совершенно (усилитель утверждения, C1)"},
    {n:34,ctx:"Raucher lassen sich nicht davon ___, was hätte sein können",
     opts:["a) begleiten","b) folgen","c) leiten","d) zeigen"],ans:"c) leiten",
     exp:"<strong>c) leiten</strong> — <em>sich von etw. leiten lassen</em> = руководствоваться чем-л., поддаваться влиянию.",
     rule:"<em>sich von etw. leiten lassen</em> = руководствоваться, поддаваться влиянию чего-л."},
    {n:35,ctx:"wenn sie eine andere Entscheidung ___ – wenn sie die Zigarette nicht gebraucht hätten",
     opts:["a) getroffen hätten","b) trafen","c) treffen werden","d) treffen würden"],ans:"a) getroffen hätten",
     exp:"<strong>a) getroffen hätten</strong> — Konjunktiv II Perfekt для гипотетической ситуации в прошлом. <em>Eine Entscheidung treffen</em> = принять решение.",
     rule:"<em>eine Entscheidung treffen</em> = принять решение · Konj.II Perf.: <em>hätten getroffen</em>"},
    {n:36,ctx:"Die Forscher ___ Raucher und Nichtraucher an einem Börsenspiel teilnehmen",
     opts:["a) brauchten","b) hatten","c) ließen","d) veranlassten"],ans:"c) ließen",
     exp:"<strong>c) ließen</strong> — Kausativkonstruktion: <em>jmdn. etw. tun lassen</em> = заставить/позволить участвовать. Без zu!",
     rule:"Kausativ: <em>jmdn. etw. tun lassen</em> = заставить/позволить сделать (без zu у Infinitiv!)"},
    {n:37,ctx:"Nach jedem Spielzug ___ die Spieler, wie sie mehr Geld hätten gewinnen können",
     opts:["a) erfuhren","b) einheiten","c) realisierten","d) träumten"],ans:"a) erfuhren",
     exp:"<strong>a) erfuhren</strong> = узнали (Präteritum von erfahren). <em>Erfuhren, wie…</em> = узнали о том, как.",
     rule:"<em>erfahren</em> = узнавать (новую информацию) · Prät.: <em>erfuhren</em>"},
    {n:38,ctx:"Am Ende ___ Raucher und Nichtraucher zwar gleich gut ab",
     opts:["a) liefen","b) trennten","c) schnitten","d) machten"],ans:"c) schnitten",
     exp:"<strong>c) schnitten ab</strong> — Prät. von <em>abschneiden</em>: gut/schlecht abschneiden = показать хорошие/плохие результаты.",
     rule:"<em>gut/schlecht abschneiden</em> = показать хорошие/плохие результаты (тест, экзамен и т.д.)"},
    {n:39,ctx:"doch sie ___ unterschiedliche Spielstrategien",
     opts:["a) nahmen","b) unternahmen","c) verbrauchten","d) verfolgten"],ans:"d) verfolgten",
     exp:"<strong>d) verfolgten</strong> — <em>eine Strategie verfolgen</em> = придерживаться стратегии.",
     rule:"<em>eine Strategie / ein Ziel verfolgen</em> = придерживаться стратегии / следовать цели"},
    {n:40,ctx:"mit einer ___ Strategie mehr Geld gewonnen hätten",
     opts:["a) anderen als die gewählte","b) anderen als der gewählten","c) gewählten als der anderen","d) gewählten anderen"],ans:"b) anderen als der gewählten",
     exp:"<strong>b) anderen als der gewählten</strong> = с другой стратегией, чем выбранная. <em>Als</em> при компаративе + Dativ.",
     rule:"Сравнение с атрибутом: <em>einer anderen als der gewählten</em> = другой, чем выбранная (Dat. после als)"},
    {n:41,ctx:"Raucher dagegen ___ dem keine Beachtung und spielten weiter",
     opts:["a) entrichteten","b) gaben","c) schenkten","d) zählten"],ans:"c) schenkten",
     exp:"<strong>c) schenkten</strong> — <em>keine Beachtung schenken</em> = не обращать внимания. Фиксированная конструкция.",
     rule:"Фиксация: <em>jmdm. Beachtung schenken / keine Beachtung schenken</em> = уделять/не уделять внимание"},
    {n:42,ctx:"Unfähigkeit der Raucher ___, auf alternative Szenarien zu reagieren",
     opts:["a) heraus","b) hinzu","c) nach","d) zurück"],ans:"d) zurück",
     exp:"<strong>d) zurück</strong> — <em>etw. auf etw. zurückführen</em> = объяснять чем-л. Здесь: <em>auf eine Unfähigkeit zurückführen</em>.",
     rule:"<em>etw. auf etw. zurückführen</em> = объяснять что-л. чем-л., относить к причине"},
    {n:43,ctx:"wurde während des Versuchs auch ___ die Gehirnaktivität aufgezeichnet",
     opts:["a) fortgegangen","b) fortgehen","c) fortgelaufen","d) fortlaufend"],ans:"d) fortlaufend",
     exp:"<strong>d) fortlaufend</strong> = непрерывно, постоянно (как наречие). <em>Fortlaufend aufgezeichnet</em> = непрерывно записывалась.",
     rule:"<em>fortlaufend</em> = непрерывно, постоянно (наречие, C1)"},
    {n:44,ctx:"Die Forscher leiteten ___ ab, dass Raucher anders umgehen",
     opts:["a) dadurch","b) danach","c) daraus","d) dazu"],ans:"c) daraus",
     exp:"<strong>c) daraus</strong> — <em>daraus ableiten</em> = сделать вывод из этого. <em>da + aus</em> = из этого.",
     rule:"<em>daraus ableiten</em> = делать вывод из этого (da + aus = из этого)"},
    {n:45,ctx:"Raucher ___ sie einfach",
     opts:["a) berücksichtigen","b) beziehen","c) ignorieren","d) vermeiden"],ans:"c) ignorieren",
     exp:"<strong>c) ignorieren</strong> = игнорировать. Рауклеры просто игнорируют информацию.",
     rule:"<em>ignorieren</em> = игнорировать · <em>nicht beachten</em> = не обращать внимания (синоним)"},
    {n:46,ctx:"Dies kann auch das Aufhören selbst ___",
     opts:["a) bekämpfen","b) beschweren","c) erschweren","d) vermeiden"],ans:"c) erschweren",
     exp:"<strong>c) erschweren</strong> = затруднять. <em>Das Aufhören erschweren</em> = затруднять отказ от курения.",
     rule:"<em>erschweren</em> = затруднять · <em>erleichtern</em> = облегчать (антоним)"}
  ],
  vocab:["von etw. ablassen — отказаться от чего-л.","keineswegs — ни в коем случае","auf … Weise — каким-л. образом","sich von etw. leiten lassen — руководствоваться чем-л.","gut abschneiden — показать хорошие результаты","eine Strategie verfolgen — придерживаться стратегии","Beachtung schenken — уделять внимание","daraus ableiten — делать вывод из этого","erschweren — затруднять"]
},

// ═══════════════════════════════════════════════════════
// LESEVERSTEHEN TEIL 1
// ═══════════════════════════════════════════════════════
{
  id:"lv1_1", type:"Leseverstehen Teil 1", kind:"lv1",
  title:"Eine Box verändert die Welt",
  desc:"6 Satz-Zuordnungen · Textrekonstruktion · C1",
  satze:[
    {id:"z",t:"<strong>z)</strong> Smartphones aus China, T-Shirts aus Bangladesch, Bananen aus Nicaragua. <em>(Beispiel — Lücke 0)</em>"},
    {id:"a",t:"<strong>a)</strong> Die Größe, die er für seine Transportbehälter gewählt hatte, wurde zum Standard."},
    {id:"b",t:"<strong>b)</strong> Dieses erhoffte sich von den Containern logistische Verbesserungen in der Sicherung des Nachschubs."},
    {id:"c",t:"<strong>c)</strong> Doch sie waren am Streit über die Abmessungen der Container und an streikenden Hafenarbeitern gescheitert."},
    {id:"d",t:"<strong>d)</strong> Es sollte genau dieser Umstand sein, dem sie in der Folge ihre Beschäftigung verdanken würden."},
    {id:"e",t:"<strong>e)</strong> Für die Hafenarbeiter war das nicht nur Schwerstarbeit, sondern lebensgefährlich."},
    {id:"f",t:"<strong>f)</strong> Gesteuert und auf ihrer Reise verfolgt werden diese dabei von Computern und globalen Logistiksystemen."},
    {id:"g",t:"<strong>g)</strong> Handelsrechtliche Überlegungen dieser Art konnten ihren Siegeszug nicht aufhalten."},
    {id:"h",t:"<strong>h)</strong> In den 1960er Jahren betrug der Warenhandel weniger als 20 Prozent der globalen Wirtschaftsleistung."}
  ],
  textps:[
    "Eine gewellte Stahlbox, zwölf Meter lang, drei Meter hoch und genauso breit. Sie ist zum greifbaren Symbol der Globalisierung geworden. Millionen von Containern kreuzen auf immer größeren Schiffen auf den Weltmeeren: {0}",
    "Der Container hat das Transportwesen revolutioniert. Bis in die 50er Jahre war es üblich, Waren einzeln zu transportieren oder sie in Säcke oder Kisten zu verladen. Für die Hafenarbeiter war das nicht nur Schwerstarbeit. {1} Immer wieder passierten nämlich in den großen Häfen der Welt schwere Unfälle.",
    "Es dauerte zehn Tage, bis die „Warrior" beladen war – genauso lange wie die Überfahrt. Zwar hatte es bereits seit Jahrzehnten Bemühungen gegeben, den Transport effizienter zu gestalten. {2} Erst einem US-amerikanischen Unternehmer gelang es, gemeinsam mit der Marine die Idee einer universellen Transportbox durchzusetzen.",
    "Am 26. April 1956 schipperte Malcolm McLean mit einem umgebauten Tanker von Port Newark Richtung Texas. An Bord waren 56 Container. {3} Diese 40-Fuß-Container sind noch heute täglich in Gebrauch.",
    "Dass McLean erfolgreich war, lag auch an dem mächtigen Kunden an seiner Seite, dem amerikanischen Militär. {4} McLean überzeugte schließlich die Betreiber des Hafens von New York.",
    "Heute reisen rund 90 Prozent der Güter, die über die Meere verschifft werden, in Containern. {5} Der Container reduzierte die Transportkosten auf einen Bruchteil.",
    "{6} Heute macht er ungefähr die Hälfte des Welthandels aus."
  ],
  qs:[
    {n:1,ans:"e",
     exp:"Satz e): «Für die Hafenarbeiter war das nicht nur Schwerstarbeit, sondern lebensgefährlich.» — <em>das</em> = das Schleppen von Hand (vorheriger Satz). Ergänzt den Gedanken.",
     textref:"«Bis in die 50er Jahre war es üblich, Waren einzeln zu transportieren … Für die Hafenarbeiter war das nicht nur Schwerstarbeit.» → Satz e) ergänzt: «sondern lebensgefährlich».",
     rule:"Strategie: Pronomen <em>das/dies/es</em> verweist auf Vorheriges. Suche den Satz, der die Aussage logisch fortsetzt."},
    {n:2,ans:"c",
     exp:"Satz c): «Doch sie waren am Streit … gescheitert.» — <em>sie</em> (Plural, fem.) = die Bemühungen. <em>Doch</em> signalisiert Gegenargument: Bemühungen gab es, aber sie scheiterten.",
     textref:"«Zwar hatte es bereits seit Jahrzehnten Bemühungen gegeben …» → <em>Doch sie</em> (= die Bemühungen) «waren gescheitert».",
     rule:"<em>Doch</em> + Pronomen → Gegenargument. Genus-Übereinstimmung: <em>sie</em> (Pl.) = die Bemühungen (Pl. fem.)."},
    {n:3,ans:"a",
     exp:"Satz a): «Die Größe, die <em>er</em> gewählt hatte, wurde zum Standard.» — <em>er</em> = McLean (zuletzt erwähnt). Zeitlogik: 56 Container → dann Standard.",
     textref:"«Am 26. April 1956 schipperte Malcolm McLean … An Bord waren 56 Container.» → <em>er</em> in Satz a) = McLean.",
     rule:"Pronomen <em>er</em> → letzter Mannesname im Text = McLean. Zeitliche Abfolge beachten."},
    {n:4,ans:"b",
     exp:"Satz b): «Dieses erhoffte sich … logistische Verbesserungen …» — <em>Dieses</em> (Neutrum) = das amerikanische Militär (Neutrum).",
     textref:"«dem amerikanischen Militär» → <em>Dieses</em> (Neutr., Nom.) in Satz b) = das Militär.",
     rule:"Genus: <em>Dieses</em> (Neutr.) → das Militär (Neutr.). Genus-Übereinstimmung ist der Schlüssel!"},
    {n:5,ans:"f",
     exp:"Satz f): «Gesteuert und verfolgt werden <em>diese</em> von Computern …» — <em>diese</em> (Plural) = die Container (90% der Güter).",
     textref:"«Heute reisen rund 90 Prozent der Güter … in Containern.» → <em>diese</em> in Satz f) = die Container.",
     rule:"Passiv mit Partizip am Satzanfang (C1-Merkmal). <em>diese</em> (Plural) = Container."},
    {n:6,ans:"h",
     exp:"Satz h): «In den 1960er Jahren betrug der Warenhandel weniger als 20 Prozent …» — baut Kontrast zu «Heute macht er die Hälfte aus» (Folgesatz) auf.",
     textref:"«Heute macht er ungefähr die Hälfte des Welthandels aus.» ← Satz h) liefert den historischen Kontrast: 1960er vs. heute.",
     rule:"Zeitlicher Kontrast: «1960er» (Satz h) vs. «heute» (Folgesatz). Statistik baut Kontrast auf."}
  ],
  vocab:["revolutionieren — совершать революцию в","die Abmessung — размер, габарит","der Nachschub — снабжение, подвоз","auf einen Bruchteil reduzieren — сократить до доли","die Bemühung — усилие, попытка"]
},

{
  id:"lv1_2", type:"Leseverstehen Teil 1", kind:"lv1",
  title:"Satzzeichen, mächtige Werkzeuge",
  desc:"6 Satz-Zuordnungen · Textrekonstruktion · C1",
  satze:[
    {id:"z",t:"<strong>z)</strong> Als Victor Hugo 1862 im Urlaub weilte, ließ er seinem Verleger ein schlichtes «?» kabeln. Wenig später erhielt er die ebenso knappe Antwort: «!» <em>(Beispiel)</em>"},
    {id:"a",t:"<strong>a)</strong> Bereits 1762 bemängelte der Gelehrte Johann Christoph Gottsched, dass es im Deutschen keine Zeichen für Staunen oder Mitleid gebe."},
    {id:"b",t:"<strong>b)</strong> Dabei konnte damals von verbindlichen Normen noch gar keine Rede sein."},
    {id:"c",t:"<strong>c)</strong> Das beklagen selbst die leidenschaftlichsten Verfechter von Kurznachrichten."},
    {id:"d",t:"<strong>d)</strong> Erst im Mittelalter kamen irische Mönche auf die Idee, diese Textschlangen mit Zeichen zu versehen, um anderen Lesern das Leben einfacher zu machen."},
    {id:"e",t:"<strong>e)</strong> Erst viel später – mit den neuen Medien – ging dieser langgehegte Wunsch in Erfüllung."},
    {id:"f",t:"<strong>f)</strong> In ihr reiht sich Buchstabe an Buchstabe, Wort an Wort."},
    {id:"g",t:"<strong>g)</strong> Rund 2500 Jahre nach den ersten Schriftzeichen trennen darin erstmals Striche und Punkte die Worte."},
    {id:"h",t:"<strong>h)</strong> Um dies zu verstehen, muss man die Arbeitsweise in den mittelalterlichen Schreibstuben beachten."}
  ],
  textps:[
    "Jeder Smartphonebesitzer weiß, dass ein Semikolon und eine Klammer Freundschaften retten können. Braucht es doch nur diese zwei Symbole, und eine Beleidigung wird zum Witz ;). Selbst mit bloßen Satzzeichen lassen sich mitunter noch ganze Konversationen gestalten. {0}",
    "Als Ur-Satzzeichen gelten die Markierungen in einem Text auf der sogenannten Mescha-Stele aus dem 9. Jahrhundert vor Christus. {1} Dass es damals schon Satzzeichen gab, heißt aber nicht, dass sie auch allgemein Verwendung fanden. Werke der griechischen und lateinischen Dichter sind aufgezeichnet in der sogenannten <em>scriptio continua</em>.",
    "{2} Experten erklären das so: In jener ersten Phase war Schrift primär eine Erinnerungsstütze für den professionellen Vortrag.",
    "{3} Spätestens die Erfindung des Buchdrucks durch Gutenberg läutete dann die zweite große Phase ein.",
    "Es regte sich aber auch Kritik: Um 1750 befand Jean-Jacques Rousseau, dass es einer niedergeschriebenen Sprache an Lebendigkeit mangele. {4} So verwendete etwa Goethe Punkt und Komma noch nach Gutdünken.",
    "Dabei scheint schon lange vorher Bedarf an größeren Ausdrucksmöglichkeiten bestanden zu haben. {5} In der Philosophie, glaubte er, könnten solche durchaus nützlich sein.",
    "{6} Die extreme Verkürzung der schriftlichen Kommunikation mittels Kurznachrichten verlangt anscheinend wieder nach einer Simulation von Mündlichkeit. Der Erfolg der Emojis entspringt dem Wunsch, Affekte in geschriebene Sprache zu überführen."
  ],
  qs:[
    {n:1,ans:"g",
     exp:"Satz g): «Rund 2500 Jahre nach den ersten Schriftzeichen trennen darin erstmals Striche und Punkte die Worte.» — <em>darin</em> = in der Mescha-Stele. Konkrete zeitliche Einordnung.",
     textref:"«Mescha-Stele aus dem 9. Jahrhundert vor Christus» → <em>darin</em> (= in der Stele) in Satz g).",
     rule:"<em>darin</em> = in der Stele. Zeitliche Progression: erste Schriftzeichen → Satzzeichen 2500 Jahre später."},
    {n:2,ans:"f",
     exp:"Satz f): «In ihr reiht sich Buchstabe an Buchstabe, Wort an Wort.» — <em>ihr</em> (fem.) = der scriptio continua. Beschreibt ununterbrochenen Text.",
     textref:"«in der sogenannten scriptio continua» → <em>In ihr</em> in Satz f) = in der scriptio continua.",
     rule:"<em>ihr</em> (fem.) = scriptio continua (fem.). Genus-Übereinstimmung! Parallelismus Buchstabe/Wort beschreibt Kontinuität."},
    {n:3,ans:"d",
     exp:"Satz d): «Erst im Mittelalter kamen irische Mönche auf die Idee…» — Übergang von scriptio continua zur Lesbarkeit. <em>Erst</em> betont die Verzögerung.",
     textref:"scriptio continua (keine Zeichen) → <em>Erst im Mittelalter</em> → Buchdruck (nächster Absatz). Chronologie!",
     rule:"Zeitliche Abfolge: <em>Erst im Mittelalter</em> = только в Средневековье. Контекст до и после."},
    {n:4,ans:"b",
     exp:"Satz b): «Dabei konnte damals von verbindlichen Normen noch gar keine Rede sein.» — erklärt, warum Goethe Kommas nach Gutdünken setzen konnte.",
     textref:"«Goethe verwendete Punkt und Komma nach Gutdünken» → Satz b): damals keine verbindlichen Normen.",
     rule:"<em>Dabei + damals</em> → zeitlicher Rückbezug. Erklärt Goethes Freiheit."},
    {n:5,ans:"a",
     exp:"Satz a): «Bereits 1762 bemängelte Gottsched, dass es keine Zeichen für Staunen oder Mitleid gebe.» — historisches Beispiel für Bedarf an Ausdrucksmöglichkeiten.",
     textref:"«Bedarf an größeren Ausdrucksmöglichkeiten» → Satz a) liefert Beispiel. <em>er</em> im Folgesatz = Gottsched.",
     rule:"Satz a) belegt mit Datum (1762) die Behauptung. <em>er</em> im nächsten Satz = Gottsched."},
    {n:6,ans:"e",
     exp:"Satz e): «Erst viel später – mit den neuen Medien – ging dieser langgehegte Wunsch in Erfüllung.» — Gottscheds Wunsch (1762) erfüllte sich erst mit Emojis.",
     textref:"«dieser Wunsch» = Gottscheds Wunsch nach neuen Zeichen (Lücke 5). <em>Erst viel später</em> = mit Emojis.",
     rule:"<em>dieser Wunsch</em> → Anaphora auf Gottscheds Wunsch. <em>Erst viel später</em> = только много позже."}
  ],
  vocab:["verbindlich — обязательный","die Norm — норма","scriptio continua — непрерывное письмо без пробелов","in Erfüllung gehen — сбываться","die Erinnerungsstütze — инструмент памяти"]
},

{
  id:"lv1_3", type:"Leseverstehen Teil 1", kind:"lv1",
  title:"Die Hamburger-Hypothese",
  desc:"6 Satz-Zuordnungen · Textrekonstruktion · C1",
  satze:[
    {id:"z",t:"<strong>z)</strong> Weil der Burger eine amerikanische Ikone ist, haben etliche US-Städte Anspruch auf die Vaterschaft erhoben. <em>(Beispiel)</em>"},
    {id:"a",t:"<strong>a)</strong> Beweisen lässt es sich zwar nicht, aber dass der Hamburger an Bord eines Auswandererschiffs erfunden wurde, ist bislang die wahrscheinlichste Annahme."},
    {id:"b",t:"<strong>b)</strong> Diese beiden Beispiele zeigen, dass gehacktes Fleisch wohl generell als Hamburg bezeichnet wurde."},
    {id:"c",t:"<strong>c)</strong> Diese besagt, dass die aus dieser Stadt stammenden Brüder Frank und Charles Menches Ende des 19. Jahrhunderts den Burger erfunden haben sollen."},
    {id:"d",t:"<strong>d)</strong> Ebenso liegt die Vermutung nahe, dass ein Ort namens Hamburg dem Burger seinen Namen gab."},
    {id:"e",t:"<strong>e)</strong> In vielen amerikanischen Kochbüchern aus dieser Zeit findet man Rezepte für seine Zubereitung."},
    {id:"f",t:"<strong>f)</strong> Kochen war dort vermutlich schwierig – doch pur und ohne Beilagen schmeckte das zähe Pökelfleisch nicht besonders."},
    {id:"g",t:"<strong>g)</strong> Noch immer wird der Name Hamburger oft irrtümlich auf das Wort <em>ham</em> (Englisch für Schinken) zurückgeführt."},
    {id:"h",t:"<strong>h)</strong> Tatsächlich wurde wohl in keiner dieser Städte der erste Burger serviert, denn ein ähnliches Gericht gab es schon früher."}
  ],
  textps:[
    "«Heißen Leute aus Hamburg wirklich Hamburger?» Jeder Hanseat, der die Vereinigten Staaten bereist, muss sich diese Frage stellen lassen. {0} Das Städtchen Seymour in Wisconsin etwa verweist stolz darauf, der Imbiss-Betreiber Charlie Nagreen habe 1885 die ersten flachgedrückten Fleischbällchen serviert.",
    "Eine ähnliche Geschichte tischt die Gemeinde Hamburg (Bundesstaat New York) der Öffentlichkeit auf: {1} Dokumente, die das beweisen, haben Hamburg und Seymour bislang ebenso wenig vorlegen können wie zahlreiche weitere Städte.",
    "{2} Bereits 50 Jahre zuvor kannte man das Hamburg Steak, das der Vorläufer des Hamburgers gewesen sein dürfte. In New Yorks Restaurant Delmonico's soll bereits 1834 ein solches auf der Karte gestanden haben.",
    "Als gesichert gilt hingegen, dass das Hamburg Steak Anfang des 20. Jahrhunderts in den USA ein gängiges Gericht war. {3} In einer Rezeptsammlung von 1911 ist das Hamburg Steak eine zu Kugeln geformte Hacksmasse. {4}",
    "Das Oxford English Dictionary von 1802 definierte Hamburg Steak als gepökeltes Rindfleisch. Es ist plausibel anzunehmen, dass die Hunderttausenden von Auswanderern, die über die Hansestadt in die USA verschifft wurden, das Fleisch als Proviant mit sich führten.",
    "Die Verpflegung an Bord war miserabel, zumindest für die weniger betuchten Zwischendeck-Passagiere. {5} Was lag da näher, als es in Streifen zu schneiden und – mangels Teller und Besteck – zwischen zwei Scheiben Brot zu klemmen?",
    "{6} Die Immigranten-Notverpflegung wäre dann zwischenzeitlich bei Delmonico's zum Gourmet-Schmankerl der US-Oberschicht aufgestiegen."
  ],
  qs:[
    {n:1,ans:"c",
     exp:"Satz c): «Diese besagt, dass die Brüder Menches den Burger erfunden haben sollen.» — <em>Diese</em> (fem.) = die Geschichte (fem., zuletzt erwähnt).",
     textref:"«Eine ähnliche Geschichte tischt die Gemeinde Hamburg auf» → <em>Diese</em> in Satz c) = diese Geschichte.",
     rule:"<em>Diese</em> (fem., Nom.) → bezieht sich auf <em>die Geschichte</em> (fem.). Genus beachten!"},
    {n:2,ans:"h",
     exp:"Satz h): «Tatsächlich wurde wohl in keiner dieser Städte der erste Burger serviert, denn ein ähnliches Gericht gab es schon früher.» — Überleitung zu «50 Jahre zuvor».",
     textref:"«Keine Beweise» → Satz h): tatsächlich war das Gericht schon früher bekannt. <em>denn</em> = ведь.",
     rule:"<em>denn</em> = потому что, ведь. Kausale Begründung für die Skepsis gegenüber allen Städten."},
    {n:3,ans:"e",
     exp:"Satz e): «In vielen amerikanischen Kochbüchern … findet man Rezepte für seine Zubereitung.» — <em>seine</em> = das Hamburg Steaks. Belegt «ein gängiges Gericht».",
     textref:"«das Hamburg Steak … war ein gängiges Gericht» → Satz e) belegt das mit Kochbüchern. <em>seine</em> = das Steaks.",
     rule:"<em>seine</em> (mask.) = das Hamburg Steaks. Satz e) liefert den Quellenbeleg."},
    {n:4,ans:"b",
     exp:"Satz b): «Diese beiden Beispiele zeigen…» — <em>diese beiden Beispiele</em> = Delmonico's (1834) + Rezeptsammlung (1911). Fazit nach zwei Quellen.",
     textref:"Delmonico's 1834 + Rezeptsammlung 1911 → Satz b) zieht Fazit: «diese beiden Beispiele».",
     rule:"<em>Diese beiden Beispiele</em> → fasst zwei genannte Quellen zusammen. Klassischer Fazit-Satz."},
    {n:5,ans:"f",
     exp:"Satz f): «Kochen war dort vermutlich schwierig – doch pur schmeckte das zähe Pökelfleisch nicht besonders.» — <em>dort</em> = an Bord. Erklärt, warum Brot als Lösung diente.",
     textref:"«Die Verpflegung an Bord war miserabel» → <em>dort</em> = an Bord. Kausalität: schwieriges Kochen + schlechter Geschmack → Brot.",
     rule:"<em>dort</em> = an Bord. Kausalität: Problem → Lösung im nächsten Satz."},
    {n:6,ans:"a",
     exp:"Satz a): «Beweisen lässt es sich zwar nicht, aber … ist bislang die wahrscheinlichste Annahme.» — relativierende Schlussfolgerung der gesamten Hypothese.",
     textref:"Gesamte Argumentation → Satz a): <em>zwar … aber</em> = хотя ... но. Einschränkende Schlussfolgerung.",
     rule:"Struktur: <em>zwar … aber</em> = хотя ... но. Schlusssatz mit Einschränkung. Typisch für LV1-Schlusssatz."}
  ],
  vocab:["die Vaterschaft — авторство, происхождение","sich rühmen — хвалиться","gängig — распространённый","das Pökelfleisch — солёное мясо","der Proviant — провизия, паёк","miserabel — ужасный, скверный"]
},

// ═══════════════════════════════════════════════════════
// LESEVERSTEHEN TEIL 2
// ═══════════════════════════════════════════════════════
{
  id:"lv2_1", type:"Leseverstehen Teil 2", kind:"lv2",
  title:"Welche Bedeutung haben Träume?",
  desc:"6 Fragen · In welchem Abschnitt? · C1",
  textps:[
    "<strong>Abschnitt a:</strong> Was für ein Schrecken! Gerade bekamen Sie die Nachricht, im Lotto gewonnen zu haben … Und dann reißt Sie der Wecker grausam aus dem Schlaf. Im Traum passieren oft skurrile Dinge. Wir überwinden die Schwerkraft, erheben uns wie ein Vogel. Oft durchleben wir in verfremdeter Form die Widrigkeiten des Alltags. In Albträumen suchen uns unsere größten Ängste heim.",
    "<strong>Abschnitt b:</strong> Doch welche Bedeutung haben Träume eigentlich? Für Götterbotschaften hielt man in der Antike das nächtliche Kopfkino. Wer leichtgläubig nach einem Schlüssel für Traumsymbole sucht, wird unzählige Websites finden. Dabei stellt sich die Frage, ob die Ansicht, Träume enthielten eine Bedeutung, möglicherweise auf einem Missverständnis basiert. Sind die nächtlichen Bilder nicht vielmehr sinnlose Abfallprodukte des Gehirns? Sollte man sie nicht am besten einfach ignorieren?",
    "<strong>Abschnitt c:</strong> Tatsächlich ist der Wahrheitsgehalt von Träumen umstritten. Zu den Klassikern gehört Sigmund Freuds 1899 erschienenes Werk «Die Traumdeutung»: Für den Begründer der Psychoanalyse manifestierten sich in Traumsymbolen unbewusste, verdrängte Wünsche. Der amerikanische Psychiater Allan Hobson erklärte Träume zum Resultat zufälliger Hirnaktivität, zu reinem Neuronengeflimmer ohne Sinngehalt. Doch auch von dieser These rückt die Psychologie inzwischen wieder ab.",
    "<strong>Abschnitt d:</strong> Diese Schwierigkeit könnte auch darin begründet liegen, dass der Gegenstand der Untersuchung nur schwer zu fassen ist. Im Allgemeinen wird als Traum eine psychische Aktivität während des Schlafes bezeichnet. Widerlegt ist mittlerweile die früher weitverbreitete Annahme, dass wir nur in den sogenannten REM-Phasen träumen – wir träumen die ganze Nacht. Die Frage nach dem «Wann» scheint also mittlerweile geklärt zu sein. <em>Da bleibt es nur zu hoffen, dass auch bald die interessante Frage geklärt wird, warum im Schlaf Bilder in unserem Kopf entstehen.</em>",
    "<strong>Abschnitt e:</strong> Eine interessante Spur verfolgen dabei Neuroforscher, die bildgebende Verfahren nutzen, um das träumende Gehirn zu beobachten. Im Traumzustand ist der präfrontale Cortex gehemmt, jener Bereich für Logik, Sinn und Moral. So kann sich die Fantasie befreit von Zwängen entfalten. Wenn wir uns mit unseren Träumen beschäftigen, sollten wir vor allem das rechte Maß einhalten."
  ],
  qs:[
    {n:7,t:"In welchem Abschnitt äußert sich die Autorin abfällig / skeptisch? (пренебрежительно / скептически)",
     opts:["a","b","c","d","e"],ans:"b",
     exp:"Abschnitt b): «Sollte man sie nicht am besten einfach ignorieren?» + «Wer leichtgläubig sucht» = negativ-skeptische Bewertung. Die Autorin zweifelt an der Bedeutung von Träumen.",
     rule:"Abfällig = пренебрежительно: Konjunktiv + negatives Adjektiv (<em>leichtgläubig</em>). Rhetorische Frage mit negativem Unterton."},
    {n:8,t:"In welchem Abschnitt gibt die Autorin einen Rat? (даёт совет)",
     opts:["a","b","c","d","e"],ans:"e",
     exp:"Abschnitt e): «sollten wir vor allem das rechte Maß einhalten» = klar formulierter Rat. Konjunktiv II von <em>sollen</em> als Empfehlung.",
     rule:"Rat erkennbar: <em>sollten</em> (Konj.II als Höflichkeitsform) + <em>vor allem</em> = рекомендация."},
    {n:9,t:"In welchem Abschnitt liefert die Autorin Definitionen? (даёт определения)",
     opts:["a","b","c","d","e"],ans:"d",
     exp:"Abschnitt d): «Im Allgemeinen wird als Traum eine psychische Aktivität während des Schlafes bezeichnet.» = klassische Definition mit Passiv + <em>als … bezeichnet werden</em>.",
     rule:"Definition: <em>als … bezeichnet werden</em> (Passiv) + <em>Im Allgemeinen</em> = официальное определение."},
    {n:10,t:"In welchem Abschnitt spricht die Autorin einen Wunsch aus? (выражает пожелание)",
     opts:["a","b","c","d","e"],ans:"d",
     exp:"Abschnitt d): «<em>Da bleibt es nur zu hoffen</em>, dass auch bald die interessante Frage geklärt wird …» — ACHTUNG: Dieser Satz kursiv im Text! Wunsch/Hoffnung der Autorin.",
     rule:"<em>es bleibt zu hoffen</em> = остаётся надеяться = выражение пожелания. Этот сatz выделен курсивом в тексте!"},
    {n:11,t:"In welchem Abschnitt stellt die Autorin verschiedene Standpunkte gegenüber? (сопоставляет точки зрения)",
     opts:["a","b","c","d","e"],ans:"c",
     exp:"Abschnitt c): Freud (Träume = unbewusste Wünsche) vs. Hobson (Träume = zufällige Hirnaktivität) = zwei entgegengesetzte Theorien.",
     rule:"Kontrastierung: zwei Namen + gegenteilige Thesen. Два имени + противоположные теории."},
    {n:12,t:"In welchem Abschnitt wirft die Autorin Bedenken auf? (выражает сомнения)",
     opts:["a","b","c","d","e"],ans:"b",
     exp:"Abschnitt b): «Sind die nächtlichen Bilder nicht vielmehr sinnlose Abfallprodukte des Gehirns?» = rhetorische Frage mit Zweifel.",
     rule:"Bedenken: rhetorische Frage + <em>nicht vielmehr</em> = не скорее? = выражение сомнения."}
  ],
  vocab:["skurril — нелепый, причудливый","die Traumdeutung — толкование снов","das Neuronengeflimmer — мерцание нейронов","es bleibt zu hoffen — остаётся надеяться","das rechte Maß einhalten — соблюдать меру"]
},

// ═══════════════════════════════════════════════════════
// LESEVERSTEHEN TEIL 3
// ═══════════════════════════════════════════════════════
{
  id:"lv3_1", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Zukunftsperspektiven für die Verpackungsindustrie",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Verbraucher erachten sie als selbstverständlich und nehmen sie oft nicht einmal bewusst wahr: die Verpackung. Sie ist aus Kundensicht nicht nur unerlässlich für einen bequemen Transport, sondern sie ist auch wesentlich an der Kaufentscheidung beteiligt. Im Unterbewusstsein lenkt die Verpackung unser Kaufverhalten.",
    "<strong>Abs.2:</strong> Doch die Verpackung ist mehr als eine Verkaufshilfe. Im vergangenen Jahr beschäftigte die deutsche Verpackungsindustrie rund 110.000 Personen und erzielte einen Umsatz von 31,8 Milliarden Euro. Mengenmäßig stellten Verpackungen aus Papier und Pappe mit 48% den größten Anteil. Am umsatzstärksten sind allerdings Kunststoffverpackungen: auf sie entfallen 41% des Gesamtumsatzes. Um im Wettbewerb bestehen zu können, muss die deutsche Verpackungsindustrie auf Innovation setzen. Sonst drohen hohe Verluste.",
    "<strong>Abs.3:</strong> An erster Stelle ist die Transportmöglichkeit zu nennen. Unmittelbar damit verbunden ist der Schutz des verpackten Produktes: Schutz vor Verschmutzung, vor Beschädigung, vor Sauerstoff oder vor Licht. Weiterhin dient die Verpackung der Information und der Selbstdarstellung von Marken.",
    "<strong>Abs.4:</strong> Verbraucher stellen ständig wachsende Anforderungen an Hygiene und Qualität. So waren etwa Mineralöle in Schokoladenverpackungen aus Karton gefunden worden. In Lebensmittelverpackungen gelangen Mineralöle in der Regel über Druckfarben. Das ließe sich vermeiden, wenn Papier ohne Mineralöle verwendet würde.",
    "<strong>Abs.5:</strong> Der größte Trend heißt eindeutig Nachhaltigkeit. Die Kunden fordern recycelbare Verpackungen, die wiederverwertet werden können. Das bedeutet für die Verpackungsindustrie: biologisch abbaubare Materialien und eine Optimierung der Herstellungsprozesse müssen in den Mittelpunkt der Forschungen gestellt werden.",
    "<strong>Abs.6:</strong> Solange Kunststoffe auf der Basis von Rohöl noch nicht durch nachwachsende Rohstoffe ersetzt werden können, müssen sie möglichst effizient eingesetzt werden. Um weniger Material zu verbrauchen, werden immer dünnere Folien entwickelt.",
    "<strong>Abs.7:</strong> Die Verpackung der Zukunft soll nicht nur sparsam und nachhaltig sein, sondern auch neue Funktionen übernehmen. <em>Künftig wird es Folien geben, die anzeigen, ob das Produkt noch genießbar oder bereits verdorben ist, weit genauer als das bisherige Mindesthaltbarkeitsdatum.</em>",
    "<strong>Abs.8:</strong> Innovationen gibt es nicht nur in Bezug auf Bequemlichkeit. Auch emotional soll die Verpackung den Kunden ansprechen – über möglichst viele Sinne. Den Geruchssinn sprechen Duftetiketten an. Letztes Jahr wurde eine sprechende Verpackung ausgezeichnet. <em>Nur der Geschmackssinn bleibt noch außer vor.</em>",
    "<strong>Abs.9:</strong> Ein System, das kürzlich vorgestellt wurde, besteht aus zwei Etiketten. Wenn man das äußere Etikett dreht, erscheint ein durchsichtiges Fenster. So wird die für Informationen verfügbare Fläche fast verdoppelt.",
    "<strong>Abs.10:</strong> Die Unternehmen müssen für anpassungsfähige Produktionsprozesse sorgen, damit sie im Rahmen von Sonderaktionen rasch kleine Mengen neuer Verpackungen liefern können."
  ],
  qs:[
    {n:13,t:"Konsumenten nehmen Verpackungen als gegeben hin.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.1: «Verbraucher erachten sie als selbstverständlich» = als gegeben hinnehmen.",
     textref:"«Verbraucher erachten sie als selbstverständlich und nehmen sie oft nicht einmal bewusst wahr.»",
     rule:"Paraphrase: <em>als selbstverständlich erachten</em> = воспринимать как само собой разумеющееся."},
    {n:14,t:"Der Umsatz der deutschen Verpackungsindustrie ist bei Papier- und Pappverpackungen am höchsten.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: Papier/Pappe = mengenmäßig 48% (größter Anteil MENGE), aber UMSATZSTÄRKSTE = Kunststoffverpackungen (41% des Umsatzes). Menge ≠ Umsatz!",
     textref:"«Mengenmäßig … Papier und Pappe mit 48% … Am umsatzstärksten sind allerdings Kunststoffverpackungen.»",
     rule:"WICHTIG: <em>mengenmäßig</em> ≠ <em>umsatzmäßig</em>. Количество ≠ выручка. Типичная ловушка!"},
    {n:15,t:"Die Konkurrenz aus Niedriglohnländern bescherte der Verpackungsindustrie milliardenschwere Einbußen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: Konkurrenz <em>droht</em> (Gefahr, nicht Tatsache). Von tatsächlichen Einbußen steht nichts.",
     textref:"«Sonst drohen hohe Verluste.» — drohen = только угроза, ещё не случилось.",
     rule:"<em>drohen</em> = угрожать ≠ eingetreten sein (уже произошло). Модальность важна!"},
    {n:16,t:"Verpackungen dienen ursprünglich dem Schutz vor Verschmutzung.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «An erster Stelle ist die Transportmöglichkeit zu nennen. Unmittelbar damit verbunden ist der Schutz … vor Verschmutzung.» = ursprüngliche Funktion.",
     textref:"«An erster Stelle … Schutz vor Verschmutzung, vor Beschädigung …»",
     rule:"<em>ursprünglich</em> = изначально. Abs.3 beschreibt primäre Aufgaben = ursprüngliche Funktionen."},
    {n:17,t:"Verbraucherverbände warnen vor Mineralöl in Verpackungen.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Mineralöle werden erwähnt (Abs.4), aber von <em>Verbraucherverbänden</em> steht nichts.",
     textref:"Abs.4 erwähnt Mineralöle, aber kein Wort über Verbraucherverbände.",
     rule:"x = Thema existiert (Mineralöle), aber DIESER Aspekt (Verbände) kommt nicht vor."},
    {n:18,t:"Die Verpackungsindustrie muss in Zukunft die Forschung in den Mittelpunkt stellen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «bioabbaubare Materialien und Optimierung der Herstellungsprozesse» müssen in den Mittelpunkt – nicht «die Forschung» allgemein.",
     textref:"«biologisch abbaubare Materialien … müssen in den Mittelpunkt der Forschungen gestellt werden.»",
     rule:"Aussage verallgemeinert. Text nennt spezifische Aspekte; Aussage sagt «Forschung» allgemein."},
    {n:19,t:"Immer mehr Forscher versuchen als Alternative zu Plastik Bio-Kunststoffe zu entwickeln.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Bio-Kunststoffe als solche werden nicht erwähnt.",
     textref:"Abs.6 erwähnt dünnere Folien und nachwachsende Rohstoffe, aber keine Bio-Kunststoffe.",
     rule:"x = dieses spezifische Thema (Bio-Kunststoffe) kommt im Text nicht vor."},
    {n:20,t:"Innovative Lebensmittelverpackungen werden die Angabe des Mindesthaltbarkeitsdatums überflüssig machen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.7 (kursiv): Folien zeigen Frische «weit genauer als das bisherige Mindesthaltbarkeitsdatum» → impliziert, MHD wird überflüssig.",
     textref:"«Folien, die anzeigen … weit genauer als das bisherige Mindesthaltbarkeitsdatum.» (kursiv hervorgehoben!)",
     rule:"Logische Schlussfolgerung: genauere Anzeige → MHD wird überflüssig. Kursiv-Text im Original lesen!"},
    {n:21,t:"Um attraktiv zu sein, sprechen Verpackungen schon heute alle fünf Sinne an.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.8 (kursiv): «Nur der Geschmackssinn bleibt noch außer vor.» = Geschmackssinn wird NICHT angesprochen.",
     textref:"«Nur der Geschmackssinn bleibt noch außer vor.» (kursiv im Text!)",
     rule:"<em>außer vor bleiben</em> = оставаться исключением. Не все 5 чувств!"},
    {n:22,t:"Verbraucherinformationen brauchen in Zukunft fast doppelt so viel Platz auf der Verpackung.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.9: verfügbare Fläche wird fast verdoppelt — aber nicht weil Infos mehr Platz brauchen, sondern weil Technik mehr Platz bietet.",
     textref:"«So wird die für Informationen verfügbare Fläche fast verdoppelt.»",
     rule:"Kausalität umgekehrt: mehr verfügbare Fläche ≠ mehr Platz benötigt."},
    {n:23,t:"Die Unternehmen müssen ihre Produktion besser an den kurzfristigen Bedarf anpassen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.10: «damit sie … rasch kleine Mengen … liefern können» = kurzfristiger Bedarf.",
     textref:"«damit sie im Rahmen von Sonderaktionen rasch kleine Mengen neuer Verpackungen liefern können.»",
     rule:"Paraphrase: <em>rasch kleine Mengen liefern</em> = auf kurzfristigen Bedarf reagieren."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Sprechende Tüten und duftende Kartons","b) Nachhaltige Verpackungen auf dem Vormarsch","c) Zukunftsperspektiven für die Verpackungsindustrie"],
     ans:"c) Zukunftsperspektiven für die Verpackungsindustrie",
     exp:"c) deckt ALLE Themen ab: Wirtschaft, Schutzfunktion, Hygiene, Nachhaltigkeit, Innovation, Sinne, Information, Flexibilität. a) = zu eng, b) = zu eng.",
     textref:"Gesamter Text behandelt: Wirtschaft + Schutz + Hygiene + Nachhaltigkeit + Sinnesansprache + Flexibilität.",
     rule:"Makroaufgabe: Überschrift muss den GESAMTEN Text abdecken, nicht nur einen Teilaspekt!"}
  ],
  vocab:["erachten als — считать, расценивать","recycelbar — пригодный для переработки","das Mindesthaltbarkeitsdatum — срок годности","außer vor bleiben — оставаться исключением","anpassungsfähig — способный к адаптации","die Sonderaktion — акция, специальное предложение"]
},

{
  id:"lv3_2", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Camping — ein Trend mit Geschichte",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Wilde Natur, Freiheit und ein Hauch Romantik. Mit diesen Verheißungen lockte das Camping von Anfang an. Bis heute gibt es Menschen, die auf alle Bequemlichkeiten eines Hotelzimmers verzichten und die Nächte draußen verbringen, ob im Schlafsack unter freiem Himmel oder im Zelt.",
    "<strong>Abs.2:</strong> Als Begründer des modernen Campings gilt der britische Schneider Thomas Hiram Holding, der Ende des 19. Jahrhunderts mit dem Fahrrad durch weite Teile Schottlands und Irlands unterwegs war. Seine Liebe zum Camping wollte er mit anderen teilen: Er schrieb ein Buch über das Zelten. Seitdem galt er als höchste Autorität in puncto Camping. Holding war der Meinung, dass Camping keine für das weibliche Geschlecht geeignete Aktivität sei.",
    "<strong>Abs.3:</strong> Nicht lange Zeit später, nämlich nach dem Ersten Weltkrieg, erlebte das Camping in Westeuropa einen Aufschwung. Viele Menschen ließen sich von der neuen Art zu reisen überzeugen: Camping war schließlich günstig und dennoch erholsam. Immer mehr Campingplätze wurden angelegt.",
    "<strong>Abs.4:</strong> Als der erste Wohnwagen entwickelt wurde, damals noch Wohnauto genannt, kam beim Camping ein neues Komfortniveau auf. Die Ausstattungen, die die frühen Camper als Errungenschaften betrachteten, wirken im Rückblick freilich ziemlich bescheiden.",
    "<strong>Abs.5:</strong> Der Zweite Weltkrieg unterbrach die Erfolgsgeschichte der Campingbewegung, doch mit dem Wirtschaftswunder wurde Camping wieder populär. Die Unternehmen begannen, Wohnwagen, Zelte und Campingzubehör in großem Stil anzubieten. Auch die Anzahl der Campingplätze in ganz Europa stieg nun sprunghaft an.",
    "<strong>Abs.6:</strong> In den 1970er Jahren schritt die Perfektionierung des Campings weiter voran: Die Wohnwagen wurden komfortabler ausgestattet, und auch die Campingplätze lockten mit neuen Annehmlichkeiten wie Sanitärräumen mit Duschanlagen.",
    "<strong>Abs.7:</strong> Campingreisen wurden zunehmend von der neuen Konkurrenz des Pauschalurlaubs verdrängt. Dennoch ist die Geschichte des Campens nicht zu Ende. Viele Campingplätze erschließen sich neue Zielgruppen, indem sie etwa spezielle Angebote für Familien oder Senioren entwickeln.",
    "<strong>Abs.8:</strong> Nicht zu vergessen ist die edle Variante des Campings, das «Glamping». Der Begriff stammt aus dem Englischen und verbindet glamour und camping. Glamping-Unterkünfte sind komplett eingerichtet mit Bad, Dusche und WC, einer Küche und mehreren Schlafzimmern."
  ],
  qs:[
    {n:13,t:"Camping-Urlauber verzichten auf den Komfort des Hotels.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.1: «die auf alle Bequemlichkeiten eines Hotelzimmers verzichten».",
     textref:"«die auf alle Bequemlichkeiten eines Hotelzimmers verzichten und die Nächte draußen verbringen»",
     rule:"Direkte Paraphrase: auf Komfort verzichten = auf Bequemlichkeiten verzichten."},
    {n:14,t:"Thomas Hiram Holding glaubte, dass Frauen ebenso gut campen können wie Männer.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: «Holding war der Meinung, dass Camping keine für das weibliche Geschlecht geeignete Aktivität sei.» = Gegenteil!",
     textref:"«Holding war der Meinung, dass Camping keine für das weibliche Geschlecht geeignete Aktivität sei.»",
     rule:"Aussage negiert das Textgegenteil. <em>keine geeignete Aktivität</em> ≠ «kann ebenso gut campen»."},
    {n:15,t:"Holding war der erste, der Zelte in Massen produzieren ließ.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Holding schrieb ein Buch, aber von Massenproduktion steht nichts.",
     textref:"Abs.2: Holding schrieb ein Buch und galt als Autorität. Kein Bezug zu Produktion.",
     rule:"x = dieser Aspekt (Massenproduktion) kommt im Text nicht vor."},
    {n:16,t:"Camping war nach dem Ersten Weltkrieg beliebt, weil es eine preisgünstige Urlaubsform war.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «Camping war schließlich günstig und dennoch erholsam.»",
     textref:"«Camping war schließlich günstig und dennoch erholsam.»",
     rule:"Direkte Paraphrase: günstig = preisgünstig."},
    {n:17,t:"In den 1950er Jahren wurden in Europa weniger Campingplätze eröffnet als je zuvor.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «die Anzahl der Campingplätze … stieg nun sprunghaft an» (nach dem Wirtschaftswunder = 1950er).",
     textref:"«die Anzahl der Campingplätze in ganz Europa stieg nun sprunghaft an.»",
     rule:"sprunghaft ansteigen ≠ weniger werden. Direkter Widerspruch."},
    {n:18,t:"Das Angebot an Campingzubehör verringerte sich nach dem Zweiten Weltkrieg.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «Die Unternehmen begannen, Wohnwagen, Zelte und Campingzubehör … in großem Stil anzubieten.» = Gegenteil!",
     textref:"«Die Unternehmen begannen, Wohnwagen, Zelte und Campingzubehör in großem Stil anzubieten.»",
     rule:"Direkter Widerspruch: mehr Angebot ≠ weniger Angebot."},
    {n:19,t:"Campingplätze boten in den 1970er Jahren nur grundlegende Einrichtungen an.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.6: «die Campingplätze lockten mit neuen Annehmlichkeiten wie Sanitärräumen mit Duschanlagen.» = mehr als Grundlegendes!",
     textref:"«Campingplätze lockten mit neuen Annehmlichkeiten wie Sanitärräumen mit Duschanlagen.»",
     rule:"Annehmlichkeiten ≠ grundlegende Einrichtungen. Widerspruch im Text."},
    {n:20,t:"Die zunehmende Popularität von Pauschalreisen schadete dem Campingurlaub.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.7: «Campingreisen wurden zunehmend von der neuen Konkurrenz des Pauschalurlaubs verdrängt.»",
     textref:"«Campingreisen wurden zunehmend von der neuen Konkurrenz des Pauschalurlaubs verdrängt.»",
     rule:"verdrängen = вытеснять = schaden. Direkte Kausalbeziehung."},
    {n:21,t:"Glamping ist eine weniger teure Alternative zu klassischem Camping.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.8: Glamping = «edle Variante» mit Vollausstattung (Bad, Küche etc.) = teurer, nicht günstiger.",
     textref:"«die edle Variante des Campings … komplett eingerichtet mit Bad, Dusche und WC»",
     rule:"<em>edel</em> = благородный, дорогой. Vollausstattung ≠ günstige Alternative."},
    {n:22,t:"Campingplätze entwickeln heute spezielle Angebote für bestimmte Personengruppen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.7: «spezielle Angebote für Familien oder Senioren entwickeln.»",
     textref:"«Viele Campingplätze erschließen sich neue Zielgruppen, indem sie spezielle Angebote für Familien oder Senioren entwickeln.»",
     rule:"Direkte Paraphrase: bestimmte Personengruppen = Familien oder Senioren."},
    {n:23,t:"Das Wort Glamping ist eine Kombination aus zwei englischen Wörtern.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.8: «Der Begriff stammt aus dem Englischen und verbindet glamour und camping.» = zwei englische Wörter.",
     textref:"«Der Begriff stammt aus dem Englischen und verbindet glamour und camping.»",
     rule:"Kombination = verbindet. Direkte Information im Text."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Campingboom im Wirtschaftswunder","b) Camping — Von der Nischenaktivität zum Massenphänomen","c) Glamping: die neue Art des Reisens"],
     ans:"b) Camping — Von der Nischenaktivität zum Massenphänomen",
     exp:"b) deckt den gesamten Text ab: Geschichte des Campings von Beginn bis heute. a) = nur ein Aspekt (1950er), c) = nur letzter Absatz.",
     textref:"Gesamter Text: von Holding (Pionier) bis Glamping (heute) = Entwicklung des Campings.",
     rule:"Makroaufgabe: Überschrift muss ALLE Abschnitte abdecken."}
  ],
  vocab:["die Verheißung — обещание, соблазн","sprunghaft — скачкообразно, резко","verdrängen — вытеснять","erschließen — осваивать, открывать","edel — благородный, изысканный","die Annehmlichkeit — удобство, комфорт"]
}

]; // end TESTS

// ═══════════════════════════════════════════════════════
// КАК ДОБАВИТЬ НОВЫЙ ТЕСТ:
// 1. Скопируй один из блоков выше
// 2. Измени id (уникальное), title, desc
// 3. Для SBS: измени text и qs
// 4. Для LV1: измени satze, textps, qs
// 5. Для LV2/LV3: измени textps, qs
// 6. ans для LV3: "+", "-" или "x"
// 7. Сохрани файл и обнови страницу в браузере
// ═══════════════════════════════════════════════════════
