// test-lv3b.js — TELC C1
window.TELC_TEST = {
  id:"lv3_2", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Camping — ein Trend mit Geschichte",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Wilde Natur, Freiheit und ein Hauch Romantik. Mit diesen Verheißungen lockte das Camping von Anfang an. Bis heute gibt es Menschen, die auf alle Bequemlichkeiten eines Hotelzimmers verzichten und die Nächte draußen verbringen, ob im Schlafsack unter freiem Himmel oder im Zelt.",
    "<strong>Abs.2:</strong> Als Begründer des modernen Campings gilt der britische Schneider Thomas Hiram Holding, der Ende des 19. Jahrhunderts mit dem Fahrrad durch weite Teile Schottlands und Irlands unterwegs war. Seine Liebe zum Camping wollte er mit anderen teilen: Er schrieb ein Buch über das Zelten. Seitdem galt er als höchste Autorität in puncto Camping. Holding war der Meinung, dass Camping keine für das weibliche Geschlecht geeignete Aktivität sei.",
    "<strong>Abs.3:</strong> Nicht lange Zeit später, nämlich nach dem Ersten Weltkrieg, erlebte das Camping in Westeuropa einen Aufschwung. Viele Menschen ließen sich von der neuen Art zu reisen überzeugen: Camping war schließlich günstig und dennoch erholsam. Immer mehr Campingplätze wurden angelegt.",
    "<strong>Abs.4:</strong> Als der erste Wohnwagen entwickelt wurde, damals noch Wohnauto genannt, kam beim Camping ein neues Komfortniveau auf. Die Ausstattungen, die die frühen Camper als Errungenschaften betrachteten, wirken im Rückblick freilich ziemlich bescheiden.",
    "<strong>Abs.5:</strong> Der Zweite Weltkrieg unterbrach die Erfolgsgeschichte der Campingbewegung, doch mit dem Wirtschaftswunder wurde Camping wieder populär. Die Unternehmen begannen, Wohnwagen, Zelte und Campingzubehör in großem Stil anzubieten. Auch die Anzahl der Campingplätze in ganz Europa stieg nun sprunghaft an.",
    "<strong>Abs.6:</strong> In den 1970er Jahren schritt die Perfektionierung des Campings weiter voran: Die Wohnwagen wurden komfortabler ausgestattet, und auch die Campingplätze lockten mit neuen Annehmlichkeiten wie Sanitärräumen mit Duschanlagen.",
    "<strong>Abs.7:</strong> Campingreisen wurden zunehmend von der neuen Konkurrenz des Pauschalurlaubs verdrängt. Dennoch ist die Geschichte des Campens nicht zu Ende. Viele Campingplätze erschließen sich neue Zielgruppen, indem sie etwa spezielle Angebote für Familien oder Senioren entwickeln.",
    "<strong>Abs.8:</strong> Nicht zu vergessen ist die edle Variante des Campings, das «Glamping». Der Begriff stammt aus dem Englischen und verbindet glamour und camping. Glamping-Unterkünfte sind komplett eingerichtet mit Bad, Dusche und WC, einer Küche und mehreren Schlafzimmern."
  ],
  qs:[
    {n:13,t:"Camping-Urlauber verzichten auf den Komfort des Hotels.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.1: «die auf alle Bequemlichkeiten eines Hotelzimmers verzichten».",
     textref:"«die auf alle Bequemlichkeiten eines Hotelzimmers verzichten und die Nächte draußen verbringen»",
     rule:"Direkte Paraphrase: auf Komfort verzichten = auf Bequemlichkeiten verzichten."},
    {n:14,t:"Thomas Hiram Holding glaubte, dass Frauen ebenso gut campen können wie Männer.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: «Holding war der Meinung, dass Camping keine für das weibliche Geschlecht geeignete Aktivität sei.» = Gegenteil!",
     textref:"«Holding war der Meinung, dass Camping keine für das weibliche Geschlecht geeignete Aktivität sei.»",
     rule:"Aussage negiert das Textgegenteil. <em>keine geeignete Aktivität</em> ≠ «kann ebenso gut campen»."},
    {n:15,t:"Holding war der erste, der Zelte in Massen produzieren ließ.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Holding schrieb ein Buch, aber von Massenproduktion steht nichts.",
     textref:"Abs.2: Holding schrieb ein Buch und galt als Autorität. Kein Bezug zu Produktion.",
     rule:"x = dieser Aspekt (Massenproduktion) kommt im Text nicht vor."},
    {n:16,t:"Camping war nach dem Ersten Weltkrieg beliebt, weil es eine preisgünstige Urlaubsform war.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «Camping war schließlich günstig und dennoch erholsam.»",
     textref:"«Camping war schließlich günstig und dennoch erholsam.»",
     rule:"Direkte Paraphrase: günstig = preisgünstig."},
    {n:17,t:"In den 1950er Jahren wurden in Europa weniger Campingplätze eröffnet als je zuvor.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «die Anzahl der Campingplätze … stieg nun sprunghaft an» (nach dem Wirtschaftswunder = 1950er).",
     textref:"«die Anzahl der Campingplätze in ganz Europa stieg nun sprunghaft an.»",
     rule:"sprunghaft ansteigen ≠ weniger werden. Direkter Widerspruch."},
    {n:18,t:"Das Angebot an Campingzubehör verringerte sich nach dem Zweiten Weltkrieg.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «Die Unternehmen begannen, Wohnwagen, Zelte und Campingzubehör … in großem Stil anzubieten.» = Gegenteil!",
     textref:"«Die Unternehmen begannen, Wohnwagen, Zelte und Campingzubehör in großem Stil anzubieten.»",
     rule:"Direkter Widerspruch: mehr Angebot ≠ weniger Angebot."},
    {n:19,t:"Campingplätze boten in den 1970er Jahren nur grundlegende Einrichtungen an.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.6: «die Campingplätze lockten mit neuen Annehmlichkeiten wie Sanitärräumen mit Duschanlagen.» = mehr als Grundlegendes!",
     textref:"«Campingplätze lockten mit neuen Annehmlichkeiten wie Sanitärräumen mit Duschanlagen.»",
     rule:"Annehmlichkeiten ≠ grundlegende Einrichtungen. Widerspruch im Text."},
    {n:20,t:"Die zunehmende Popularität von Pauschalreisen schadete dem Campingurlaub.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.7: «Campingreisen wurden zunehmend von der neuen Konkurrenz des Pauschalurlaubs verdrängt.»",
     textref:"«Campingreisen wurden zunehmend von der neuen Konkurrenz des Pauschalurlaubs verdrängt.»",
     rule:"verdrängen = вытеснять = schaden. Direkte Kausalbeziehung."},
    {n:21,t:"Glamping ist eine weniger teure Alternative zu klassischem Camping.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.8: Glamping = «edle Variante» mit Vollausstattung (Bad, Küche etc.) = teurer, nicht günstiger.",
     textref:"«die edle Variante des Campings … komplett eingerichtet mit Bad, Dusche und WC»",
     rule:"<em>edel</em> = благородный, дорогой. Vollausstattung ≠ günstige Alternative."},
    {n:22,t:"Campingplätze entwickeln heute spezielle Angebote für bestimmte Personengruppen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.7: «spezielle Angebote für Familien oder Senioren entwickeln.»",
     textref:"«Viele Campingplätze erschließen sich neue Zielgruppen, indem sie spezielle Angebote für Familien oder Senioren entwickeln.»",
     rule:"Direkte Paraphrase: bestimmte Personengruppen = Familien oder Senioren."},
    {n:23,t:"Das Wort Glamping ist eine Kombination aus zwei englischen Wörtern.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.8: «Der Begriff stammt aus dem Englischen und verbindet glamour und camping.» = zwei englische Wörter.",
     textref:"«Der Begriff stammt aus dem Englischen und verbindet glamour und camping.»",
     rule:"Kombination = verbindet. Direkte Information im Text."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Campingboom im Wirtschaftswunder","b) Camping — Von der Nischenaktivität zum Massenphänomen","c) Glamping: die neue Art des Reisens"],
     ans:"b) Camping — Von der Nischenaktivität zum Massenphänomen",
     exp:"b) deckt den gesamten Text ab: Geschichte des Campings von Beginn bis heute. a) = nur ein Aspekt (1950er), c) = nur letzter Absatz.",
     textref:"Gesamter Text: von Holding (Pionier) bis Glamping (heute) = Entwicklung des Campings.",
     rule:"Makroaufgabe: Überschrift muss ALLE Abschnitte abdecken."}
  ],
  vocab:["die Verheißung — обещание, соблазн","sprunghaft — скачкообразно, резко","verdrängen — вытеснять","erschließen — осваивать, открывать","edel — благородный, изысканный","die Annehmlichkeit — удобство, комфорт"]
};
