// test-sb5.js — Sprachbausteine
window.TELC_TEST = {
  id:"sb5", type:"Sprachbausteine", kind:"sb",
  title:"Plastik im Ozean — ein globales Problem",
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Die Ozeane unserer Erde <strong>(25)</strong> in Plastik. Jedes Jahr gelangen schätzungsweise acht Millionen Tonnen Plastikabfälle ins Meer — eine Menge, die schwer <strong>(26)</strong> ist. Die Folgen für Meeresökosysteme sind <strong>(27)</strong>: Tiere verenden in Plastiknetzen, Seevögel <strong>(28)</strong> ihre Küken mit Plastikteilen, Fische nehmen Mikroplastik <strong>(29)</strong> Nahrung auf.</p><p>Besonders <strong>(30)</strong> ist das sogenannte Mikroplastik. Es <strong>(31)</strong> aus dem Zerfall größerer Plastikteile oder wird direkt in Kosmetikprodukten eingesetzt. Diese winzigen Partikel <strong>(32)</strong> von Kleinstorganismen aufgenommen und gelangen so in die Nahrungskette — letztendlich auch <strong>(33)</strong> den menschlichen Organismus.</p><p>Die Lösung des Problems erfordert Maßnahmen auf verschiedenen Ebenen. Auf individueller Ebene <strong>(34)</strong> Verbraucher Einwegplastik <strong>(35)</strong>. Auf politischer Ebene brauchen wir verbindliche internationale Abkommen. Die EU hat bereits Schritte <strong>(36)</strong>: Einwegplastikartikel wie Strohhalme und Wattestäbchen sind in der Union seit 2021 verboten.</p><p>Doch trotz positiver Ansätze bleibt die Lage ernst. Viele Entwicklungsländer <strong>(37)</strong> über keine ausreichenden Entsorgungsinfrastrukturen. Müll landet <strong>(38)</strong> in Flüssen, die ihn ins Meer transportieren. Selbst wenn die Welt heute <strong>(39)</strong> aufhörte, Plastik zu produzieren, würde das bereits im Ozean <strong>(40)</strong> Plastik noch Jahrhunderte <strong>(41)</strong>.</p><p>Technologische Innovationen bieten jedoch Hoffnung. Spezielle Schiffe sammeln treibende Plastikteile <strong>(42)</strong> der Meeresoberfläche ein. Biologen arbeiten an Bakterien, die Plastik <strong>(43)</strong> können. Und die Entwicklung biologisch <strong>(44)</strong> Alternativen zu herkömmlichem Plastik schreitet voran. Es bleibt zu <strong>(45)</strong>, dass diese Lösungen <strong>(46)</strong> genug kommen.</p>',
  qs:[
    {n:25, ctx:"Die Ozeane unserer Erde ___ in Plastik",
     opts:["a) ersticken","b) schwimmen","c) versinken","d) ertrinken"],
     ans:"c) versinken",
     exp:"<strong>c) versinken</strong> — <em>in etw. versinken</em> = тонуть в чём-л. (перен.). <em>Versinken in Plastik</em> = тонуть в пластике. <em>Ersticken</em> = задыхаться (тоже возможно, но реже в этом контексте).",
     rule:"<em>in etw. versinken</em> = тонуть в чём-л. (переносное значение). Коллокация для экологических текстов."},
    {n:26, ctx:"eine Menge, die schwer ___ ist",
     opts:["a) abzuschätzen","b) einzuschätzen","c) vorzustellen","d) zu begreifen"],
     ans:"d) zu begreifen",
     exp:"<strong>d) zu begreifen</strong> — <em>schwer zu begreifen</em> = трудно осознать, трудно вообразить. Natürlichste Formulierung für unvorstellbar große Mengen.",
     rule:"<em>schwer zu + Infinitiv</em> = трудно (что-л. сделать). <em>Begreifen</em> = понять/осознать."},
    {n:27, ctx:"Die Folgen für Meeresökosysteme sind ___",
     opts:["a) dramatisch","b) erschreckend","c) gravierend","d) weitreichend"],
     ans:"c) gravierend",
     exp:"<strong>c) gravierend</strong> = серьёзный, весомый (C1). Typischer C1-Begriff für ernsthafte Probleme. <em>Dramatisch</em> zu umgangssprachlich, <em>weitreichend</em> = weitreichend (räumlich).",
     rule:"<em>gravierend</em> = серьёзный, значительный (формальный C1-термин). Ср.: <em>schwerwiegend</em> = тяжёлый."},
    {n:28, ctx:"Seevögel ___ ihre Küken mit Plastikteilen",
     opts:["a) ernähren","b) füttern","c) füllen","d) versorgen"],
     ans:"b) füttern",
     exp:"<strong>b) füttern</strong> — <em>Küken füttern</em> = кормить птенцов. Typische Kollokation: Tier + Küken füttern.",
     rule:"<em>füttern</em> = кормить (животных). Коллокация: <em>Küken füttern</em>. Ср.: <em>ernähren</em> = питать (более общее)."},
    {n:29, ctx:"Fische nehmen Mikroplastik ___ Nahrung auf",
     opts:["a) als","b) anstatt","c) statt","d) wie"],
     ans:"a) als",
     exp:"<strong>a) als</strong> — <em>etw. als Nahrung aufnehmen</em> = воспринимать как пищу, принимать в качестве. Фиксация: <em>als etw. aufnehmen</em>.",
     rule:"<em>als + Nomen</em> = в качестве чего-л. Фиксация: <em>als Nahrung aufnehmen</em>."},
    {n:30, ctx:"Besonders ___ ist das sogenannte Mikroplastik",
     opts:["a) alarmierend","b) bedrohlich","c) gefährlich","d) problematisch"],
     ans:"d) problematisch",
     exp:"<strong>d) problematisch</strong> — passt strukturell: «Besonders problematisch ist X» = наиболее проблематичным является X. Формальный стиль.",
     rule:"Struktur: <em>Besonders + Adjektiv + ist</em> = особенно … является. <em>Problematisch</em> = проблематичный (C1)."},
    {n:31, ctx:"Es ___ aus dem Zerfall größerer Plastikteile",
     opts:["a) bildet sich","b) entsteht","c) ergibt sich","d) resultiert"],
     ans:"b) entsteht",
     exp:"<strong>b) entsteht</strong> — <em>etw. entsteht aus etw.</em> = что-л. образуется из чего-л. Стандартная коллокация для научных текстов.",
     rule:"<em>entstehen aus + Dativ</em> = образовываться из чего-л. Научный стиль (C1)."},
    {n:32, ctx:"Diese winzigen Partikel ___ von Kleinstorganismen aufgenommen",
     opts:["a) dürfen","b) können","c) sollen","d) werden"],
     ans:"d) werden",
     exp:"<strong>d) werden</strong> — Passiv: <em>werden … aufgenommen</em> = поглощаются. Passiv ist die korrekte Konstruktion hier.",
     rule:"Passiv Präsens: <em>werden + Partizip II</em> = поглощаются. Hier kein Modalverb nötig."},
    {n:33, ctx:"gelangen so in die Nahrungskette — letztendlich auch ___ den menschlichen Organismus",
     opts:["a) bei","b) bis in","c) in","d) zu"],
     ans:"b) bis in",
     exp:"<strong>b) bis in</strong> — <em>bis in + Akk.</em> = вплоть до чего-л. Betont die Reichweite der Kontamination.",
     rule:"<em>bis in + Akk.</em> = вплоть до, даже до (betont Reichweite/Endpunkt)."},
    {n:34, ctx:"Auf individueller Ebene ___ Verbraucher Einwegplastik",
     opts:["a) dürfen meiden","b) können meiden","c) sollen meiden","d) sollten meiden"],
     ans:"d) sollten meiden",
     exp:"<strong>d) sollten meiden</strong> — Konjunktiv II als Empfehlung/Forderung. <em>Sollten</em> = рекомендательный тон (мягче, чем müssen).",
     rule:"<em>sollten</em> (Konj.II) = следует, рекомендуется. Вежливая рекомендация (C1-Register)."},
    {n:35, ctx:"sollten Verbraucher Einwegplastik ___",
     opts:["a) ablehnen","b) meiden","c) verbieten","d) vermeiden"],
     ans:"d) vermeiden",
     exp:"<strong>d) vermeiden</strong> — <em>Einwegplastik vermeiden</em> = избегать одноразового пластика. <em>Meiden</em> = сторониться (чаще о людях/местах). <em>Vermeiden</em> — стандарт для экологических текстов.",
     rule:"<em>vermeiden</em> = избегать (действие/вещь). Коллокация: <em>Plastik vermeiden</em>."},
    {n:36, ctx:"Die EU hat bereits Schritte ___",
     opts:["a) eingenommen","b) eingeleitet","c) genommen","d) unternommen"],
     ans:"b) eingeleitet",
     exp:"<strong>b) eingeleitet</strong> — <em>Schritte einleiten</em> = предпринять шаги (официальный/политический контекст). <em>Unternehmen</em> тоже возможно, но <em>einleiten</em> — формальнее.",
     rule:"<em>Schritte/Maßnahmen einleiten</em> = предпринять меры (официальный стиль, C1)."},
    {n:37, ctx:"Viele Entwicklungsländer ___ über keine ausreichenden Entsorgungsinfrastrukturen",
     opts:["a) besitzen","b) haben","c) verfügen","d) weisen"],
     ans:"c) verfügen",
     exp:"<strong>c) verfügen</strong> — <em>über etw. verfügen</em> = располагать чем-л. Формальная альтернатива к <em>haben</em>. Typisch für C1-Texte.",
     rule:"<em>über etw. verfügen</em> = располагать чем-л. (формально). = <em>etw. haben</em>, но книжнее."},
    {n:38, ctx:"Müll landet ___ in Flüssen",
     opts:["a) immer","b) meist","c) oft","d) stattdessen"],
     ans:"d) stattdessen",
     exp:"<strong>d) stattdessen</strong> — <em>stattdessen</em> = вместо этого. Конкретизирует: вместо надлежащей утилизации мусор попадает в реки.",
     rule:"<em>stattdessen</em> = вместо этого (указывает на альтернативное/нежелательное развитие событий)."},
    {n:39, ctx:"Selbst wenn die Welt heute ___ aufhörte, Plastik zu produzieren",
     opts:["a) abrupt","b) komplett","c) schlagartig","d) vollständig"],
     ans:"c) schlagartig",
     exp:"<strong>c) schlagartig</strong> = внезапно, разом. <em>Schlagartig aufhören</em> = резко прекратить. Typische Adverbialformulierung für radikale Szenarien.",
     rule:"<em>schlagartig</em> = внезапно, разом (C1-Adverb). Ср.: <em>plötzlich</em> = разговорнее."},
    {n:40, ctx:"würde das bereits im Ozean ___ Plastik",
     opts:["a) angesammelte","b) befindliche","c) existierende","d) vorhandene"],
     ans:"d) vorhandene",
     exp:"<strong>d) vorhandene</strong> — <em>vorhandenes Plastik</em> = уже имеющийся пластик. Standardformulierung für «bereits existierende Dinge».",
     rule:"<em>vorhanden</em> = имеющийся, существующий. <em>das vorhandene X</em> = уже существующий X."},
    {n:41, ctx:"würde das bereits im Ozean vorhandene Plastik noch Jahrhunderte ___",
     opts:["a) bestehen","b) dauern","c) fortbestehen","d) verbleiben"],
     ans:"c) fortbestehen",
     exp:"<strong>c) fortbestehen</strong> — <em>fortbestehen</em> = продолжать существовать. Betont die Kontinuität: das Plastik würde weiterhin existieren.",
     rule:"<em>fortbestehen</em> = продолжать существовать/сохраняться. Trennbar: fort|bestehen."},
    {n:42, ctx:"Spezielle Schiffe sammeln treibende Plastikteile ___ der Meeresoberfläche ein",
     opts:["a) an","b) auf","c) über","d) von"],
     ans:"d) von",
     exp:"<strong>d) von</strong> — <em>von der Meeresoberfläche einsammeln</em> = собирать с поверхности моря. Präposition <em>von</em> für Ort des Aufsammelns.",
     rule:"<em>etw. von etw. einsammeln</em> = собирать с (поверхности). Präposition <em>von</em> + Oberfläche."},
    {n:43, ctx:"Biologen arbeiten an Bakterien, die Plastik ___ können",
     opts:["a) abbauen","b) auflösen","c) beseitigen","d) zersetzen"],
     ans:"a) abbauen",
     exp:"<strong>a) abbauen</strong> — <em>Plastik abbauen</em> = разлагать пластик (биологически). Fachbegriff für biologischen Abbau.",
     rule:"<em>abbauen</em> = разлагать (биол.). Fachbegriff: <em>biologischer Abbau</em> = биологическое разложение."},
    {n:44, ctx:"die Entwicklung biologisch ___ Alternativen zu herkömmlichem Plastik",
     opts:["a) abbaubarer","b) auflösbarer","c) recycelbarer","d) verwertbarer"],
     ans:"a) abbaubarer",
     exp:"<strong>a) abbaubarer</strong> — <em>biologisch abbaubar</em> = биоразлагаемый. Standardbegriff für nachhaltige Materialien.",
     rule:"<em>biologisch abbaubar</em> = биоразлагаемый (стандартный экологический термин C1)."},
    {n:45, ctx:"Es bleibt zu ___, dass diese Lösungen",
     opts:["a) hoffen","b) sehen","c) wünschen","d) erwarten"],
     ans:"a) hoffen",
     exp:"<strong>a) hoffen</strong> — <em>es bleibt zu hoffen</em> = остаётся надеяться. Фиксированное выражение для выражения надежды (C1).",
     rule:"ФИКСАЦИЯ: <em>es bleibt zu hoffen, dass</em> = остаётся надеяться, что (C1, книжн.)."},
    {n:46, ctx:"dass diese Lösungen ___ genug kommen",
     opts:["a) bald","b) früh","c) früher","d) rechtzeitig"],
     ans:"d) rechtzeitig",
     exp:"<strong>d) rechtzeitig</strong> — <em>rechtzeitig genug kommen</em> = прийти достаточно своевременно. <em>Rechtzeitig</em> = вовремя. Kombination mit <em>genug</em> = достаточно своевременно.",
     rule:"<em>rechtzeitig</em> = вовремя, своевременно. Kollokation: <em>rechtzeitig + genug</em> = достаточно вовремя."}
  ],
  vocab:["versinken in — тонуть в (перен.)","gravierend — серьёзный, значительный","Mikroplastik — микропластик","einleiten — предпринимать (меры)","verfügen über — располагать чем-л.","stattdessen — вместо этого","schlagartig — внезапно, разом","biologisch abbaubar — биоразлагаемый","es bleibt zu hoffen — остаётся надеяться","rechtzeitig — вовремя, своевременно"]
};
