// test-lv3g.js — TELC C1
window.TELC_TEST = {
  id:"lv3_7", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Macht Reisen wirklich glücklich?",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> «Reisen bildet» — dieser Satz stammt von Goethe und gilt bis heute als unbestrittene Weisheit. Doch macht Reisen wirklich glücklich und klüger? Psychologen und Glücksforscher haben sich dieser Frage angenommen und kommen zu differenzierten Ergebnissen. Die Antwort hängt weniger davon ab, wohin man reist, als davon, wie und warum man reist.",
    "<strong>Abs.2:</strong> Kurzfristig erzeugt Reisen zweifellos positive Gefühle. Schon die Vorfreude auf eine bevorstehende Reise steigert das Wohlbefinden nachweislich stärker als die Reise selbst. Studien zeigen, dass Urlauber bereits Wochen vor dem Abflug glücklicher sind — und dieser Effekt nach der Rückkehr schnell wieder nachlässt.",
    "<strong>Abs.3:</strong> Langfristig sind die Effekte des Reisens komplexer. Wer nur in der Touristenblase bleibt, Sehenswürdigkeiten abhakt und im All-inclusive-Hotel residiert, bringt oft kaum persönliche Entwicklung mit nach Hause. Tiefgreifende Begegnungen mit anderen Kulturen hingegen können das Weltbild erweitern und die Kreativität fördern.",
    "<strong>Abs.4:</strong> Besonders Langzeitreisen und Work-and-Travel-Aufenthalte scheinen positive Wirkungen zu haben. Junge Menschen, die längere Zeit im Ausland leben und arbeiten, berichten häufiger von gesteigertem Selbstvertrauen, größerer Offenheit und besseren Fremdsprachenkenntnissen. Das Scheitern in fremder Umgebung — zum Beispiel die Verständigung zu scheitern — lehrt Resilienz.",
    "<strong>Abs.5:</strong> Allerdings warnen Psychologen vor einer Flucht in den Urlaub. Wer durch ständiges Reisen inneren Konflikten aus dem Weg geht, löst diese damit nicht. «Man kann nicht vor sich selbst davonlaufen», sagt Glücksforscherin Prof. Dr. Sonja Lyubomirsky. Reisen als Allheilmittel für Unzufriedenheit funktioniert selten dauerhaft.",
    "<strong>Abs.6:</strong> Umweltpsychologen betonen zudem: Die Art des Reisens ist entscheidend. Wer aktiv reist — wandert, radelt, mit öffentlichen Verkehrsmitteln fährt — erlebt das Ziel intensiver als jemand, der nur von Sehenswürdigkeit zu Sehenswürdigkeit kutschiert wird. Und: Wer auf den ökologischen Fußabdruck achtet, reist nicht nur nachhaltiger, sondern auch bewusster."
  ],
  qs:[
    {n:13,t:"Schon das Planen einer Reise kann das Wohlbefinden steigern.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.2: «Schon die Vorfreude auf eine bevorstehende Reise steigert das Wohlbefinden … stärker als die Reise selbst.»",
     textref:"«Schon die Vorfreude auf eine bevorstehende Reise steigert das Wohlbefinden nachweislich stärker als die Reise selbst.»",
     rule:"<em>Vorfreude</em> = anticipation = Planen/Erwarten. <em>schon</em> = уже (подчёркивает раннее начало)."},
    {n:14,t:"Das Glücksgefühl nach einer Reise hält in der Regel lange an.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: «dieser Effekt nach der Rückkehr schnell wieder nachlässt» = hält nicht lange an.",
     textref:"«dieser Effekt nach der Rückkehr schnell wieder nachlässt.»",
     rule:"<em>nachlassen</em> = ослабевать, проходить ≠ lange anhalten. Direkter Widerspruch."},
    {n:15,t:"Touristen, die nur Sehenswürdigkeiten besuchen, profitieren weniger von Reisen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «Wer nur in der Touristenblase bleibt … bringt oft kaum persönliche Entwicklung mit nach Hause.»",
     textref:"«Wer nur in der Touristenblase bleibt … bringt oft kaum persönliche Entwicklung mit nach Hause.»",
     rule:"kaum persönliche Entwicklung = weniger profitieren. Paraphrase des Textinhalts."},
    {n:16,t:"Längere Auslandsaufenthalte können das Selbstvertrauen stärken.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «berichten häufiger von gesteigertem Selbstvertrauen, größerer Offenheit.»",
     textref:"«berichten häufiger von gesteigertem Selbstvertrauen, größerer Offenheit und besseren Fremdsprachenkenntnissen.»",
     rule:"<em>gesteigertes Selbstvertrauen</em> = gestärktes Selbstvertrauen. Direkte Aussage."},
    {n:17,t:"Das Scheitern im Ausland hat ausschließlich negative Folgen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.4: «Das Scheitern in fremder Umgebung … lehrt Resilienz.» = positive Folge!",
     textref:"«Das Scheitern in fremder Umgebung … lehrt Resilienz.»",
     rule:"<em>Resilienz lernen</em> = positive Konsequenz. <em>ausschließlich negativ</em> widerspricht dem Text."},
    {n:18,t:"Reisen kann als Therapie bei psychischen Problemen eingesetzt werden.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.5 warnt vor Flucht durch Reisen, aber Therapie wird nicht erwähnt.",
     textref:"Abs.5 erwähnt keine therapeutische Anwendung von Reisen.",
     rule:"x = Therapie-Aspekt kommt im Text nicht vor."},
    {n:19,t:"Reisen löst laut Psychologen keine inneren Konflikte.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.5: «Wer durch ständiges Reisen inneren Konflikten aus dem Weg geht, löst diese damit nicht.»",
     textref:"«Wer durch ständiges Reisen inneren Konflikten aus dem Weg geht, löst diese damit nicht.»",
     rule:"Direkte Aussage. Paraphrase: löst nicht = bestätigt die Aussage."},
    {n:20,t:"Aktives Reisen führt zu einer intensiveren Erfahrung des Reiseziels.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.6: «Wer aktiv reist … erlebt das Ziel intensiver.»",
     textref:"«Wer aktiv reist — wandert, radelt … — erlebt das Ziel intensiver.»",
     rule:"Direkte Aussage im Text."},
    {n:21,t:"Goethes Aussage über Reisen wird von modernen Psychologen vollständig bestätigt.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.1: «kommen zu differenzierten Ergebnissen» = nicht vollständige Bestätigung, sondern differenziertes Bild.",
     textref:"«Psychologen … kommen zu differenzierten Ergebnissen.»",
     rule:"<em>differenziert</em> = неоднозначный ≠ vollständig bestätigt."},
    {n:22,t:"Nachhaltiges Reisen hat laut Text auch einen positiven Effekt auf das Reiseerlebnis.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.6: «Wer auf den ökologischen Fußabdruck achtet, reist nicht nur nachhaltiger, sondern auch bewusster.»",
     textref:"«reist nicht nur nachhaltiger, sondern auch bewusster.»",
     rule:"<em>bewusster reisen</em> = intensiveres/besseres Erlebnis = positiver Effekt."},
    {n:23,t:"Die Studie aus Abs.2 zeigt, dass die Reise selbst den größten Glückseffekt hat.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: «die Vorfreude … steigert das Wohlbefinden … stärker als die Reise selbst» = Gegenteil!",
     textref:"«Schon die Vorfreude … steigert das Wohlbefinden nachweislich stärker als die Reise selbst.»",
     rule:"Vorfreude > Reise selbst. Die Aussage kehrt die Relation um."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Warum Vorfreude besser ist als die Reise selbst","b) Reisen und Glück: Ein differenzierter Blick der Psychologie","c) Ökologisch reisen — der neue Trend"],
     ans:"b) Reisen und Glück: Ein differenzierter Blick der Psychologie",
     exp:"b) deckt alle Aspekte ab: Glückseffekte (pos/neg), Kurzzeit vs. Langzeit, Reisestil, Psychologen-Perspektive. a) = nur Abs.2, c) = nur Abs.6.",
     textref:"Gesamter Text: verschiedene Perspektiven auf Reisen und Glück aus psychologischer Sicht.",
     rule:"<em>differenzierter Blick</em> = nuancierte Betrachtung = Kernaussage von Abs.1. Makroüberschrift!"}
  ],
  vocab:["differenziert — дифференцированный, многогранный","die Vorfreude — предвкушение","nachlassen — ослабевать, проходить","die Resilienz — жизнестойкость, устойчивость","die Touristenblase — туристический пузырь","der ökologische Fußabdruck — экологический след","kutschieren — перевозить (как в карете)"]
};
