// test-lv3f.js — TELC C1
window.TELC_TEST = {
  id:"lv3_6", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Sabbatical — Auszeit vom Beruf",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Ein Jahr lang reisen, ein Buch schreiben oder einfach durchatmen — immer mehr Arbeitnehmer träumen davon, eine längere Auszeit vom Beruf zu nehmen. Das sogenannte Sabbatical, ursprünglich an Hochschulen für Forschungsfreijahre genutzt, hat längst Einzug in die Arbeitswelt gehalten. Doch was steckt hinter dem Trend, und was sind die Konsequenzen?",
    "<strong>Abs.2:</strong> Der Begriff Sabbatical leitet sich vom hebräischen Wort «Sabbat» ab. Ursprünglich bezeichnete er das siebte Ruhejahr, in dem Felder brach lagen und Schulden erlassen wurden. In der modernen Arbeitswelt bedeutet Sabbatical eine bezahlte oder unbezahlte Auszeit, die in der Regel zwischen drei Monaten und einem Jahr dauert.",
    "<strong>Abs.3:</strong> Die Gründe für ein Sabbatical sind vielfältig. Viele Arbeitnehmer möchten sich erholen und neue Energie tanken. Andere nutzen die Zeit für Weiterbildung, ein ehrenamtliches Projekt oder die Pflege von Angehörigen. Manche wollen einfach reisen oder kreativ tätig sein. Gemeinsam ist allen: der Wunsch nach Abstand vom beruflichen Alltag.",
    "<strong>Abs.4:</strong> Nicht jeder kann sich ein Sabbatical leisten. Zum einen müssen finanzielle Rücklagen vorhanden sein. Zum anderen hängt es vom Arbeitgeber ab: Ein gesetzlicher Anspruch auf ein Sabbatical existiert in Deutschland nicht. Viele Unternehmen sind jedoch bereit, entsprechende Vereinbarungen zu treffen, da sie erkannt haben, dass ausgeruhte Mitarbeiter produktiver sind.",
    "<strong>Abs.5:</strong> Studien zeigen, dass Menschen nach einem Sabbatical kreativer, motivierter und weniger anfällig für Burnout sind. Allerdings kehren nicht alle nach der Auszeit in ihren alten Job zurück. Manche erkennen während des Sabbaticals, dass sie einen beruflichen Neustart anstreben. Arbeitgeber sehen das naturgemäß mit gemischten Gefühlen.",
    "<strong>Abs.6:</strong> Wer ein Sabbatical plant, sollte es sorgfältig vorbereiten. Finanzielle Planung, Absprachen mit dem Arbeitgeber und eine klare Vorstellung davon, was man mit der Zeit anfangen möchte, sind entscheidend. Experten raten zudem, die Auszeit nicht zu überladen — wer ständig unter Druck steht, etwas «Sinnvolles» zu tun, verpasst den eigentlichen Erholungseffekt."
  ],
  qs:[
    {n:13,t:"Das Sabbatical wurde ursprünglich in der freien Wirtschaft entwickelt.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.1: «ursprünglich an Hochschulen für Forschungsfreijahre genutzt» = nicht in der freien Wirtschaft.",
     textref:"«ursprünglich an Hochschulen für Forschungsfreijahre genutzt, hat längst Einzug in die Arbeitswelt gehalten.»",
     rule:"<em>ursprünglich an Hochschulen</em> ≠ in der freien Wirtschaft. Chronologische Reihenfolge beachten."},
    {n:14,t:"Der Begriff Sabbatical hat religiöse Wurzeln.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.2: «leitet sich vom hebräischen Wort Sabbat ab» = religiös-kulturelle Herkunft.",
     textref:"«Der Begriff Sabbatical leitet sich vom hebräischen Wort «Sabbat» ab.»",
     rule:"Hebräisch + Sabbat = religiöse Herkunft. <em>sich ableiten von</em> = происходить от."},
    {n:15,t:"Ein Sabbatical dauert in Deutschland gesetzlich mindestens sechs Monate.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.2 nennt «drei Monate bis ein Jahr», aber eine gesetzliche Mindestdauer wird nicht erwähnt.",
     textref:"«zwischen drei Monaten und einem Jahr dauert» — keine gesetzliche Mindestdauer genannt.",
     rule:"x = gesetzliche Mindestdauer kommt im Text nicht vor."},
    {n:16,t:"Arbeitnehmer in Deutschland haben keinen gesetzlichen Anspruch auf ein Sabbatical.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «Ein gesetzlicher Anspruch auf ein Sabbatical existiert in Deutschland nicht.»",
     textref:"«Ein gesetzlicher Anspruch auf ein Sabbatical existiert in Deutschland nicht.»",
     rule:"Direkte Aussage. Paraphrase = exakte Wiedergabe des Textes."},
    {n:17,t:"Alle Arbeitnehmer kehren nach dem Sabbatical zu ihrem früheren Arbeitgeber zurück.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «kehren nicht alle nach der Auszeit in ihren alten Job zurück.»",
     textref:"«Allerdings kehren nicht alle nach der Auszeit in ihren alten Job zurück.»",
     rule:"<em>nicht alle</em> = nicht 100%. Die Aussage «alle» ist falsch."},
    {n:18,t:"Arbeitgeber reagieren ausnahmslos positiv auf den Wunsch nach einem Sabbatical.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «Arbeitgeber sehen das … mit gemischten Gefühlen.» = nicht ausnahmslos positiv.",
     textref:"«Arbeitgeber sehen das naturgemäß mit gemischten Gefühlen.»",
     rule:"<em>gemischte Gefühle</em> = смешанные чувства ≠ ausnahmslos positiv."},
    {n:19,t:"Finanzielle Rücklagen sind eine Voraussetzung für ein Sabbatical.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «müssen finanzielle Rücklagen vorhanden sein.» = Bedingung.",
     textref:"«Zum einen müssen finanzielle Rücklagen vorhanden sein.»",
     rule:"<em>müssen vorhanden sein</em> = Pflichtbedingung = Voraussetzung."},
    {n:20,t:"Nach einem Sabbatical sind Arbeitnehmer produktiver und kreativer.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.5: «nach einem Sabbatical kreativer, motivierter und weniger anfällig für Burnout sind.»",
     textref:"«Menschen nach einem Sabbatical kreativer, motivierter und weniger anfällig für Burnout sind.»",
     rule:"Direkte Aussage. produktiver = motivierter (Synonym im Kontext)."},
    {n:21,t:"Experten empfehlen, die Auszeit mit möglichst vielen Aktivitäten zu füllen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.6: «nicht zu überladen — wer ständig unter Druck steht … verpasst den eigentlichen Erholungseffekt.» = Gegenteil!",
     textref:"«Experten raten zudem, die Auszeit nicht zu überladen.»",
     rule:"<em>nicht zu überladen</em> = nicht zu viel reinpacken ≠ mit Aktivitäten füllen."},
    {n:22,t:"Pflege von Familienangehörigen kann ein Grund für ein Sabbatical sein.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «die Pflege von Angehörigen» = ein genannter Grund.",
     textref:"«Andere nutzen die Zeit für Weiterbildung, ein ehrenamtliches Projekt oder die Pflege von Angehörigen.»",
     rule:"Direkte Nennung im Text als einer der vielen Gründe."},
    {n:23,t:"Die Planung eines Sabbaticals sollte möglichst spontan erfolgen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.6: «sollte es sorgfältig vorbereiten» = Gegenteil von spontan.",
     textref:"«Wer ein Sabbatical plant, sollte es sorgfältig vorbereiten.»",
     rule:"<em>sorgfältig vorbereiten</em> = тщательно готовиться ≠ spontan erfolgen."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Sabbatical: Warum Auszeiten Arbeitnehmer und Arbeitgeber gleichermaßen bereichern","b) Sabbatical — Chancen, Hürden und Tipps für die berufliche Auszeit","c) Weg mit dem Stress: Reisen als beste Therapie"],
     ans:"b) Sabbatical — Chancen, Hürden und Tipps für die berufliche Auszeit",
     exp:"b) deckt alle Aspekte ab: Definition + Gründe (Chancen) + Finanzierung/Recht (Hürden) + Planung (Tipps). a) = zu einseitig positiv, c) = zu eng.",
     textref:"Gesamter Text: Was ist Sabbatical + Gründe + Hürden + Wirkung + Planung.",
     rule:"Makroaufgabe: alle Themen (Definition, Hürden, Nutzen, Tipps) in der Überschrift abbilden."}
  ],
  vocab:["das Sabbatical — творческий/учебный отпуск","die Auszeit — перерыв, пауза","brach liegen — лежать под паром, простаивать","die Rücklage — резерв, накопления","anfällig — подверженный (болезням и т.д.)","überladen — перегружать","ehrenamtlich — волонтёрский, общественный"]
};
