// test-lv3c.js — TELC C1
window.TELC_TEST = {
  id:"lv3_3", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"MINT-Fächer: Nachwuchs gesucht",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> MINT — das klingt wie eine Zahnpasta, steht aber für Mathematik, Informatik, Naturwissenschaften und Technik. Bundesweit touren Initiativen, um junge Menschen für diese Fächer zu begeistern. Wie viel Geld jährlich in die MINT-Förderung fließt, lässt sich kaum berechnen.",
    "<strong>Abs.2:</strong> Ob Bund, Länder, Kommunen, Stiftungen, Unternehmen — eine MINT-Initiative zu starten, gehört in Deutschland inzwischen zum guten Ton. Im vergangenen Studienjahr haben sich knapp 340.000 Abiturientinnen und Abiturienten für ein MINT-Studium eingeschrieben, rund 40 Prozent aller Erstimmatrikulierten. Damit steht Deutschland besser da als viele andere Länder.",
    "<strong>Abs.3:</strong> Was auch immer für den jüngsten Boom verantwortlich ist — die Politik ist beim Thema MINT in den vergangenen Jahren deutlich vorangekommen. Aber wir sind noch lange nicht am Ziel. So fehlen in Deutschland nach Berechnungen des Kölner Instituts der deutschen Wirtschaft rund 161.000 MINT-Fachkräfte.",
    "<strong>Abs.4:</strong> Ein weiteres Problem: Noch immer gibt es in MINT-Fächern deutlich weniger Frauen als Männer. Zwar studiert in der Biologie inzwischen die Mehrheit weiblich; in den Ingenieurwissenschaften aber ist es noch nicht einmal ein Viertel.",
    "<strong>Abs.5:</strong> Und dann ist da noch die Frage der Qualität. Die Abbrecherquote ist bei MINT-Fächern besonders hoch. Nur rund die Hälfte der Studienanfänger schließt das Studium auch ab. Viele scheitern an den hohen Anforderungen im ersten Studienjahr. Mit Vorkursen vor dem Studium soll dem entgegengewirkt werden.",
    "<strong>Abs.6:</strong> Auch bei den Auszubildenden macht sich der demografische Wandel bemerkbar: Die Zahl der MINT-Azubis sank um acht Prozent. Das sei für die deutsche Wirtschaft ein ernstes Problem, sagen Experten."
  ],
  qs:[
    {n:13,t:"Die Ausgaben für die MINT-Förderung in Deutschland lassen sich genau beziffern.",
     opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.1: «lässt sich kaum berechnen» = Gegenteil von «genau beziffern».",
     textref:"«Wie viel Geld jährlich in die MINT-Förderung fließt, lässt sich kaum berechnen.»",
     rule:"<em>kaum berechnen</em> = едва можно подсчитать ≠ genau beziffern = точно определить. Прямое противоречие."},
    {n:14,t:"Der Anteil der MINT-Studierenden in Deutschland ist im internationalen Vergleich relativ hoch.",
     opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.2: «Damit steht Deutschland besser da als viele andere Länder.»",
     textref:"«Damit steht Deutschland besser da als viele andere Länder.»",
     rule:"Paraphrase: besser als viele andere Länder = im internationalen Vergleich relativ hoch."},
    {n:15,t:"Deutschland hat in den letzten Jahren den Bedarf an MINT-Fachkräften vollständig gedeckt.",
     opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.3 sagt, es fehlen 161.000 Fachkräfte — aber «vollständig gedeckt» kommt nicht vor.",
     textref:"«fehlen … rund 161.000 MINT-Fachkräfte» — aber vollständige Deckung wird nicht erwähnt.",
     rule:"x = dieser spezifische Aspekt (vollständige Deckung) kommt im Text nicht vor."},
    {n:16,t:"In den MINT-Ingenieurwissenschaften studieren weniger Frauen als Männer.",
     opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «in den Ingenieurwissenschaften … ist es noch nicht einmal ein Viertel» weiblich = deutlich weniger Frauen.",
     textref:"«in den Ingenieurwissenschaften aber ist es noch nicht einmal ein Viertel.»",
     rule:"Weniger als ein Viertel Frauen = deutlich weniger als Männer."},
    {n:17,t:"Vorkurse sollen helfen, die Abbrecherquote bei MINT-Studiengängen zu senken.",
     opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.5: «Mit Vorkursen vor dem Studium soll dem entgegengewirkt werden.» — <em>dem</em> = der hohen Abbrecherquote.",
     textref:"«Mit Vorkursen vor dem Studium soll dem entgegengewirkt werden.»",
     rule:"<em>dem entgegenwirken</em> = противодействовать этому = Abbrecherquote senken."},
    {n:18,t:"Große Unternehmen finanzieren die Mehrheit der MINT-Initiativen.",
     opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.2 nennt Unternehmen als eine von vielen Gruppen, aber Mehrheitsfinanzierung wird nicht erwähnt.",
     textref:"«Ob Bund, Länder, Kommunen, Stiftungen, Unternehmen» — alle gleichberechtigt erwähnt.",
     rule:"x = die spezifische Behauptung (Mehrheit durch Unternehmen) kommt nicht vor."},
    {n:19,t:"Die Zahl der MINT-Azubis ist in den letzten Jahren gestiegen.",
     opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.6: «Die Zahl der MINT-Azubis sank um acht Prozent.» = Gegenteil!",
     textref:"«Die Zahl der MINT-Azubis sank um acht Prozent.»",
     rule:"<em>sinken</em> ≠ steigen. Direkter Widerspruch zum Text."},
    {n:20,t:"In Deutschland fehlt es an ausreichend MINT-Fachkräften auf dem Arbeitsmarkt.",
     opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «fehlen in Deutschland … rund 161.000 MINT-Fachkräfte.»",
     textref:"«fehlen in Deutschland … rund 161.000 MINT-Fachkräfte»",
     rule:"Direkte Aussage im Text."},
    {n:21,t:"Mehr als die Hälfte der MINT-Studierenden schließt das Studium nicht ab.",
     opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.5: «Nur rund die Hälfte der Studienanfänger schließt das Studium auch ab.» = die andere Hälfte bricht ab.",
     textref:"«Nur rund die Hälfte der Studienanfänger schließt das Studium auch ab.»",
     rule:"50% schließen ab → mehr als 50% brechen ab. Логический вывод из текста."},
    {n:22,t:"In der Biologie studieren weniger Frauen als in den Ingenieurwissenschaften.",
     opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.4: Biologie = Mehrheit weiblich; Ingenieurwissenschaften = weniger als ein Viertel. Genau umgekehrt!",
     textref:"«in der Biologie inzwischen die Mehrheit weiblich; in den Ingenieurwissenschaften … nicht einmal ein Viertel.»",
     rule:"Text: mehr Frauen in Biologie als in Ingenieurwesen. Aussage behauptet das Gegenteil."},
    {n:23,t:"Der Fachkräftemangel bei MINT wird von Wirtschaftsexperten als ernstes Problem eingeschätzt.",
     opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.6: «Das sei für die deutsche Wirtschaft ein ernstes Problem, sagen Experten.»",
     textref:"«Das sei für die deutsche Wirtschaft ein ernstes Problem, sagen Experten.»",
     rule:"Direkte Paraphrase: sagen Experten = Wirtschaftsexperten einschätzen."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Frauen holen auf: MINT-Gleichstellung erreicht","b) MINT-Fächer: Wachsende Beteiligung, aber noch große Herausforderungen","c) Vorkurse als Lösung der MINT-Krise"],
     ans:"b) MINT-Fächer: Wachsende Beteiligung, aber noch große Herausforderungen",
     exp:"b) deckt den gesamten Text ab: positive Entwicklung (340.000 Studierende) + Probleme (Fachkräftemangel, Frauen, Abbrecherquote, Azubis). a) = falsch (Gleichstellung nicht erreicht), c) = zu eng.",
     textref:"Gesamter Text: Erfolge + Herausforderungen der MINT-Förderung.",
     rule:"<em>aber</em> in der Überschrift = Kontrast, der den gesamten Text widerspiegelt. Макрозаголовок!"}
  ],
  vocab:["die Abbrecherquote — процент бросающих учёбу","zum guten Ton gehören — считаться хорошим тоном","vorangekommen — продвинуться","entgegenwirken — противодействовать","sinken — падать, снижаться","der demografische Wandel — демографические изменения"]
};
