// test-lv3a.js — TELC C1
window.TELC_TEST = {
  id:"lv3_1", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Zukunftsperspektiven für die Verpackungsindustrie",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Verbraucher erachten sie als selbstverständlich und nehmen sie oft nicht einmal bewusst wahr: die Verpackung. Sie ist aus Kundensicht nicht nur unerlässlich für einen bequemen Transport, sondern sie ist auch wesentlich an der Kaufentscheidung beteiligt. Im Unterbewusstsein lenkt die Verpackung unser Kaufverhalten.",
    "<strong>Abs.2:</strong> Doch die Verpackung ist mehr als eine Verkaufshilfe. Im vergangenen Jahr beschäftigte die deutsche Verpackungsindustrie rund 110.000 Personen und erzielte einen Umsatz von 31,8 Milliarden Euro. Mengenmäßig stellten Verpackungen aus Papier und Pappe mit 48% den größten Anteil. Am umsatzstärksten sind allerdings Kunststoffverpackungen: auf sie entfallen 41% des Gesamtumsatzes. Um im Wettbewerb bestehen zu können, muss die deutsche Verpackungsindustrie auf Innovation setzen. Sonst drohen hohe Verluste.",
    "<strong>Abs.3:</strong> An erster Stelle ist die Transportmöglichkeit zu nennen. Unmittelbar damit verbunden ist der Schutz des verpackten Produktes: Schutz vor Verschmutzung, vor Beschädigung, vor Sauerstoff oder vor Licht. Weiterhin dient die Verpackung der Information und der Selbstdarstellung von Marken.",
    "<strong>Abs.4:</strong> Verbraucher stellen ständig wachsende Anforderungen an Hygiene und Qualität. So waren etwa Mineralöle in Schokoladenverpackungen aus Karton gefunden worden. In Lebensmittelverpackungen gelangen Mineralöle in der Regel über Druckfarben. Das ließe sich vermeiden, wenn Papier ohne Mineralöle verwendet würde.",
    "<strong>Abs.5:</strong> Der größte Trend heißt eindeutig Nachhaltigkeit. Die Kunden fordern recycelbare Verpackungen, die wiederverwertet werden können. Das bedeutet für die Verpackungsindustrie: biologisch abbaubare Materialien und eine Optimierung der Herstellungsprozesse müssen in den Mittelpunkt der Forschungen gestellt werden.",
    "<strong>Abs.6:</strong> Solange Kunststoffe auf der Basis von Rohöl noch nicht durch nachwachsende Rohstoffe ersetzt werden können, müssen sie möglichst effizient eingesetzt werden. Um weniger Material zu verbrauchen, werden immer dünnere Folien entwickelt.",
    "<strong>Abs.7:</strong> Die Verpackung der Zukunft soll nicht nur sparsam und nachhaltig sein, sondern auch neue Funktionen übernehmen. <em>Künftig wird es Folien geben, die anzeigen, ob das Produkt noch genießbar oder bereits verdorben ist, weit genauer als das bisherige Mindesthaltbarkeitsdatum.</em>",
    "<strong>Abs.8:</strong> Innovationen gibt es nicht nur in Bezug auf Bequemlichkeit. Auch emotional soll die Verpackung den Kunden ansprechen – über möglichst viele Sinne. Den Geruchssinn sprechen Duftetiketten an. Letztes Jahr wurde eine sprechende Verpackung ausgezeichnet. <em>Nur der Geschmackssinn bleibt noch außer vor.</em>",
    "<strong>Abs.9:</strong> Ein System, das kürzlich vorgestellt wurde, besteht aus zwei Etiketten. Wenn man das äußere Etikett dreht, erscheint ein durchsichtiges Fenster. So wird die für Informationen verfügbare Fläche fast verdoppelt.",
    "<strong>Abs.10:</strong> Die Unternehmen müssen für anpassungsfähige Produktionsprozesse sorgen, damit sie im Rahmen von Sonderaktionen rasch kleine Mengen neuer Verpackungen liefern können."
  ],
  qs:[
    {n:13,t:"Konsumenten nehmen Verpackungen als gegeben hin.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.1: «Verbraucher erachten sie als selbstverständlich» = als gegeben hinnehmen.",
     textref:"«Verbraucher erachten sie als selbstverständlich und nehmen sie oft nicht einmal bewusst wahr.»",
     rule:"Paraphrase: <em>als selbstverständlich erachten</em> = воспринимать как само собой разумеющееся."},
    {n:14,t:"Der Umsatz der deutschen Verpackungsindustrie ist bei Papier- und Pappverpackungen am höchsten.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: Papier/Pappe = mengenmäßig 48% (größter Anteil MENGE), aber UMSATZSTÄRKSTE = Kunststoffverpackungen (41% des Umsatzes). Menge ≠ Umsatz!",
     textref:"«Mengenmäßig … Papier und Pappe mit 48% … Am umsatzstärksten sind allerdings Kunststoffverpackungen.»",
     rule:"WICHTIG: <em>mengenmäßig</em> ≠ <em>umsatzmäßig</em>. Количество ≠ выручка. Типичная ловушка!"},
    {n:15,t:"Die Konkurrenz aus Niedriglohnländern bescherte der Verpackungsindustrie milliardenschwere Einbußen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: Konkurrenz <em>droht</em> (Gefahr, nicht Tatsache). Von tatsächlichen Einbußen steht nichts.",
     textref:"«Sonst drohen hohe Verluste.» — drohen = только угроза, ещё не случилось.",
     rule:"<em>drohen</em> = угрожать ≠ eingetreten sein (уже произошло). Модальность важна!"},
    {n:16,t:"Verpackungen dienen ursprünglich dem Schutz vor Verschmutzung.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «An erster Stelle ist die Transportmöglichkeit zu nennen. Unmittelbar damit verbunden ist der Schutz … vor Verschmutzung.» = ursprüngliche Funktion.",
     textref:"«An erster Stelle … Schutz vor Verschmutzung, vor Beschädigung …»",
     rule:"<em>ursprünglich</em> = изначально. Abs.3 beschreibt primäre Aufgaben = ursprüngliche Funktionen."},
    {n:17,t:"Verbraucherverbände warnen vor Mineralöl in Verpackungen.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Mineralöle werden erwähnt (Abs.4), aber von <em>Verbraucherverbänden</em> steht nichts.",
     textref:"Abs.4 erwähnt Mineralöle, aber kein Wort über Verbraucherverbände.",
     rule:"x = Thema existiert (Mineralöle), aber DIESER Aspekt (Verbände) kommt nicht vor."},
    {n:18,t:"Die Verpackungsindustrie muss in Zukunft die Forschung in den Mittelpunkt stellen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «bioabbaubare Materialien und Optimierung der Herstellungsprozesse» müssen in den Mittelpunkt – nicht «die Forschung» allgemein.",
     textref:"«biologisch abbaubare Materialien … müssen in den Mittelpunkt der Forschungen gestellt werden.»",
     rule:"Aussage verallgemeinert. Text nennt spezifische Aspekte; Aussage sagt «Forschung» allgemein."},
    {n:19,t:"Immer mehr Forscher versuchen als Alternative zu Plastik Bio-Kunststoffe zu entwickeln.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Bio-Kunststoffe als solche werden nicht erwähnt.",
     textref:"Abs.6 erwähnt dünnere Folien und nachwachsende Rohstoffe, aber keine Bio-Kunststoffe.",
     rule:"x = dieses spezifische Thema (Bio-Kunststoffe) kommt im Text nicht vor."},
    {n:20,t:"Innovative Lebensmittelverpackungen werden die Angabe des Mindesthaltbarkeitsdatums überflüssig machen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.7 (kursiv): Folien zeigen Frische «weit genauer als das bisherige Mindesthaltbarkeitsdatum» → impliziert, MHD wird überflüssig.",
     textref:"«Folien, die anzeigen … weit genauer als das bisherige Mindesthaltbarkeitsdatum.» (kursiv hervorgehoben!)",
     rule:"Logische Schlussfolgerung: genauere Anzeige → MHD wird überflüssig. Kursiv-Text im Original lesen!"},
    {n:21,t:"Um attraktiv zu sein, sprechen Verpackungen schon heute alle fünf Sinne an.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.8 (kursiv): «Nur der Geschmackssinn bleibt noch außer vor.» = Geschmackssinn wird NICHT angesprochen.",
     textref:"«Nur der Geschmackssinn bleibt noch außer vor.» (kursiv im Text!)",
     rule:"<em>außer vor bleiben</em> = оставаться исключением. Не все 5 чувств!"},
    {n:22,t:"Verbraucherinformationen brauchen in Zukunft fast doppelt so viel Platz auf der Verpackung.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.9: verfügbare Fläche wird fast verdoppelt — aber nicht weil Infos mehr Platz brauchen, sondern weil Technik mehr Platz bietet.",
     textref:"«So wird die für Informationen verfügbare Fläche fast verdoppelt.»",
     rule:"Kausalität umgekehrt: mehr verfügbare Fläche ≠ mehr Platz benötigt."},
    {n:23,t:"Die Unternehmen müssen ihre Produktion besser an den kurzfristigen Bedarf anpassen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.10: «damit sie … rasch kleine Mengen … liefern können» = kurzfristiger Bedarf.",
     textref:"«damit sie im Rahmen von Sonderaktionen rasch kleine Mengen neuer Verpackungen liefern können.»",
     rule:"Paraphrase: <em>rasch kleine Mengen liefern</em> = auf kurzfristigen Bedarf reagieren."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Sprechende Tüten und duftende Kartons","b) Nachhaltige Verpackungen auf dem Vormarsch","c) Zukunftsperspektiven für die Verpackungsindustrie"],
     ans:"c) Zukunftsperspektiven für die Verpackungsindustrie",
     exp:"c) deckt ALLE Themen ab: Wirtschaft, Schutzfunktion, Hygiene, Nachhaltigkeit, Innovation, Sinne, Information, Flexibilität. a) = zu eng, b) = zu eng.",
     textref:"Gesamter Text behandelt: Wirtschaft + Schutz + Hygiene + Nachhaltigkeit + Sinnesansprache + Flexibilität.",
     rule:"Makroaufgabe: Überschrift muss den GESAMTEN Text abdecken, nicht nur einen Teilaspekt!"}
  ],
  vocab:["erachten als — считать, расценивать","recycelbar — пригодный для переработки","das Mindesthaltbarkeitsdatum — срок годности","außer vor bleiben — оставаться исключением","anpassungsfähig — способный к адаптации","die Sonderaktion — акция, специальное предложение"]
};
