// test-lv3d.js — TELC C1
window.TELC_TEST = {
  id:"lv3_4", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Die Spielzeugindustrie im Wandel",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Puppen, Bauklötze, Brettspiele — das klassische Spielzeug hat Generationen von Kindern begleitet. Doch die Spielzeugindustrie steht vor einem tiefgreifenden Wandel. Digitale Spiele und Smartphones drängen traditionelles Spielzeug zunehmend in den Hintergrund. Die Branche muss sich anpassen, um relevant zu bleiben.",
    "<strong>Abs.2:</strong> Dabei ist der Markt für Spielzeug nach wie vor groß. In Deutschland gaben Verbraucher im vergangenen Jahr rund 3,8 Milliarden Euro für Spielzeug aus — ein Rekordwert. Allerdings verschiebt sich die Nachfrage: Klassisches Spielzeug verliert Marktanteile, während interaktive und digitale Produkte boomen.",
    "<strong>Abs.3:</strong> Experten sehen in der Digitalisierung nicht nur eine Bedrohung, sondern auch eine Chance. Hybride Produkte, die analoge und digitale Elemente verbinden, erfreuen sich wachsender Beliebtheit. Ein Beispiel sind Lernroboter, die Kinder spielerisch ans Programmieren heranführen.",
    "<strong>Abs.4:</strong> Ein wichtiges Thema in der Branche ist Nachhaltigkeit. Immer mehr Eltern achten beim Kauf auf umweltfreundliche Materialien und faire Produktionsbedingungen. Spielzeug aus Holz oder recyceltem Kunststoff liegt im Trend. Einige Hersteller bieten zudem Reparaturservices an, um die Lebensdauer ihrer Produkte zu verlängern.",
    "<strong>Abs.5:</strong> Eine besondere Herausforderung stellt das Thema Sicherheit dar. Spielzeug muss in der EU strenge Normen erfüllen. Dennoch werden jährlich zahlreiche Produkte wegen Sicherheitsmängeln aus dem Verkehr gezogen, darunter viele Importe aus Fernost. Eltern werden zunehmend für das Thema sensibilisiert.",
    "<strong>Abs.6:</strong> Die Corona-Pandemie hat dem Spielzeugmarkt überraschenderweise einen Boom beschert. Da Familien mehr Zeit zu Hause verbrachten, stieg die Nachfrage nach Gesellschaftsspielen und Kreativspielzeug sprunghaft an. Experten bezweifeln jedoch, ob dieser Trend nachhaltig ist."
  ],
  qs:[
    {n:13,t:"Klassisches Spielzeug verliert zunehmend an Bedeutung.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.2: «Klassisches Spielzeug verliert Marktanteile» — direkte Aussage.",
     textref:"«Klassisches Spielzeug verliert Marktanteile, während interaktive und digitale Produkte boomen.»",
     rule:"Direkte Aussage im Text. Paraphrase: Marktanteile verlieren = an Bedeutung verlieren."},
    {n:14,t:"Der Gesamtumsatz der deutschen Spielzeugbranche ist im vergangenen Jahr gesunken.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.2: «rund 3,8 Milliarden Euro … — ein Rekordwert.» = Gegenteil, Rekordhoch!",
     textref:"«gaben Verbraucher im vergangenen Jahr rund 3,8 Milliarden Euro für Spielzeug aus — ein Rekordwert.»",
     rule:"<em>ein Rekordwert</em> = рекордный показатель = gestiegen, nicht gesunken."},
    {n:15,t:"Hybride Spielzeugprodukte kombinieren digitale und traditionelle Elemente.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «Hybride Produkte, die analoge und digitale Elemente verbinden.» — direkte Definition.",
     textref:"«Hybride Produkte, die analoge und digitale Elemente verbinden, erfreuen sich wachsender Beliebtheit.»",
     rule:"Paraphrase: analoge + digitale = traditionelle + digitale Elemente."},
    {n:16,t:"Viele Eltern legen beim Spielzeugkauf Wert auf Umweltaspekte.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «Immer mehr Eltern achten beim Kauf auf umweltfreundliche Materialien.»",
     textref:"«Immer mehr Eltern achten beim Kauf auf umweltfreundliche Materialien und faire Produktionsbedingungen.»",
     rule:"Paraphrase: auf Umweltaspekte achten = auf umweltfreundliche Materialien achten."},
    {n:17,t:"Alle in Deutschland verkauften Spielzeugprodukte erfüllen EU-Sicherheitsnormen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «werden jährlich zahlreiche Produkte wegen Sicherheitsmängeln aus dem Verkehr gezogen» = nicht alle sind sicher.",
     textref:"«Dennoch werden jährlich zahlreiche Produkte wegen Sicherheitsmängeln aus dem Verkehr gezogen.»",
     rule:"<em>dennoch</em> = тем не менее → Einschränkung. Nicht alle erfüllen die Normen!"},
    {n:18,t:"Spielzeugimporte aus Asien sind in Deutschland verboten.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.5 erwähnt Sicherheitsmängel bei Importen, aber ein Verbot kommt nicht vor.",
     textref:"«darunter viele Importe aus Fernost» — Sicherheitsmängel, aber kein Verbot erwähnt.",
     rule:"x = Verbot von Importen wird im Text nicht erwähnt."},
    {n:19,t:"Spielzeug aus recycelten Materialien ist derzeit besonders gefragt.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «Spielzeug aus Holz oder recyceltem Kunststoff liegt im Trend.»",
     textref:"«Spielzeug aus Holz oder recyceltem Kunststoff liegt im Trend.»",
     rule:"<em>liegt im Trend</em> = derzeit besonders gefragt = популярно в данный момент."},
    {n:20,t:"Die Pandemie hat die Nachfrage nach bestimmten Spielzeugkategorien erhöht.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.6: «stieg die Nachfrage nach Gesellschaftsspielen und Kreativspielzeug sprunghaft an.»",
     textref:"«stieg die Nachfrage nach Gesellschaftsspielen und Kreativspielzeug sprunghaft an.»",
     rule:"Direkte Aussage. Bestimmte Kategorien = Gesellschaftsspiele + Kreativspielzeug."},
    {n:21,t:"Lernroboter sind ein Beispiel für die Verbindung von Spielen und Bildung.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «Lernroboter, die Kinder spielerisch ans Programmieren heranführen.» = spielerisch lernen.",
     textref:"«Lernroboter, die Kinder spielerisch ans Programmieren heranführen.»",
     rule:"<em>spielerisch heranführen</em> = spielerisch lernen = Verbindung von Spielen und Bildung."},
    {n:22,t:"Experten sind sicher, dass der Pandemieboom im Spielzeugmarkt langfristig anhält.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.6: «Experten bezweifeln jedoch, ob dieser Trend nachhaltig ist.» = Gegenteil!",
     textref:"«Experten bezweifeln jedoch, ob dieser Trend nachhaltig ist.»",
     rule:"<em>bezweifeln</em> = сомневаться ≠ sicher sein. Direkter Widerspruch."},
    {n:23,t:"Einige Spielzeughersteller ermöglichen die Reparatur ihrer Produkte.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «Einige Hersteller bieten zudem Reparaturservices an.»",
     textref:"«Einige Hersteller bieten zudem Reparaturservices an, um die Lebensdauer ihrer Produkte zu verlängern.»",
     rule:"Direkte Aussage. Paraphrase: Reparaturservice anbieten = Reparatur ermöglichen."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Digitales Spielzeug verdrängt alle traditionellen Produkte","b) Boom und Wandel: Die Spielzeugindustrie zwischen Tradition und Digitalisierung","c) Sicherheitsmängel: Die größte Herausforderung der Spielzeugbranche"],
     ans:"b) Boom und Wandel: Die Spielzeugindustrie zwischen Tradition und Digitalisierung",
     exp:"b) deckt alle Themen ab: Wandel, Rekordumsatz (Boom), Nachhaltigkeit, Sicherheit, Hybrid-Produkte, Pandemie. a) und c) = zu eng.",
     textref:"Gesamter Text: Umsatzrekord + Digitalisierung + Nachhaltigkeit + Sicherheit + Pandemie.",
     rule:"Makroaufgabe: Überschrift mit <em>und</em> = Kontrast zwischen zwei Aspekten, die den ganzen Text abdecken."}
  ],
  vocab:["tiefgreifend — глубокий, коренной","hybrid — гибридный","spielerisch — игровым путём, в игровой форме","aus dem Verkehr ziehen — изымать из оборота","sensibilisieren — повышать осведомлённость","sprunghaft — резко, скачкообразно","bezweifeln — сомневаться"]
};
