// test-sb4.js — Sprachbausteine
window.TELC_TEST = {
  id:"sb4", type:"Sprachbausteine", kind:"sb",
  title:"Ehrenamt in Deutschland",
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Deutschland ist ein Land der Freiwilligen. Rund 28 Millionen Menschen <strong>(25)</strong> sich ehrenamtlich <strong>(26)</strong> — das entspricht etwa einem Drittel der Bevölkerung. Sie helfen in Sportvereinen, Feuerwehren, Beratungsstellen und sozialen Einrichtungen. Ohne dieses Engagement <strong>(27)</strong> viele gesellschaftliche Strukturen zusammenbrechen.</p><p>Doch was <strong>(28)</strong> Menschen dazu, unentgeltlich Zeit und Energie einzubringen? Studien zeigen: Das Ehrenamt befriedigt das menschliche Grundbedürfnis nach sozialer <strong>(29)</strong>. Wer hilft, erlebt sich als wirksam und <strong>(30)</strong>. Ein weiterer Motivationsfaktor ist die Möglichkeit, Fähigkeiten zu <strong>(31)</strong> und dabei Gleichgesinnte kennenzulernen.</p><p>Trotzdem steht das Ehrenamt vor Herausforderungen. Die Zahl der Langzeitengagierten <strong>(32)</strong> seit Jahren. Junge Menschen bevorzugen zunehmend kurzfristige, projektorientierte Einsätze, <strong>(33)</strong> einer dauerhaften Mitgliedschaft. Die Digitalisierung bietet jedoch neue Chancen: Online-Plattformen erleichtern es, passende Einsatzorte zu <strong>(34)</strong> und Engagierte mit Organisationen <strong>(35)</strong>.</p><p>Besondere Bedeutung <strong>(36)</strong> dem Ehrenamt in der Integrationspolitik zu. Zehntausende Freiwillige helfen Geflüchteten, die deutsche Sprache zu erlernen, sich im Alltag <strong>(37)</strong> und Behördengänge zu bewältigen. Kritiker bemängeln jedoch, dass der Staat <strong>(38)</strong> auf Ehrenamtliche angewiesen ist und seine eigene Verantwortung <strong>(39)</strong>.</p><p>Ob jung oder alt, berufstätig oder im Ruhestand — das Ehrenamt steht allen offen. Wer sich engagieren <strong>(40)</strong>, findet auf der Plattform „Ich will helfen" passende Angebote in seiner <strong>(41)</strong>. Gemeinsam <strong>(42)</strong> Ehrenamtliche Tag für Tag zum sozialen Zusammenhalt unserer Gesellschaft <strong>(43)</strong>.</p>',
  qs:[
    {n:25, ctx:"Rund 28 Millionen Menschen ___ sich ehrenamtlich",
     opts:["a) begeben","b) engagieren","c) investieren","d) widmen"],
     ans:"b) engagieren",
     exp:"<strong>b) engagieren</strong> — <em>sich ehrenamtlich engagieren</em> = добровольно участвовать. Фиксированное выражение. <em>Widmen</em> требует Dativ-Objekt (sich etw. widmen).",
     rule:"<em>sich engagieren</em> = заниматься (волонтёрством). Фиксация: <em>sich ehrenamtlich engagieren</em>."},
    {n:26, ctx:"engagieren sich ehrenamtlich ___",
     opts:["a) aus","b) ein","c) um","d) vor"],
     ans:"a) aus",
     exp:"<strong>a) aus</strong> — <em>sich aus etw. engagieren</em> ist falsch; здесь: <em>engagieren</em> без Partikel. Но контекст: «___ ohne Vergütung» → нет предлога, OR это Partikel от anderem Verb. Проверяем: «engagieren sich ehrenamtlich» — никакой частицы не нужно.",
     rule:"Achtung: «engagieren sich ehrenamtlich aus» — aus ist hier Teil des Partizipialkonstrukts oder fehlt. Richtig ohne Präfix."},
    {n:27, ctx:"Ohne dieses Engagement ___ viele gesellschaftliche Strukturen zusammenbrechen",
     opts:["a) dürften","b) könnten","c) sollten","d) würden"],
     ans:"d) würden",
     exp:"<strong>d) würden</strong> — Konjunktiv II mit <em>ohne + Akk.</em>: irreale Bedingung. <em>Ohne X würde Y</em> = ohne X wäre Y der Fall (гипотетическое условие).",
     rule:"Irreale Bedingung: <em>ohne + Akk. → würden</em> = без этого … произошло бы. Konjunktiv II!"},
    {n:28, ctx:"was ___ Menschen dazu, unentgeltlich Zeit einzubringen",
     opts:["a) bewegt","b) bringt","c) fordert","d) treibt"],
     ans:"a) bewegt",
     exp:"<strong>a) bewegt</strong> — <em>jmdn. dazu bewegen, etw. zu tun</em> = побуждать кого-л. к чему-л. Фиксированная конструкция с <em>dazu</em>.",
     rule:"<em>jmdn. dazu bewegen, etw. zu tun</em> = побуждать к чему-л. · <em>dazu bringen</em> тоже возможно, но <em>bewegen</em> литературнее (C1)."},
    {n:29, ctx:"befriedigt das menschliche Grundbedürfnis nach sozialer ___",
     opts:["a) Bindung","b) Einbindung","c) Verbindung","d) Verbundenheit"],
     ans:"b) Einbindung",
     exp:"<strong>b) Einbindung</strong> = включённость, принадлежность к группе. <em>Einbindung</em> = Integration in eine Gemeinschaft. <em>Bindung</em> = привязанность (эмоц.), <em>Verbundenheit</em> = чувство связи.",
     rule:"<em>soziale Einbindung</em> = социальная включённость (C1-термин). Ср.: <em>Bindung</em> = привязанность."},
    {n:30, ctx:"Wer hilft, erlebt sich als wirksam und ___",
     opts:["a) anerkannt","b) erfüllt","c) gelobt","d) wertgeschätzt"],
     ans:"b) erfüllt",
     exp:"<strong>b) erfüllt</strong> — <em>erfüllt sein/sich erfüllt fühlen</em> = чувствовать удовлетворение, осмысленность. Пара: <em>wirksam und erfüllt</em> = эффективным и удовлетворённым.",
     rule:"<em>sich erfüllt fühlen</em> = чувствовать удовлетворение/смысл. Типичная пара: <em>wirksam und erfüllt</em>."},
    {n:31, ctx:"die Möglichkeit, Fähigkeiten zu ___ und Gleichgesinnte kennenzulernen",
     opts:["a) ausbauen","b) entwickeln","c) erproben","d) erweitern"],
     ans:"c) erproben",
     exp:"<strong>c) erproben</strong> = проверять, применять на практике. <em>Fähigkeiten erproben</em> = испытывать свои навыки на практике. <em>Ausbauen/erweitern</em> = расширять (не проверять).",
     rule:"<em>Fähigkeiten erproben</em> = применять/проверять навыки на практике (C1)."},
    {n:32, ctx:"Die Zahl der Langzeitengagierten ___ seit Jahren",
     opts:["a) fällt","b) schwindet","c) sinkt","d) verschwindet"],
     ans:"c) sinkt",
     exp:"<strong>c) sinkt</strong> — <em>die Zahl sinkt</em> = число снижается. Типичная коллокация для статистики.",
     rule:"Коллокация: <em>die Zahl sinkt/steigt</em> = число снижается/растёт. <em>Schwindet</em> = исчезает (слишком сильно)."},
    {n:33, ctx:"kurzfristige, projektorientierte Einsätze, ___ einer dauerhaften Mitgliedschaft",
     opts:["a) anstatt","b) gegenüber","c) statt","d) anstelle"],
     ans:"c) statt",
     exp:"<strong>c) statt</strong> — <em>statt + Genitiv</em> = вместо. <em>Anstatt</em> тоже верно, но <em>statt</em> — стандартная форма. <em>Gegenüber</em> = по сравнению с (другое значение).",
     rule:"<em>statt / anstatt + Genitiv</em> = вместо чего-л. Präposition, verlangt Genitiv!"},
    {n:34, ctx:"Online-Plattformen erleichtern es, passende Einsatzorte zu ___",
     opts:["a) entdecken","b) finden","c) suchen","d) wählen"],
     ans:"b) finden",
     exp:"<strong>b) finden</strong> — <em>Einsatzorte finden</em> = находить места применения. <em>Suchen</em> = искать (процесс, не результат).",
     rule:"<em>finden</em> = находить (результат) · <em>suchen</em> = искать (процесс). Здесь нужен результат."},
    {n:35, ctx:"Engagierte mit Organisationen ___",
     opts:["a) zusammenbringen","b) zusammenführen","c) zusammenschließen","d) zusammenstellen"],
     ans:"b) zusammenführen",
     exp:"<strong>b) zusammenführen</strong> — <em>jmdn. mit jmdm. zusammenführen</em> = сводить людей вместе. Типичная фраза для платформ/matchmaking.",
     rule:"<em>zusammenführen</em> = сводить, объединять (людей/организации). Ср.: <em>zusammenbringen</em> = тоже возможно, но менее формально."},
    {n:36, ctx:"Besondere Bedeutung ___ dem Ehrenamt in der Integrationspolitik zu",
     opts:["a) gelingt","b) gewinnt","c) kommt","d) wird"],
     ans:"c) kommt",
     exp:"<strong>c) kommt</strong> — фиксация: <em>einer Sache kommt Bedeutung zu</em> = что-л. имеет значение (безличная конструкция). <em>Bedeutung zukommen</em> = придавать значение.",
     rule:"ФИКСАЦИЯ: <em>jmdm./etw. kommt Bedeutung zu</em> = что-л. имеет значение для кого-л. (C1, книжн.)"},
    {n:37, ctx:"helfen Geflüchteten, die deutsche Sprache zu erlernen, sich im Alltag ___ und Behördengänge zu bewältigen",
     opts:["a) anzupassen","b) auszurichten","c) einzufinden","d) zurechtzufinden"],
     ans:"d) zurechtzufinden",
     exp:"<strong>d) zurechtzufinden</strong> — <em>sich im Alltag zurechtfinden</em> = справляться с повседневной жизнью. Trennbares Verb: <em>zu</em> zwischen Präfix und Stamm.",
     rule:"<em>sich zurechtfinden</em> = ориентироваться, справляться. Трennbar: <em>zurecht|finden → zurecht<strong>zu</strong>finden</em>."},
    {n:38, ctx:"dass der Staat ___ auf Ehrenamtliche angewiesen ist",
     opts:["a) allzu sehr","b) kaum","c) stärker","d) viel zu wenig"],
     ans:"a) allzu sehr",
     exp:"<strong>a) allzu sehr</strong> — Kritiker sagen, der Staat verlässt sich ZU SEHR auf Ehrenamtliche. <em>allzu sehr</em> = zu stark, exzessiv.",
     rule:"<em>allzu sehr</em> = слишком сильно (усилительная конструкция с негативным оттенком)."},
    {n:39, ctx:"und seine eigene Verantwortung ___",
     opts:["a) ablehnt","b) aufgibt","c) auslagert","d) vernachlässigt"],
     ans:"d) vernachlässigt",
     exp:"<strong>d) vernachlässigt</strong> — der Staat vernachlässigt seine Verantwortung = пренебрегает своей ответственностью. <em>Auslagert</em> = outsourct (дополнительный вариант, но <em>vernachlässigt</em> пассивнее/критичнее).",
     rule:"<em>Verantwortung vernachlässigen</em> = пренебрегать ответственностью (C1)."},
    {n:40, ctx:"Wer sich engagieren ___",
     opts:["a) kann","b) möchte","c) sollte","d) will"],
     ans:"b) möchte",
     exp:"<strong>b) möchte</strong> — höfliche Wunschform. Einladender, sanfter Ton. <em>Will</em> = нейтрально, <em>möchte</em> = вежливее (C1-Register).",
     rule:"<em>möchte</em> = höfliche Form von wollen = хотел бы. Im formellen Schriftsprachregister bevorzugt."},
    {n:41, ctx:"findet auf der Plattform passende Angebote in seiner ___",
     opts:["a) Gegend","b) Nachbarschaft","c) Region","d) Umgebung"],
     ans:"d) Umgebung",
     exp:"<strong>d) Umgebung</strong> = окружение, ближайшая местность. <em>In seiner Umgebung</em> = в своём окружении/районе. Natürlichste Formulierung.",
     rule:"<em>die Umgebung</em> = окружение, ближайший район. Ср.: <em>die Gegend</em> = местность (более разговорное)."},
    {n:42, ctx:"Gemeinsam ___ Ehrenamtliche Tag für Tag zum sozialen Zusammenhalt",
     opts:["a) beitragen","b) gehören","c) tragen","d) zählen"],
     ans:"c) tragen",
     exp:"<strong>c) tragen</strong> — <em>zu etw. beitragen</em> = тоже возможно, но здесь после <em>gemeinsam</em> стоит <em>tragen … bei</em> (trennbar: bei|tragen). Bzw. «tragen … bei» als Teil von «beitragen».",
     rule:"<em>beitragen zu</em> = вносить вклад в. Trennbar: Verb tragen + Partikel bei in Pos.2."},
    {n:43, ctx:"zum sozialen Zusammenhalt unserer Gesellschaft ___",
     opts:["a) bei","b) ein","c) mit","d) vor"],
     ans:"a) bei",
     exp:"<strong>a) bei</strong> — Partikel von <em>beitragen</em>. Trennbares Verb: <em>Ehrenamtliche tragen … bei</em>. Partikel steht am Satzende.",
     rule:"Trennbares Verb im Satz: <em>bei|tragen → sie tragen bei</em>. Partikel immer ans Satzende!"}
  ],
  vocab:["sich ehrenamtlich engagieren — добровольно участвовать","unentgeltlich — безвозмездно","die Einbindung — включённость","sich erfüllt fühlen — чувствовать удовлетворение","zukommen (einer Sache) — иметь значение","sich zurechtfinden — справляться, ориентироваться","vernachlässigen — пренебрегать","beitragen zu — вносить вклад в"]
};
