// test-sb6.js — Sprachbausteine
window.TELC_TEST = {
  id:"sb6", type:"Sprachbausteine", kind:"sb",
  title:"E-Learning an deutschen Hochschulen",
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Das digitale Lernen hat an deutschen Hochschulen in den letzten Jahren erheblich <strong>(25)</strong>. Orts- und zeitunabhängig Lehrveranstaltungen <strong>(26)</strong>, Aufgaben einreichen und mit Kommilitonen kommunizieren — was noch vor zehn Jahren futuristisch klang, ist heute für Millionen von Studierenden Alltag. Lernplattformen wie Moodle oder ILIAS <strong>(27)</strong> dabei als technische Basis.</p><p>Die Vorteile liegen <strong>(28)</strong>: Studierende können Lernmaterialien nach eigenem Tempo bearbeiten und Vorlesungsaufzeichnungen <strong>(29)</strong> beliebig oft ansehen. Berufstätige oder Eltern mit kleinen Kindern <strong>(30)</strong> dadurch die Möglichkeit, ein Studium zu absolvieren, das sonst kaum machbar wäre. Auch der ökologische <strong>(31)</strong> ist nicht zu vernachlässigen: Weniger Pendelwege bedeuten weniger CO₂-Emissionen.</p><p>Dennoch <strong>(32)</strong> E-Learning nicht ohne Kritik. Ein häufig <strong>(33)</strong> Kritikpunkt ist die fehlende soziale Interaktion. Direkter Kontakt zwischen Studierenden und Lehrenden <strong>(34)</strong> zu tieferem Verstehen und bleibt im digitalen Raum schwer zu <strong>(35)</strong>. Zudem <strong>(36)</strong> viele Studierende, sich ohne klare Tagesstruktur selbst zu motivieren.</p><p>Besonders <strong>(37)</strong> ist die ungleiche technische Ausstattung der Studierenden. Nicht alle <strong>(38)</strong> zu Hause über schnelles Internet oder einen eigenen Computer. Hochschulen <strong>(39)</strong> gegensteuern, indem sie Geräte verleihen und kostenlose WLAN-Zugänge <strong>(40)</strong>.</p><p>Experten sind sich <strong>(41)</strong>, dass die Zukunft nicht im reinen E-Learning liegt, sondern in hybriden Konzepten, die Präsenz- und Online-Phasen <strong>(42)</strong> verknüpfen. Diese sogenannten Blended-Learning-Modelle <strong>(43)</strong> es, die Vorteile beider Lernformen <strong>(44)</strong> zu nutzen. So bleibt der Hochschulcampus als sozialer Begegnungsraum <strong>(45)</strong>, wird aber durch digitale Angebote <strong>(46)</strong>.</p>',
  qs:[
    {n:25, ctx:"Das digitale Lernen hat in den letzten Jahren erheblich ___",
     opts:["a) ausgebaut","b) entwickelt","c) gewonnen","d) zugenommen"],
     ans:"d) zugenommen",
     exp:"<strong>d) zugenommen</strong> — <em>zunehmen</em> = расти, увеличиваться. Perfekt: <em>hat zugenommen</em>. Trennbar: zu|nehmen.",
     rule:"<em>zunehmen</em> = увеличиваться, расти (Perfekt: hat zugenommen). Trennbar!"},
    {n:26, ctx:"Orts- und zeitunabhängig Lehrveranstaltungen ___",
     opts:["a) besuchen","b) besuchen zu können","c) zu besuchen","d) zu besuchen können"],
     ans:"c) zu besuchen",
     exp:"<strong>c) zu besuchen</strong> — Infinitiv mit <em>zu</em> in einer Aufzählung. Parallelismus: «Lehrveranstaltungen zu besuchen, Aufgaben einzureichen und zu kommunizieren».",
     rule:"Infinitiv mit zu in Aufzählung: alle Infinitive müssen das gleiche Muster haben."},
    {n:27, ctx:"Lernplattformen wie Moodle oder ILIAS ___ dabei als technische Basis",
     opts:["a) dienen","b) funktionieren","c) gelten","d) wirken"],
     ans:"a) dienen",
     exp:"<strong>a) dienen</strong> — <em>als etw. dienen</em> = служить чем-л. Feste Konstruktion mit <em>als</em>.",
     rule:"<em>als etw. dienen</em> = служить чем-л. (фиксация: dienen + als + Nomen)."},
    {n:28, ctx:"Die Vorteile liegen ___",
     opts:["a) auf der Hand","b) nahe","c) offen","d) vor"],
     ans:"a) auf der Hand",
     exp:"<strong>a) auf der Hand</strong> — <em>auf der Hand liegen</em> = быть очевидным. Идиома C1.",
     rule:"ИДИОМА: <em>auf der Hand liegen</em> = быть очевидным, лежать на поверхности (C1)."},
    {n:29, ctx:"Vorlesungsaufzeichnungen ___ beliebig oft ansehen",
     opts:["a) dürfen","b) können","c) lassen sich","d) mögen"],
     ans:"c) lassen sich",
     exp:"<strong>c) lassen sich</strong> — <em>lassen sich + Infinitiv</em> = можно (пассивное значение). Ersatz für Passiv.",
     rule:"<em>lassen sich + Infinitiv</em> = можно сделать (= können + Passiv). C1-Konstruktion!"},
    {n:30, ctx:"Berufstätige oder Eltern ___ dadurch die Möglichkeit, ein Studium zu absolvieren",
     opts:["a) bekommen","b) erhalten","c) erwerben","d) kriegen"],
     ans:"b) erhalten",
     exp:"<strong>b) erhalten</strong> — <em>die Möglichkeit erhalten</em> = получить возможность. Формально (C1). <em>Bekommen/kriegen</em> = разговорнее.",
     rule:"<em>die Möglichkeit erhalten</em> = получить возможность (формальный стиль C1)."},
    {n:31, ctx:"Auch der ökologische ___ ist nicht zu vernachlässigen",
     opts:["a) Aspekt","b) Faktor","c) Nutzen","d) Vorteil"],
     ans:"c) Nutzen",
     exp:"<strong>c) Nutzen</strong> — <em>der ökologische Nutzen</em> = экологическая польза/выгода. Passt am besten zum Kontext (Emissionen).",
     rule:"<em>der Nutzen</em> = польза, выгода. Ср.: <em>der Vorteil</em> = преимущество (allgemeiner)."},
    {n:32, ctx:"Dennoch ___ E-Learning nicht ohne Kritik",
     opts:["a) bleibt","b) besteht","c) geht","d) kommt"],
     ans:"a) bleibt",
     exp:"<strong>a) bleibt</strong> — <em>nicht ohne Kritik bleiben</em> = не оставаться без критики. Фиксация.",
     rule:"<em>nicht ohne Kritik bleiben</em> = не оставаться без критики (фиксированная конструкция)."},
    {n:33, ctx:"Ein häufig ___ Kritikpunkt ist die fehlende soziale Interaktion",
     opts:["a) erwähnter","b) genannter","c) gesagter","d) vorgeworfener"],
     ans:"b) genannter",
     exp:"<strong>b) genannter</strong> — Partizip II von <em>nennen</em> als Adjektiv: <em>ein häufig genannter Kritikpunkt</em> = часто упоминаемый критический аспект.",
     rule:"Partizip II als Attribut: <em>häufig genannt</em> → <em>häufig genannter</em> (starke Dekl. ohne Artikel)."},
    {n:34, ctx:"Direkter Kontakt ___ zu tieferem Verstehen",
     opts:["a) beiträgt","b) beträgt","c) führt","d) trägt bei"],
     ans:"d) trägt bei",
     exp:"<strong>d) trägt bei</strong> — <em>zu etw. beitragen</em> (trennbar). Im Hauptsatz steht das Verb an Pos.2: <em>trägt</em> + Partikel <em>bei</em> am Ende.",
     rule:"Trennbares Verb im Hauptsatz: <em>trägt … bei</em>. Partikel IMMER ans Satzende!"},
    {n:35, ctx:"bleibt im digitalen Raum schwer zu ___",
     opts:["a) ersetzen","b) erzielen","c) imitieren","d) reproduzieren"],
     ans:"a) ersetzen",
     exp:"<strong>a) ersetzen</strong> — direkter Kontakt ist im Digitalen <em>schwer zu ersetzen</em> = трудно заменить. Пассивный инфинитив.",
     rule:"<em>schwer zu ersetzen</em> = трудно заменить. <em>schwer zu + Infinitiv</em> = трудно сделать."},
    {n:36, ctx:"Zudem ___ viele Studierende, sich ohne klare Tagesstruktur selbst zu motivieren",
     opts:["a) fällt es schwer","b) gelingt es nicht","c) kämpfen","d) schaffen es nicht"],
     ans:"a) fällt es schwer",
     exp:"<strong>a) fällt es schwer</strong> — <em>es fällt jmdm. schwer, etw. zu tun</em> = кому-л. трудно что-л. делать. Фиксация.",
     rule:"<em>Es fällt jmdm. schwer + zu-Infinitiv</em> = кому-л. трудно (что-л. делать). C1!"},
    {n:37, ctx:"Besonders ___ ist die ungleiche technische Ausstattung",
     opts:["a) auffällig","b) bezeichnend","c) problematisch","d) schwierig"],
     ans:"c) problematisch",
     exp:"<strong>c) problematisch</strong> — strukturelle C1-Formulierung: <em>Besonders problematisch ist …</em> = особенно проблематично.",
     rule:"Struktur: <em>Besonders + Adjektiv + ist</em>. <em>Problematisch</em> passt für sachliche Kritik (C1)."},
    {n:38, ctx:"Nicht alle ___ zu Hause über schnelles Internet oder einen eigenen Computer",
     opts:["a) besitzen","b) haben","c) verfügen","d) zeigen"],
     ans:"c) verfügen",
     exp:"<strong>c) verfügen</strong> — <em>über etw. verfügen</em> = располагать чем-л. Formeller als <em>haben</em>.",
     rule:"<em>über etw. verfügen</em> = располагать чем-л. (формально, C1)."},
    {n:39, ctx:"Hochschulen ___ gegensteuern, indem sie Geräte verleihen",
     opts:["a) dürfen","b) können","c) müssen","d) versuchen"],
     ans:"b) können",
     exp:"<strong>b) können</strong> — Hochschulen KÖNNEN gegensteuern = у них есть возможность/средства. Keine Pflicht, sondern Möglichkeit.",
     rule:"<em>können</em> = мочь (возможность). <em>müssen</em> = обязаны (другой оттенок)."},
    {n:40, ctx:"indem sie Geräte verleihen und kostenlose WLAN-Zugänge ___",
     opts:["a) anbieten","b) einrichten","c) ermöglichen","d) gewähren"],
     ans:"a) anbieten",
     exp:"<strong>a) anbieten</strong> — <em>WLAN-Zugänge anbieten</em> = предлагать доступ к Wi-Fi. Natürlichste Kollokation.",
     rule:"<em>etw. anbieten</em> = предлагать что-л. Kollokation: Zugänge / Angebote anbieten."},
    {n:41, ctx:"Experten sind sich ___, dass die Zukunft nicht im reinen E-Learning liegt",
     opts:["a) bewusst","b) einig","c) klar","d) sicher"],
     ans:"b) einig",
     exp:"<strong>b) einig</strong> — <em>sich einig sein</em> = быть единого мнения, соглашаться. Фиксация: <em>sich einig sein, dass</em>.",
     rule:"<em>sich einig sein</em> = быть единого мнения. Реф. Verb: sich!"},
    {n:42, ctx:"die Präsenz- und Online-Phasen ___ verknüpfen",
     opts:["a) clever","b) geschickt","c) klug","d) sinnvoll"],
     ans:"d) sinnvoll",
     exp:"<strong>d) sinnvoll</strong> — <em>sinnvoll verknüpfen</em> = разумно/осмысленно связывать. <em>Clever/klug</em> = умно (разговорнее).",
     rule:"<em>sinnvoll</em> = разумный, имеющий смысл (формальный регистр C1)."},
    {n:43, ctx:"Diese Blended-Learning-Modelle ___ es, die Vorteile beider Lernformen zu nutzen",
     opts:["a) bieten","b) erlauben","c) ermöglichen","d) gestatten"],
     ans:"c) ermöglichen",
     exp:"<strong>c) ermöglichen</strong> — <em>etw. ermöglichen</em> = делать возможным, позволять. Формальная альтернатива к <em>erlauben</em>.",
     rule:"<em>ermöglichen</em> = делать возможным (формально, C1). Ср.: <em>erlauben</em> = разрешать (другой оттенок)."},
    {n:44, ctx:"die Vorteile beider Lernformen ___ zu nutzen",
     opts:["a) effektiv","b) kombiniert","c) optimal","d) verbunden"],
     ans:"c) optimal",
     exp:"<strong>c) optimal</strong> — <em>optimal nutzen</em> = использовать оптимально. Стандартная коллокация для академических текстов.",
     rule:"<em>optimal nutzen</em> = использовать оптимально (C1-коллокация)."},
    {n:45, ctx:"So bleibt der Hochschulcampus als sozialer Begegnungsraum ___",
     opts:["a) bestehen","b) erhalten","c) erhalten bleiben","d) vorhanden"],
     ans:"c) erhalten bleiben",
     exp:"<strong>c) erhalten bleiben</strong> — <em>erhalten bleiben</em> = сохраняться. Фиксированное выражение: кампус остаётся/сохраняется как место встреч.",
     rule:"<em>erhalten bleiben</em> = сохраняться, оставаться (фиксация C1)."},
    {n:46, ctx:"wird aber durch digitale Angebote ___",
     opts:["a) ausgebaut","b) bereichert","c) ergänzt","d) erweitert"],
     ans:"c) ergänzt",
     exp:"<strong>c) ergänzt</strong> — <em>durch etw. ergänzt werden</em> = дополняться чем-л. Präziserer Ausdruck für «hinzugefügt».",
     rule:"<em>ergänzen</em> = дополнять (не заменять, а добавлять). Ср.: <em>erweitern</em> = расширять."}
  ],
  vocab:["zunehmen — возрастать, увеличиваться","auf der Hand liegen — быть очевидным","lassen sich + Inf. — можно (сделать)","beitragen zu — вносить вклад в","es fällt jmdm. schwer — кому-л. трудно","sich einig sein — быть единого мнения","ermöglichen — делать возможным","erhalten bleiben — сохраняться","ergänzen — дополнять"]
};
