// test-sb7.js — Sprachbausteine
window.TELC_TEST = {
  id:"sb7", type:"Sprachbausteine", kind:"sb",
  title:"Schlaftypen: Eulen und Lerchen",
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Sind Sie eher ein Morgenmensch oder ein Nachtmensch? Diese Frage klingt nach einer Frage des Charakters, ist aber in Wirklichkeit eine Frage der Biologie. Wissenschaftler <strong>(25)</strong> zwischen zwei grundlegenden Schlaftypen: den sogenannten Lerchen — Menschen, die früh <strong>(26)</strong> und voller Energie in den Tag starten — und den Eulen, die erst spät in der Nacht richtig <strong>(27)</strong> kommen.</p><p>Der entscheidende Faktor ist die innere Uhr, auch <strong>(28)</strong> als zirkadianer Rhythmus. Dieser biologische Mechanismus <strong>(29)</strong> nahezu alle Körperfunktionen: Schlaf-Wach-Phasen, Körpertemperatur, Hormonausschüttung. Er <strong>(30)</strong> sich nach einem 24-Stunden-Takt und ist <strong>(31)</strong> genetisch bedingt. Wer also eine Eule ist, kann das kaum <strong>(32)</strong> — es liegt in den Genen.</p><p>Dennoch <strong>(33)</strong> die Gesellschaft nach wie vor die Lerchen. Schulen beginnen früh, Berufsleben <strong>(34)</strong> Pünktlichkeit am Morgen, und wer bis mittags schläft, gilt schnell als faul oder undiszipliniert. Diese Vorurteile <strong>(35)</strong> den Eulen das Leben schwer — obwohl sie biologisch gesehen <strong>(36)</strong> anders ticken.</p><p>Dabei wäre eine Anpassung des Systems möglich und sinnvoll. Studien zeigen, dass Schüler, <strong>(37)</strong> Schulbeginn um eine Stunde nach hinten <strong>(38)</strong> wurde, deutlich bessere Leistungen erzielten. Auch im Berufsleben gibt es erste Versuche mit flexiblen <strong>(39)</strong>: Mitarbeiter können zwischen verschiedenen Arbeitszeitmodellen <strong>(40)</strong>.</p><p>Für Eulen <strong>(41)</strong> es sich dennoch, bestimmte Strategien anzuwenden. Morgenlicht hilft, die innere Uhr <strong>(42)</strong> zu verschieben. Koffein sollte nach dem frühen Nachmittag <strong>(43)</strong> werden, da es den Schlaf <strong>(44)</strong>. Und <strong>(45)</strong> allem ist ein regelmäßiger Schlafrhythmus wichtig — auch <strong>(46)</strong> dem Wochenende.</p>',
  qs:[
    {n:25, ctx:"Wissenschaftler ___ zwischen zwei grundlegenden Schlaftypen",
     opts:["a) differenzieren","b) teilen","c) trennen","d) unterscheiden"],
     ans:"d) unterscheiden",
     exp:"<strong>d) unterscheiden</strong> — <em>zwischen etw. unterscheiden</em> = различать, проводить различие между. Фиксация с предлогом <em>zwischen</em>.",
     rule:"<em>zwischen etw. unterscheiden</em> = различать между чем-л. Фиксация: zwischen + Dativ."},
    {n:26, ctx:"Menschen, die früh ___ und voller Energie in den Tag starten",
     opts:["a) aufstehen","b) aufwachen","c) aufwecken","d) erwachen"],
     ans:"b) aufwachen",
     exp:"<strong>b) aufwachen</strong> = просыпаться (без помощи). <em>Aufstehen</em> = вставать (физическое действие). <em>Aufwecken</em> = будить кого-то (переходный глагол).",
     rule:"<em>aufwachen</em> = просыпаться (сам) · <em>aufwecken</em> = будить кого-то. Intransitiv vs. transitiv!"},
    {n:27, ctx:"Eulen, die erst spät in der Nacht richtig ___ kommen",
     opts:["a) an","b) auf","c) in Fahrt","d) in Schwung"],
     ans:"d) in Schwung",
     exp:"<strong>d) in Schwung</strong> — <em>in Schwung kommen</em> = разойтись, набрать обороты. Идиома C1.",
     rule:"ИДИОМА: <em>in Schwung kommen</em> = набирать обороты, раскачиваться. Ср.: <em>in Gang kommen</em>."},
    {n:28, ctx:"auch ___ als zirkadianer Rhythmus",
     opts:["a) bekannt","b) bezeichnet","c) genannt","d) tituliert"],
     ans:"a) bekannt",
     exp:"<strong>a) bekannt</strong> — <em>auch bekannt als</em> = также известный как. Фиксация для синонимов/альтернативных названий.",
     rule:"<em>auch bekannt als</em> = также известный как (= auch genannt). Стандартная вставная конструкция."},
    {n:29, ctx:"Dieser biologische Mechanismus ___ nahezu alle Körperfunktionen",
     opts:["a) betrifft","b) kontrolliert","c) regelt","d) steuert"],
     ans:"c) regelt",
     exp:"<strong>c) regelt</strong> — <em>Körperfunktionen regeln</em> = регулировать функции организма. Стандартный медицинский термин.",
     rule:"<em>etw. regeln</em> = регулировать, управлять (биологические процессы). Коллокация: Funktionen/Prozesse regeln."},
    {n:30, ctx:"Er ___ sich nach einem 24-Stunden-Takt",
     opts:["a) läuft","b) orientiert","c) richtet","d) wiederholt"],
     ans:"c) richtet",
     exp:"<strong>c) richtet</strong> — <em>sich nach etw. richten</em> = ориентироваться на что-л., подстраиваться под. Рефлексивная фиксация.",
     rule:"<em>sich nach etw. richten</em> = ориентироваться на что-л. Фиксация: nach + Dativ."},
    {n:31, ctx:"und ist ___ genetisch bedingt",
     opts:["a) außerdem","b) dazu","c) großteils","d) vorwiegend"],
     ans:"d) vorwiegend",
     exp:"<strong>d) vorwiegend</strong> = преимущественно, главным образом. Точнее <em>großteils</em>, но <em>vorwiegend</em> — книжнее (C1).",
     rule:"<em>vorwiegend</em> = преимущественно (C1). Ср.: <em>hauptsächlich</em> = hauptsächlich."},
    {n:32, ctx:"Wer also eine Eule ist, kann das kaum ___",
     opts:["a) abändern","b) beeinflussen","c) steuern","d) verändern"],
     ans:"b) beeinflussen",
     exp:"<strong>b) beeinflussen</strong> — <em>kaum beeinflussen</em> = едва можно повлиять. Стандартная коллокация для неизменяемых характеристик.",
     rule:"<em>etw. beeinflussen</em> = влиять на что-л. Коллокация: genetische Faktoren kaum beeinflussen."},
    {n:33, ctx:"Dennoch ___ die Gesellschaft nach wie vor die Lerchen",
     opts:["a) bevorzugt","b) fördert","c) liebt","d) unterstützt"],
     ans:"a) bevorzugt",
     exp:"<strong>a) bevorzugt</strong> — <em>die Gesellschaft bevorzugt Lerchen</em> = общество отдаёт предпочтение жаворонкам. Strukturell korrekt.",
     rule:"<em>bevorzugen</em> = отдавать предпочтение, предпочитать (C1). Формальнее чем <em>lieber mögen</em>."},
    {n:34, ctx:"Berufsleben ___ Pünktlichkeit am Morgen",
     opts:["a) braucht","b) erfordert","c) fordert","d) verlangt"],
     ans:"d) verlangt",
     exp:"<strong>d) verlangt</strong> — <em>etw. verlangt Pünktlichkeit</em> = требует пунктуальности. Stärker als <em>fordert</em>, passt für gesellschaftliche Normen.",
     rule:"<em>verlangen</em> = требовать (безличное требование системы). Ср.: <em>fordern</em> = требовать (активное лицо)."},
    {n:35, ctx:"Diese Vorurteile ___ den Eulen das Leben schwer",
     opts:["a) gestalten","b) machen","c) schaffen","d) stellen"],
     ans:"b) machen",
     exp:"<strong>b) machen</strong> — <em>jmdm. das Leben schwer machen</em> = осложнять кому-л. жизнь. Фиксация!",
     rule:"ФИКСАЦИЯ: <em>jmdm. das Leben schwer machen</em> = осложнять чью-л. жизнь (C1)."},
    {n:36, ctx:"obwohl sie biologisch gesehen ___ anders ticken",
     opts:["a) einfach","b) ganz","c) halt","d) nun mal"],
     ans:"d) nun mal",
     exp:"<strong>d) nun mal</strong> = просто так устроено, ничего не поделаешь (Modalpartikel). Ausdrückt unvermeidliche Tatsache.",
     rule:"<em>nun mal</em> = так уж устроено, ничего не поделаешь (Modalpartikel C1). Unveränderliche Tatsache."},
    {n:37, ctx:"Schüler, ___ Schulbeginn um eine Stunde nach hinten ___ wurde",
     opts:["a) bei denen","b) deren","c) denen","d) von denen"],
     ans:"b) deren",
     exp:"<strong>b) deren</strong> — Genitiv-Relativpronomen: <em>Schüler, deren Schulbeginn</em> = ученики, чьё начало уроков. Genitiv = Besitz/Zugehörigkeit.",
     rule:"<em>deren</em> = Genitiv Relativpronomen (чей/чья/чьё). Schüler → deren Schulbeginn = начало уроков этих учеников."},
    {n:38, ctx:"Schulbeginn um eine Stunde nach hinten ___ wurde",
     opts:["a) geschoben","b) gelegt","c) gesetzt","d) verlegt"],
     ans:"d) verlegt",
     exp:"<strong>d) verlegt</strong> — <em>etw. verlegen</em> = переносить (по времени). <em>Den Schulbeginn verlegen</em> = перенести начало занятий.",
     rule:"<em>etw. verlegen</em> = переносить (время/место). Коллокация: Termin/Beginn verlegen."},
    {n:39, ctx:"erste Versuche mit flexiblen ___",
     opts:["a) Arbeitsmodellen","b) Arbeitsplänen","c) Arbeitszeiten","d) Arbeitszeitmodellen"],
     ans:"d) Arbeitszeitmodellen",
     exp:"<strong>d) Arbeitszeitmodellen</strong> — <em>flexible Arbeitszeitmodelle</em> = гибкие модели рабочего времени. Стандартный термин.",
     rule:"<em>das Arbeitszeitmodell</em> = модель рабочего времени (HR-термин C1)."},
    {n:40, ctx:"Mitarbeiter können zwischen verschiedenen Arbeitszeitmodellen ___",
     opts:["a) auswählen","b) entscheiden","c) urteilen","d) wählen"],
     ans:"d) wählen",
     exp:"<strong>d) wählen</strong> — <em>zwischen etw. wählen</em> = выбирать из. Фиксация: zwischen + Dativ + wählen.",
     rule:"<em>zwischen etw. wählen</em> = выбирать из чего-л. Фиксация!"},
    {n:41, ctx:"Für Eulen ___ es sich dennoch, bestimmte Strategien anzuwenden",
     opts:["a) empfiehlt","b) lohnt","c) rät","d) zahlt"],
     ans:"b) lohnt",
     exp:"<strong>b) lohnt</strong> — <em>es lohnt sich, etw. zu tun</em> = стоит что-л. делать. Фиксация!",
     rule:"ФИКСАЦИЯ: <em>es lohnt sich + zu-Infinitiv</em> = стоит (делать что-л.). C1!"},
    {n:42, ctx:"Morgenlicht hilft, die innere Uhr ___ zu verschieben",
     opts:["a) etwas","b) geringfügig","c) kaum","d) leicht"],
     ans:"a) etwas",
     exp:"<strong>a) etwas</strong> — <em>etwas nach vorne verschieben</em> = немного сдвинуть. <em>Etwas</em> als Adverb = немного.",
     rule:"<em>etwas</em> als Adverb = немного, слегка. Ср.: <em>ein bisschen</em> = разговорнее."},
    {n:43, ctx:"Koffein sollte nach dem frühen Nachmittag ___ werden",
     opts:["a) abgelehnt","b) eingestellt","c) gemieden","d) vermieden"],
     ans:"d) vermieden",
     exp:"<strong>d) vermieden</strong> — <em>Koffein vermeiden</em> = избегать кофеина. Стандартная коллокация для рекомендаций.",
     rule:"<em>etw. vermeiden</em> = избегать чего-л. (рекомендация). Passiv: sollte vermieden werden."},
    {n:44, ctx:"da es den Schlaf ___",
     opts:["a) behindert","b) blockiert","c) hemmt","d) stört"],
     ans:"d) stört",
     exp:"<strong>d) stört</strong> — <em>den Schlaf stören</em> = мешать сну. Стандартная коллокация.",
     rule:"<em>den Schlaf stören</em> = нарушать/мешать сну. Коллокация: Schlaf stören."},
    {n:45, ctx:"Und ___ allem ist ein regelmäßiger Schlafrhythmus wichtig",
     opts:["a) bei","b) neben","c) vor","d) über"],
     ans:"c) vor",
     exp:"<strong>c) vor</strong> — <em>vor allem</em> = прежде всего, главным образом. Фиксация!",
     rule:"ФИКСАЦИЯ: <em>vor allem</em> = прежде всего, главным образом (C1)."},
    {n:46, ctx:"ein regelmäßiger Schlafrhythmus wichtig — auch ___ dem Wochenende",
     opts:["a) an","b) bei","c) in","d) zu"],
     ans:"a) an",
     exp:"<strong>a) an</strong> — <em>am Wochenende</em> (Dativ: an dem = am). Temporale Präposition für Wochentage und Wochenende.",
     rule:"<em>am Wochenende / an Weihnachten</em> — Präposition <em>an</em> für Wochentage/besondere Tage."}
  ],
  vocab:["die innere Uhr — внутренние часы","der zirkadiane Rhythmus — циркадный ритм","bevorzugen — отдавать предпочтение","jmdm. das Leben schwer machen — осложнять чью-л. жизнь","nun mal — так уж устроено","es lohnt sich — стоит (делать)","vermeiden — избегать","vor allem — прежде всего"]
};
