// test-lv3l.js — Leseverstehen Teil 3
window.TELC_TEST = {
  id:"lv3l", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Kleingärten — grüne Oasen in der Stadt",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Rund eine Million Kleingärten gibt es in Deutschland — aufgeteilt auf etwa 15.000 Vereine. Gemeinsam bilden sie das größte zusammenhängende Grünnetz in deutschen Städten. Was einst als Versorgungsgarten für ärmere Stadtbewohner begann, hat sich zu einem vielfältigen Freizeitphänomen entwickelt, das heute alle sozialen Schichten anspricht.",
    "<strong>Abs.2:</strong> Die Geschichte des Kleingartens reicht ins 19. Jahrhundert zurück. Der Leipziger Arzt Daniel Gottlob Moritz Schreber gilt als geistiger Vater der Bewegung — auch wenn er selbst nie einen Garten anlegte. Nach ihm wurden die bekanntesten deutschen Kleingärten benannt: die Schrebergärten. Ursprünglich sollten sie Kindern aus einkommensschwachen Familien Bewegung und Frischluft verschaffen.",
    "<strong>Abs.3:</strong> Heute hat der Kleingarten seinen sozialen Charakter weitgehend bewahrt, aber sein Gesicht verändert. Statt Kartoffeln und Kohl gedeihen immer häufiger Kräuter, Beeren und exotische Gemüsesorten. Die Nachfrage nach Kleingärten ist zuletzt stark gestiegen — besonders in Großstädten, wo die Wartelisten in manchen Vereinen mehrere Jahre betragen. Die Pandemie hat diesen Trend noch verstärkt.",
    "<strong>Abs.4:</strong> Die Kleingärten stehen jedoch auch unter Druck. Städtische Behörden sehen in den Grünflächen zunehmend Potenzial für Wohnungsbau — ein angesichts des Wohnungsmangels verständlicher Impuls. Naturschützer hingegen betonen die ökologische Bedeutung: Kleingärten sind Rückzugsorte für Insekten, Vögel und andere Kleintiere und tragen zur Kühlung überhitzter Stadtbezirke bei.",
    "<strong>Abs.5:</strong> Rechtlich sind Kleingärten durch das Bundeskleingartengesetz geschützt. Dieses schreibt vor, dass mindestens ein Drittel der Parzelle für den Anbau von Obst und Gemüse genutzt werden muss — ein Relikt aus den Zeiten, als Selbstversorgung wichtiger war als Erholung. Verstöße gegen diese Regel können zur Kündigung des Pachtvertrags führen.",
    "<strong>Abs.6:</strong> Der Kleingarten von morgen könnte sich stark von dem heutigen unterscheiden. Stadtplaner und Gartenexperten diskutieren Modelle, bei denen Kleingartenflächen als Gemeinschaftsgärten allen Stadtbewohnern offen stehen — nicht nur den Pächtern. Das würde die soziale Funktion der Gärten stärken und den gesellschaftlichen Zusammenhalt fördern."
  ],
  qs:[
    {n:13, t:"Die Kleingartenbewegung entstand ursprünglich, um Menschen mit niedrigem Einkommen zu helfen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.2: «Ursprünglich sollten sie Kindern aus einkommensschwachen Familien Bewegung und Frischluft verschaffen.»",
     textref:"«Ursprünglich sollten sie Kindern aus einkommensschwachen Familien Bewegung und Frischluft verschaffen.»",
     rule:"<em>ursprünglich</em> = изначально. Direkte Aussage über den ursprünglichen Zweck."},
    {n:14, t:"Daniel Gottlob Moritz Schreber legte den ersten Kleingarten in Deutschland an.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.2: «auch wenn er selbst nie einen Garten anlegte» — er legte keinen Garten an.",
     textref:"«auch wenn er selbst nie einen Garten anlegte.»",
     rule:"<em>auch wenn</em> = хотя. Direkter Widerspruch: er legte KEINEN Garten an."},
    {n:15, t:"Die Nachfrage nach Kleingärten ist in letzter Zeit gesunken.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: «Die Nachfrage nach Kleingärten ist zuletzt stark gestiegen.»",
     textref:"«Die Nachfrage nach Kleingärten ist zuletzt stark gestiegen.»",
     rule:"<em>gestiegen</em> ≠ gesunken. Direkter Widerspruch."},
    {n:16, t:"In manchen Städten müssen Interessenten jahrelang auf einen Kleingarten warten.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.3: «Wartelisten in manchen Vereinen betragen mehrere Jahre.»",
     textref:"«wo die Wartelisten in manchen Vereinen mehrere Jahre betragen.»",
     rule:"Direkte Paraphrase: Wartelisten = mehrere Jahre = jahrelang warten."},
    {n:17, t:"Kleingärten dürfen laut Gesetz ausschließlich zur Erholung genutzt werden.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.5: «mindestens ein Drittel … für den Anbau von Obst und Gemüse genutzt werden muss» — Anbau ist Pflicht.",
     textref:"«mindestens ein Drittel der Parzelle für den Anbau von Obst und Gemüse genutzt werden muss.»",
     rule:"Ausschließlich Erholung = falsch. Gesetz schreibt Anbau vor."},
    {n:18, t:"Kleingärten leisten einen Beitrag zur Abkühlung von Städten.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «tragen zur Kühlung überhitzter Stadtbezirke bei.»",
     textref:"«tragen zur Kühlung überhitzter Stadtbezirke bei.»",
     rule:"Direkte Paraphrase: Kühlung = Abkühlung. Direkte Aussage."},
    {n:19, t:"Das Bundeskleingartengesetz wurde nach der Pandemie eingeführt.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.5: Das Gesetz ist ein «Relikt aus den Zeiten, als Selbstversorgung wichtiger war» — also viel älter.",
     textref:"«ein Relikt aus den Zeiten, als Selbstversorgung wichtiger war als Erholung.»",
     rule:"<em>Relikt</em> = пережиток прошлого → sehr alt. Nach der Pandemie eingeführt = falsch."},
    {n:20, t:"Städtische Behörden möchten einige Kleingartenflächen für den Wohnungsbau nutzen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «Städtische Behörden sehen in den Grünflächen Potenzial für Wohnungsbau.»",
     textref:"«Städtische Behörden sehen in den Grünflächen zunehmend Potenzial für Wohnungsbau.»",
     rule:"Direkte Paraphrase: Potenzial für Wohnungsbau sehen = für Wohnungsbau nutzen wollen."},
    {n:21, t:"Zukünftige Gemeinschaftsgärten könnten allen Stadtbewohnern offenstehen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.6: «Kleingartenflächen als Gemeinschaftsgärten allen Stadtbewohnern offen stehen — nicht nur den Pächtern.»",
     textref:"«bei denen Kleingartenflächen als Gemeinschaftsgärten allen Stadtbewohnern offen stehen.»",
     rule:"Direkte Aussage im Text. Zukünftige Modelle werden diskutiert."},
    {n:22, t:"Wer die Anbauvorschrift im Kleingarten verletzt, riskiert den Verlust des Pachtrechts.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.5: «Verstöße gegen diese Regel können zur Kündigung des Pachtvertrags führen.»",
     textref:"«Verstöße gegen diese Regel können zur Kündigung des Pachtvertrags führen.»",
     rule:"Pachtvertrag kündigen = Verlust des Pachtrechts. Direkte Paraphrase."},
    {n:23, t:"In deutschen Kleingärten werden heute überwiegend dieselben Pflanzen angebaut wie vor 100 Jahren.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: «immer häufiger Kräuter, Beeren und exotische Gemüsesorten» statt früher Kartoffeln und Kohl.",
     textref:"«Statt Kartoffeln und Kohl gedeihen immer häufiger Kräuter, Beeren und exotische Gemüsesorten.»",
     rule:"<em>statt</em> = вместо. Andere Pflanzen als früher — Direkter Widerspruch."},
    {n:24, t:"Welche Überschrift passt am besten?",
     opts:["a) Schrebergärten: Nur etwas für Rentner","b) Kleingärten — Geschichte, Bedeutung und Zukunft eines deutschen Phänomens","c) Das Bundeskleingartengesetz und seine Folgen"],
     ans:"b) Kleingärten — Geschichte, Bedeutung und Zukunft eines deutschen Phänomens",
     exp:"b) deckt alle Abschnitte ab: Geschichte (Abs.1,2), aktueller Wandel (Abs.3), Druck (Abs.4), Recht (Abs.5), Zukunft (Abs.6). a) und c) = zu eng.",
     textref:"Text: Entstehung → Wandel → Bedrohung → Gesetz → Zukunftsmodelle.",
     rule:"Makroaufgabe: Geschichte + Bedeutung + Zukunft = alle drei Dimensionen abgedeckt."}
  ],
  vocab:["das Grünnetz — зелёная сеть","der Schrebergarten — дача/огород (по-немецки)","einkommensschwach — малообеспеченный","die Parzelle — участок (в саду)","der Pachtvertrag — договор аренды","gedeihen — произрастать, процветать","das Relikt — пережиток, реликт"]
};
