// test-lv3h.js — Leseverstehen Teil 3
window.TELC_TEST = {
  id:"lv3h", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Essen in der Mensa — Hochschulgastronomie im Wandel",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Die Mensa — für viele Studierende das tägliche Pflichtprogramm. Günstig, praktisch, schnell. Doch das Image der Hochschulgastronomie hat sich gewandelt. Wo früher der berüchtigte Eintopf dominierte, locken heute Salatbars, vegetarische Gerichte und sogar vegane Menüs. Die Mensen konkurrieren zunehmend mit Bistros, Cafés und Fast-Food-Ketten in unmittelbarer Hochschulnähe.",
    "<strong>Abs.2:</strong> Das Studentenwerk, das die meisten deutschen Mensen betreibt, steht vor einem Balanceakt: einerseits preiswerte Mahlzeiten anbieten, andererseits Qualität und Nachhaltigkeit steigern. Pro Mittagessen zahlen Studierende im Schnitt zwischen 1,50 und 3,50 Euro — ein Preis, der nur durch hohe Subventionen möglich ist. Allein das Studentenwerk München betreibt 58 Mensen und Cafeterien und versorgt täglich über 60.000 Gäste.",
    "<strong>Abs.3:</strong> Ein wachsender Trend ist die Regionalisierung. Immer mehr Mensen beziehen Zutaten von lokalen Bauernhöfen und verzichten auf weite Transportwege. Das spart nicht nur CO₂, sondern garantiert auch frischere Produkte. In manchen Einrichtungen hängen sogar Landkarten an der Wand, die zeigen, woher jede Zutat stammt — ein Transparenzkonzept, das bei Studierenden gut ankommt.",
    "<strong>Abs.4:</strong> Nicht alle Veränderungen stoßen auf Begeisterung. Als das Studentenwerk Berlin ankündigte, den Fleischanteil im Angebot um 50 Prozent zu reduzieren, formierte sich Widerstand. Petitionen wurden gestartet, Leserbriefe geschrieben. Die Befürworter argumentieren mit Klimaschutz und Tierwohlbefinden, die Gegner pochen auf persönliche Wahlfreiheit. Der Streit ist symptomatisch für eine gesellschaftliche Debatte, die weit über die Mensa hinausgeht.",
    "<strong>Abs.5:</strong> Technisch rüsten die Mensen ebenfalls auf. Digitale Kassensysteme, App-basierte Speisepläne und kontaktloses Bezahlen sind in vielen Einrichtungen bereits Standard. In Pilotprojekten können Studierende sogar ihr Mittagessen per App vorbestellen und die Wartezeit so auf ein Minimum reduzieren. Einige Mensen experimentieren mit selbst lernenden Systemen, die Bestellmengen automatisch an den Bedarf anpassen und so Lebensmittelverschwendung verringern.",
    "<strong>Abs.6:</strong> Gleichwohl bleibt die soziale Funktion der Mensa unbestritten. Sie ist ein Ort der Begegnung, an dem Kommilitonen unterschiedlicher Herkunft und Fachbereiche zusammenkommen. Für internationale Studierende ist die Mensa oft der erste Berührungspunkt mit deutscher Esskultur. Aus diesem Grund plädieren Hochschulpädagogen dafür, die Mensa nicht als bloßen Verpflegungsbetrieb zu betrachten, sondern als Teil des Campus-Lebens."
  ],
  qs:[
    {n:13, t:"Das Angebot in deutschen Hochschulmensen hat sich in den letzten Jahren kaum verändert.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.1: «Das Image der Hochschulgastronomie hat sich gewandelt … Salatbars, vegetarische und vegane Menüs» statt früherem Eintopf.",
     textref:"«das Image der Hochschulgastronomie hat sich gewandelt. Wo früher der berüchtigte Eintopf dominierte, locken heute Salatbars…»",
     rule:"<em>gewandelt</em> = verändert ≠ kaum verändert. Direkter Widerspruch."},
    {n:14, t:"Günstige Mensapreise sind nur durch finanzielle Förderung möglich.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.2: «ein Preis, der nur durch hohe Subventionen möglich ist.»",
     textref:"«ein Preis, der nur durch hohe Subventionen möglich ist.»",
     rule:"Direkte Aussage. Paraphrase: finanzielle Förderung = Subventionen."},
    {n:15, t:"Das Studentenwerk München versorgt täglich mehr als 50.000 Personen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.2: «versorgt täglich über 60.000 Gäste» — 60.000 ist mehr als 50.000.",
     textref:"«versorgt täglich über 60.000 Gäste.»",
     rule:"60.000 > 50.000. «mehr als 50.000» ist korrekte Paraphrase von «über 60.000»."},
    {n:16, t:"Die Regionalisierung der Zutaten dient ausschließlich der Kostensenkung.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: «Das spart nicht nur CO₂, sondern garantiert auch frischere Produkte» — Umwelt + Qualität, nicht nur Kosten.",
     textref:"«Das spart nicht nur CO₂, sondern garantiert auch frischere Produkte.»",
     rule:"<em>nicht nur … sondern auch</em> = nicht ausschließlich. Mehrere Gründe, nicht nur Kosten."},
    {n:17, t:"Die Reduzierung des Fleischangebots in Berliner Mensen führte zu öffentlichem Protest.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «formierte sich Widerstand. Petitionen wurden gestartet, Leserbriefe geschrieben.»",
     textref:"«formierte sich Widerstand. Petitionen wurden gestartet, Leserbriefe geschrieben.»",
     rule:"öffentlicher Protest = Petitionen + Leserbriefe. Direkte Paraphrase."},
    {n:18, t:"Alle deutschen Mensen sind bereits vollständig digitalisiert.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.5: «in vielen Einrichtungen bereits Standard» — nicht alle, nur viele.",
     textref:"«in vielen Einrichtungen bereits Standard» + «In Pilotprojekten können Studierende…»",
     rule:"<em>in vielen</em> ≠ in allen. Pilotprojekte = noch nicht flächendeckend."},
    {n:19, t:"Einige Mensen nutzen Technologie, um Lebensmittelverschwendung zu reduzieren.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.5: «selbst lernende Systeme, die Bestellmengen automatisch … anpassen und so Lebensmittelverschwendung verringern.»",
     textref:"«selbst lernende Systeme … Lebensmittelverschwendung verringern.»",
     rule:"Direkte Aussage im Text."},
    {n:20, t:"Die Mensa wird von Hochschulpädagogen als reiner Verpflegungsbetrieb angesehen.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.6: «plädieren Hochschulpädagogen dafür, die Mensa nicht als bloßen Verpflegungsbetrieb zu betrachten» — Gegenteil!",
     textref:"«plädieren … die Mensa nicht als bloßen Verpflegungsbetrieb zu betrachten, sondern als Teil des Campus-Lebens.»",
     rule:"<em>nicht als … sondern als</em> = nicht X, sondern Y. Die Pädagogen lehnen diese Sichtweise ab."},
    {n:21, t:"Für Studierende aus dem Ausland ist die Mensa ein wichtiger Kontaktpunkt mit deutschen Essgewohnheiten.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.6: «Für internationale Studierende ist die Mensa oft der erste Berührungspunkt mit deutscher Esskultur.»",
     textref:"«Für internationale Studierende ist die Mensa oft der erste Berührungspunkt mit deutscher Esskultur.»",
     rule:"Direkte Paraphrase: Berührungspunkt = Kontaktpunkt, Esskultur = Essgewohnheiten."},
    {n:22, t:"Die Debatte über Fleisch in der Mensa spiegelt einen breiteren gesellschaftlichen Konflikt wider.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «Der Streit ist symptomatisch für eine gesellschaftliche Debatte, die weit über die Mensa hinausgeht.»",
     textref:"«Der Streit ist symptomatisch für eine gesellschaftliche Debatte, die weit über die Mensa hinausgeht.»",
     rule:"<em>symptomatisch für</em> = показательный для, отражающий. Direkte Aussage."},
    {n:23, t:"Per App lässt sich in manchen Mensen das Essen bereits im Voraus bestellen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.5: «können Studierende sogar ihr Mittagessen per App vorbestellen.»",
     textref:"«können Studierende sogar ihr Mittagessen per App vorbestellen und die Wartezeit so auf ein Minimum reduzieren.»",
     rule:"Direkte Aussage. <em>vorbestellen</em> = im Voraus bestellen."},
    {n:24, t:"Welche Überschrift passt am besten?",
     opts:["a) Streit um Fleisch: Mensen im politischen Kreuzfeuer","b) Von der Kantine zur modernen Hochschulgastronomie — Wandel und Herausforderungen","c) Digitalisierung rettet die Mensa"],
     ans:"b) Von der Kantine zur modernen Hochschulgastronomie — Wandel und Herausforderungen",
     exp:"b) deckt alle Themen ab: Wandel (Abs.1), Preise/Subventionen (Abs.2), Regionalität (Abs.3), Debatte (Abs.4), Digitalisierung (Abs.5), soziale Funktion (Abs.6). a) und c) = zu eng.",
     textref:"Gesamter Text behandelt: Image-Wandel + Preise + Nachhaltigkeit + Konflikt + Technik + Soziales.",
     rule:"Makroaufgabe: Überschrift mit <em>und</em> = deckt mehrere Aspekte ab. Kein einzelner Aspekt dominiert."}
  ],
  vocab:["die Subvention — субсидия, дотация","die Regionalisierung — регионализация","die Zutat — ингредиент","stoßen auf — наталкиваться на (реакцию)","plädieren für — выступать за","der Berührungspunkt — точка соприкосновения","symptomatisch — симптоматичный, показательный"]
};
