// test-lv3j.js — Leseverstehen Teil 3
window.TELC_TEST = {
  id:"lv3j", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Haben Navis unser Gehirn verändert?",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> «Bitte links abbiegen» — für viele Autofahrer ist die Stimme des Navigationsgeräts zum treuen Begleiter geworden. Kaum jemand faltet heute noch Straßenkarten auf dem Beifahrersitz auseinander. Doch während Navis unser Reisen praktischer machen, werfen Wissenschaftler eine beunruhigende Frage auf: Verlernen wir durch ständige Navigation die Fähigkeit, uns selbst zu orientieren?",
    "<strong>Abs.2:</strong> Unser Gehirn besitzt ein erstaunliches Navigationssystem. Im Hippocampus, einem kleinen Bereich im Inneren des Gehirns, befinden sich sogenannte Ortszellen und Rasterzellen, die gemeinsam eine Art innere Landkarte unserer Umgebung aufbauen. Je mehr wir uns aktiv orientieren — also bewusst auf Umgebungsmerkmale achten — desto stärker wird dieses neuronale Netz. Für ihre Entdeckung dieser Zellen erhielten die Forscher 2014 den Nobelpreis für Medizin.",
    "<strong>Abs.3:</strong> Eine vielzitierte Studie an Londoner Taxifahrern zeigte: Menschen, die täglich ohne Navi durch ein komplexes Straßennetz navigieren, entwickeln einen signifikant vergrößerten Hippocampus. Die Studie von Wissenschaftlerin Eleanor Maguire gilt als Beleg dafür, dass das Gehirn sich durch aktive Nutzung buchstäblich umbaut — ein Prinzip, das als Neuroplastizität bekannt ist.",
    "<strong>Abs.4:</strong> Was passiert hingegen, wenn wir uns auf das Navi verlassen? Neue Experimente zeigen: Probanden, die bei einem Test mit GPS navigierten, zeigten deutlich weniger Aktivität im Hippocampus als jene, die sich selbst orientierten. Das Gehirn schaltet gewissermaßen auf «Autopilot» — es verarbeitet die Informationen, die das Gerät liefert, ohne eigene mentale Karten zu erstellen.",
    "<strong>Abs.5:</strong> Langzeiteffekte sind noch nicht abschließend erforscht. Es gibt aber Hinweise darauf, dass Menschen, die selten selbst navigieren, im Alter anfälliger für kognitive Einbußen sind. Manche Forscher spekulieren, ob die weit verbreitete Navi-Nutzung mittel- bis langfristig zu einer Schwächung räumlicher Denkfähigkeiten in der Bevölkerung führen könnte.",
    "<strong>Abs.6:</strong> Ein vollständiger Verzicht auf Navigationshilfen ist freilich keine realistische Forderung. Sinnvoller erscheint ein bewusster Umgang: Gelegentlich das Navi ausschalten, neue Wege selbst erkunden und sich dabei aktiv auf die Umgebung einlassen. Schon wenige Minuten des aktiven Navigierens pro Tag können laut Experten helfen, das räumliche Denkvermögen zu erhalten."
  ],
  qs:[
    {n:13, t:"Die meisten Menschen benutzen heute noch Straßenkarten für die Navigation.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.1: «Kaum jemand faltet heute noch Straßenkarten auf dem Beifahrersitz auseinander.»",
     textref:"«Kaum jemand faltet heute noch Straßenkarten … auseinander.»",
     rule:"<em>kaum jemand</em> = почти никто ≠ die meisten. Direkter Widerspruch."},
    {n:14, t:"Im Hippocampus befinden sich Zellen, die zur räumlichen Orientierung beitragen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.2: «Im Hippocampus befinden sich sogenannte Ortszellen und Rasterzellen, die … eine innere Landkarte aufbauen.»",
     textref:"«Im Hippocampus … Ortszellen und Rasterzellen, die gemeinsam eine Art innere Landkarte aufbauen.»",
     rule:"Direkte Aussage. Ortszellen + Rasterzellen = zur räumlichen Orientierung."},
    {n:15, t:"Die Entdeckung der Ortszellen im Gehirn wurde mit dem Nobelpreis ausgezeichnet.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.2: «Für ihre Entdeckung dieser Zellen erhielten die Forscher 2014 den Nobelpreis für Medizin.»",
     textref:"«Für ihre Entdeckung dieser Zellen erhielten die Forscher 2014 den Nobelpreis für Medizin.»",
     rule:"Direkte Aussage im Text."},
    {n:16, t:"Die Studie an Londoner Taxifahrern bewies, dass Navis das Gehirn schrumpfen lassen.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: Die Studie zeigt, dass aktives Navigieren den Hippocampus vergrößert — aber nichts über Navi-Nutzung und Schrumpfen.",
     textref:"«entwickeln einen signifikant vergrößerten Hippocampus» — Studie zu aktivem Navigieren, NICHT zu Navi-Nutzung.",
     rule:"Studie zeigt Wachstum durch aktives Navigieren ≠ Navis lassen Gehirn schrumpfen. Falsche Schlussfolgerung."},
    {n:17, t:"Bei GPS-Nutzung ist der Hippocampus weniger aktiv als beim selbstständigen Navigieren.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «zeigten deutlich weniger Aktivität im Hippocampus als jene, die sich selbst orientierten.»",
     textref:"«Probanden, die mit GPS navigierten, zeigten deutlich weniger Aktivität im Hippocampus.»",
     rule:"Direkte Aussage. GPS-Nutzung → weniger Hippocampus-Aktivität."},
    {n:18, t:"Es ist wissenschaftlich bewiesen, dass Navi-Nutzung langfristig das Denkvermögen schwächt.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.5: «Langzeiteffekte sind noch nicht abschließend erforscht … Manche Forscher spekulieren …» — noch nicht bewiesen.",
     textref:"«Langzeiteffekte sind noch nicht abschließend erforscht.» + «spekulieren»",
     rule:"<em>spekulieren</em> = spekulieren (не доказано). <em>noch nicht abschließend erforscht</em> = ещё не доказано окончательно."},
    {n:19, t:"Wissenschaftler empfehlen, ganz auf Navis zu verzichten.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.6: «Ein vollständiger Verzicht … ist freilich keine realistische Forderung.»",
     textref:"«Ein vollständiger Verzicht auf Navigationshilfen ist freilich keine realistische Forderung.»",
     rule:"<em>keine realistische Forderung</em> = нереалистичное требование ≠ Empfehlung zum Verzicht."},
    {n:20, t:"Aktives Selbstorientieren stärkt die neuronalen Netzwerke im Gehirn.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.2: «Je mehr wir uns aktiv orientieren … desto stärker wird dieses neuronale Netz.»",
     textref:"«Je mehr wir uns aktiv orientieren … desto stärker wird dieses neuronale Netz.»",
     rule:"Direkte Aussage: aktives Orientieren → stärkeres neuronales Netz."},
    {n:21, t:"Eleanor Maguire forschte über die Auswirkungen von Navigationssystemen auf das Gehirn.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: Maguires Studie war über Londoner Taxifahrer (aktives Navigieren ohne Navi), nicht über GPS-Geräte.",
     textref:"«Die Studie von Wissenschaftlerin Eleanor Maguire» — über Taxifahrer, nicht über Navis.",
     rule:"Inhalt der Studie: Taxifahrer ohne Navi ≠ Auswirkungen von Navigationssystemen."},
    {n:22, t:"Gelegentliches Navigieren ohne Gerät kann laut Experten das räumliche Denken erhalten.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.6: «Schon wenige Minuten des aktiven Navigierens pro Tag können … das räumliche Denkvermögen erhalten.»",
     textref:"«Schon wenige Minuten des aktiven Navigierens pro Tag können laut Experten helfen, das räumliche Denkvermögen zu erhalten.»",
     rule:"Direkte Paraphrase: gelegentliches Navigieren = wenige Minuten aktiven Navigierens."},
    {n:23, t:"Das Neuroplastizitätsprinzip besagt, dass das Gehirn sich durch Nutzung verändern kann.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.3: «das Gehirn sich durch aktive Nutzung buchstäblich umbaut — ein Prinzip, das als Neuroplastizität bekannt ist.»",
     textref:"«das Gehirn sich durch aktive Nutzung buchstäblich umbaut — ein Prinzip, das als Neuroplastizität bekannt ist.»",
     rule:"Direkte Paraphrase: umbaut = verändern kann. Neuroplastizität = Umbau durch Nutzung."},
    {n:24, t:"Welche Überschrift passt am besten?",
     opts:["a) Londoner Taxifahrer beweisen: Navis machen dumm","b) Navigationssysteme und ihre Auswirkungen auf die Orientierungsfähigkeit des Gehirns","c) Nobelpreis für Hirnforschung: Die Geschichte der Ortszellen"],
     ans:"b) Navigationssysteme und ihre Auswirkungen auf die Orientierungsfähigkeit des Gehirns",
     exp:"b) deckt alle Aspekte ab: Navi-Nutzung (Abs.1,4), Gehirnstruktur (Abs.2,3), Langzeiteffekte (Abs.5), Empfehlungen (Abs.6). a) und c) = zu eng.",
     textref:"Gesamter Text: Navis → Gehirn → Hippocampus → Langzeiteffekte → Empfehlungen.",
     rule:"Makroaufgabe: Überschrift muss alle Abschnitte umfassen. Keine Einzelaspekte."}
  ],
  vocab:["der Hippocampus — гиппокамп","die Ortszelle — клетка места (нейрон)","die Neuroplastizität — нейропластичность","sich orientieren — ориентироваться","anfällig — подверженный, восприимчивый","die kognitive Einbuße — снижение когнитивных способностей","gelegentlich — время от времени"]
};
