// test-sb3.js — TELC C1
window.TELC_TEST = {
  id:"sb3", type:"Sprachbausteine", kind:"sb",
  title:"Neues aus der Bionik",
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Natur in der Technik <strong>(25)</strong>. Zuerst ist da zum Beispiel das Staunen über die Fähigkeit von Tieren wie den Geckos, an senkrechten Wänden und Glascheiben <strong>(26)</strong>. Oder das Bewundern des Lotusblatts, das Wasser <strong>(27)</strong> von sich abperlen lässt, ohne dabei nass zu werden. Die Wissenschaftler, die sich <strong>(28)</strong> beschäftigen, diese natürlichen Phänomene für die Technik <strong>(29)</strong> zu machen, nennen sich Bioniker.</p><p>Das Wort Bionik <strong>(30)</strong> sich aus den Begriffen Biologie und Technik zusammen und bezeichnet die Wissenschaft, die Erkenntnisse aus dem Tier- und Pflanzenreich auf technische Probleme <strong>(31)</strong>. Im Zentrum steht dabei stets die Frage, wie die Natur nach Jahrmillionen der Evolution <strong>(32)</strong> hat, Probleme zu lösen, mit denen auch der Mensch konfrontiert ist.</p><p>Denn die Natur ist, <strong>(33)</strong> gesagt, ein hervorragender Ingenieur. Oder wie die Bioniker es ausdrücken: <strong>(34)</strong> Evolution hat keine schlechten Noten <strong>(35)</strong>. Schlechte Konstruktionen haben sich im Laufe der Zeit nicht <strong>(36)</strong>. Die Natur <strong>(37)</strong> daher immer nach Lösungen, die effizient, stabil und energiesparend sind.</p><p>Die <strong>(38)</strong> bekanntesten Beispiele für gelungene Bionik sind der Klettverschluss und der Haifischhaut-Badeanzug. Der Schweizer Ingenieur Georges de Mestral <strong>(39)</strong> 1941 beim Wandern, dass sich Klettfrüchte in seinem Pullover <strong>(40)</strong> hatten, und entwickelte daraus den Klettverschluss. Beim Haifischhaut-Badeanzug wurde die <strong>(41)</strong> Struktur der Haifischhaut, die den Wasserwiderstand <strong>(42)</strong>, imitiert.</p><p>Aber auch in der Architektur <strong>(43)</strong> sich die Natur als Vorbild: Termitenhügel besitzen ein natürliches Klimatisierungssystem, <strong>(44)</strong> viele Gebäude heute nachempfunden werden. Und Seifenblasen haben Architekten bei der Entwicklung leichter, aber stabiler Kuppelkonstruktionen <strong>(45)</strong>. Die Bionik ist damit <strong>(46)</strong> eine der spannendsten Schnittstellen zwischen Natur und moderner Technologie.</div>',
  qs:[
    {n:25,ctx:"Natur in der Technik ___",
     opts:["a) bewährt sich","b) erweist sich","c) findet sich","d) zeigt sich"],ans:"a) bewährt sich",
     exp:"<strong>a) bewährt sich</strong> — <em>sich bewähren</em> = оправдывать себя, подтверждать ценность. «Natur bewährt sich in der Technik» = природа доказывает свою ценность в технике.",
     rule:"<em>sich bewähren</em> = доказывать свою ценность/эффективность. Фиксированное выражение C1."},
    {n:26,ctx:"die Fähigkeit von Geckos, an senkrechten Wänden ___",
     opts:["a) festzuhalten","b) hochzuklettern","c) entlangzugehen","d) haftenzubleiben"],ans:"d) haftenzubleiben",
     exp:"<strong>d) haftenzubleiben</strong> — <em>haften</em> = прилипать, цепляться. Гекконы именно «остаются прилипшими» к стенам. Infinitiv mit zu от <em>haftenbleiben</em>.",
     rule:"<em>haftenbleiben</em> = прилипать, удерживаться на поверхности. Трennbares Verb: <em>haften|bleiben → haftenzu bleiben</em>."},
    {n:27,ctx:"das Lotusblatt, das Wasser ___ von sich abperlen lässt",
     opts:["a) einfach","b) glatt","c) problemlos","d) rückstandslos"],ans:"d) rückstandslos",
     exp:"<strong>d) rückstandslos</strong> = бесследно, без остатка. Вода стекает с листа лотоса не оставляя следов.",
     rule:"<em>rückstandslos</em> = не оставляя следов/остатков (C1-Wort). <em>abperlen</em> = скатываться каплями."},
    {n:28,ctx:"die Wissenschaftler, die sich ___ beschäftigen",
     opts:["a) dabei","b) dafür","c) damit","d) daran"],ans:"c) damit",
     exp:"<strong>c) damit</strong> = da + mit. Verweist auf das Vorherige: <em>sich damit beschäftigen</em> = заниматься этим.",
     rule:"<em>sich mit etw. beschäftigen → sich damit beschäftigen</em>. Pronominaladverb <em>da(r) + Präposition</em>."},
    {n:29,ctx:"diese natürlichen Phänomene für die Technik ___ zu machen",
     opts:["a) anwendbar","b) brauchbar","c) nutzbar","d) verwendbar"],ans:"c) nutzbar",
     exp:"<strong>c) nutzbar</strong> — <em>nutzbar machen</em> = делать пригодным для использования. Фиксированное словосочетание в научных текстах.",
     rule:"<em>etw. nutzbar machen</em> = делать что-л. используемым/пригодным (C1-Phrase)."},
    {n:30,ctx:"Das Wort Bionik ___ sich aus den Begriffen Biologie und Technik zusammen",
     opts:["a) bildet","b) ergibt","c) setzt","d) stellt"],ans:"c) setzt",
     exp:"<strong>c) setzt</strong> — <em>sich zusammensetzen aus</em> = состоять из, складываться из. Обязательное возвратное местоимение!",
     rule:"<em>sich aus etw. zusammensetzen</em> = состоять из чего-л. (фиксированная конструкция C1)."},
    {n:31,ctx:"die Wissenschaft, die Erkenntnisse aus dem Tier- und Pflanzenreich auf technische Probleme ___",
     opts:["a) anwendet","b) aufträgt","c) einsetzt","d) überträgt"],ans:"d) überträgt",
     exp:"<strong>d) überträgt</strong> — <em>Erkenntnisse übertragen</em> = переносить знания/результаты. Wissenschaftlicher Fachbegriff.",
     rule:"<em>etw. auf etw. übertragen</em> = применять/переносить что-л. на что-л."},
    {n:32,ctx:"wie die Natur nach Jahrmillionen der Evolution ___ hat, Probleme zu lösen",
     opts:["a) gelernt","b) geschafft","c) gesucht","d) versucht"],ans:"a) gelernt",
     exp:"<strong>a) gelernt</strong> — <em>gelernt haben, etw. zu tun</em> = научиться делать что-л. (за миллионы лет эволюции).",
     rule:"<em>etw. zu tun lernen → gelernt haben, etw. zu tun</em>. Infinitiv Perfekt mit <em>haben</em>."},
    {n:33,ctx:"Die Natur ist, ___ gesagt, ein hervorragender Ingenieur",
     opts:["a) frei","b) gut","c) klar","d) offen"],ans:"a) frei",
     exp:"<strong>a) frei</strong> — <em>frei gesagt / frei heraus gesagt</em> = говоря откровенно, если честно. Фиксированная вводная конструкция.",
     rule:"<em>frei gesagt</em> = если честно, откровенно говоря. Вводная конструкция C1."},
    {n:34,ctx:"___ Evolution hat keine schlechten Noten",
     opts:["a) Das","b) Der","c) Die","d) Eine"],ans:"c) Die",
     exp:"<strong>c) Die</strong> — <em>die Evolution</em> (fem.) → bestimmter Artikel. Allgemein bekanntes Konzept → bestimmter Artikel.",
     rule:"Wissenschaftliche Konzepte mit generischer Bedeutung nehmen den bestimmten Artikel: <em>die Evolution, die Natur</em>."},
    {n:35,ctx:"Evolution hat keine schlechten Noten ___",
     opts:["a) bekommen","b) erhalten","c) gekriegt","d) vergeben"],ans:"b) erhalten",
     exp:"<strong>b) erhalten</strong> — <em>Noten erhalten</em> = получать оценки. Формальное слово для научного/нейтрального текста.",
     rule:"<em>erhalten</em> = получать (формально) / <em>bekommen</em> = получать (разговорно). В C1-текстах предпочтительно <em>erhalten</em>."},
    {n:36,ctx:"Schlechte Konstruktionen haben sich im Laufe der Zeit nicht ___",
     opts:["a) bewährt","b) bewiesen","c) durchgesetzt","d) gehalten"],ans:"c) durchgesetzt",
     exp:"<strong>c) durchgesetzt</strong> — <em>sich durchsetzen</em> = утвердиться, возобладать. Плохие конструкции не смогли утвердиться в ходе эволюции.",
     rule:"<em>sich durchsetzen</em> = утверждаться, побеждать (в конкуренции/отборе)."},
    {n:37,ctx:"Die Natur ___ daher immer nach Lösungen, die effizient sind",
     opts:["a) forscht","b) schaut","c) strebt","d) sucht"],ans:"d) sucht",
     exp:"<strong>d) sucht</strong> — <em>nach etw. suchen</em> = искать что-л. Метафора: природа «ищет» эффективные решения.",
     rule:"<em>nach etw. suchen</em> = искать что-л. (Präposition <em>nach</em> obligatorisch!)."},
    {n:38,ctx:"Die ___ bekanntesten Beispiele für gelungene Bionik",
     opts:["a) allseits","b) allgemein","c) wohl","d) zweifellos"],ans:"c) wohl",
     exp:"<strong>c) wohl</strong> — <em>wohl bekanntesten</em> = пожалуй, самые известные. Модальная частица для смягчённого утверждения.",
     rule:"<em>wohl</em> как Partikel = пожалуй, наверное (смягчение утверждения, C1)."},
    {n:39,ctx:"Der Ingenieur Georges de Mestral ___ 1941 beim Wandern, dass sich Klettfrüchte … hatten",
     opts:["a) bemerkte","b) erkannte","c) merkte","d) sah"],ans:"a) bemerkte",
     exp:"<strong>a) bemerkte</strong> — <em>bemerken</em> = заметить, обратить внимание. Описывает момент наблюдения.",
     rule:"<em>bemerken</em> = заметить (сознательно). <em>merken</em> = заметить (почувствовать). Тонкое различие."},
    {n:40,ctx:"dass sich Klettfrüchte in seinem Pullover ___ hatten",
     opts:["a) festgehakt","b) festgehalten","c) festgesetzt","d) festgehängt"],ans:"a) festgehakt",
     exp:"<strong>a) festgehakt</strong> — <em>sich festhaken</em> = зацепиться, застрять. Клетчатые плоды именно «зацепились» за свитер.",
     rule:"<em>sich festhaken</em> = зацепиться (как крючком). Trennbares Verb: <em>fest|haken → festgehakt</em>."},
    {n:41,ctx:"die ___ Struktur der Haifischhaut",
     opts:["a) besondere","b) feine","c) gerillte","d) raue"],ans:"c) gerillte",
     exp:"<strong>c) gerillte</strong> — <em>gerillt</em> = рифлёная, с бороздками. Кожа акулы имеет именно рифлёную структуру, снижающую сопротивление воды.",
     rule:"<em>gerillt</em> = рифлёный, с продольными бороздками. Технический термин Bionik."},
    {n:42,ctx:"die gerillte Struktur der Haifischhaut, die den Wasserwiderstand ___",
     opts:["a) erniedrigt","b) mindert","c) reduziert","d) vermindert"],ans:"c) reduziert",
     exp:"<strong>c) reduziert</strong> — <em>den Widerstand reduzieren</em> = снижать сопротивление. Технически точный термин.",
     rule:"<em>reduzieren</em> = снижать, уменьшать (технический/научный термин C1)."},
    {n:43,ctx:"Aber auch in der Architektur ___ sich die Natur als Vorbild",
     opts:["a) erweist","b) gibt","c) gilt","d) zeigt"],ans:"a) erweist",
     exp:"<strong>a) erweist</strong> — <em>sich als etw. erweisen</em> = оказываться чем-л., проявлять себя как. Формальная конструкция.",
     rule:"<em>sich als etw. erweisen</em> = оказываться чем-л. (C1). Ср.: <em>sich zeigen</em> = проявляться (менее формально)."},
    {n:44,ctx:"Termitenhügel besitzen ein natürliches Klimatisierungssystem, ___ viele Gebäude heute nachempfunden werden",
     opts:["a) das","b) dem","c) dessen","d) welchem"],ans:"b) dem",
     exp:"<strong>b) dem</strong> — Relativpronomen Dativ Neutrum: <em>nachempfinden + Dativ</em>. «dem System nachempfunden werden» = создан по образцу этой системы.",
     rule:"<em>etw./jmdm. nachempfinden</em> (Dativ!) = создавать по образцу чего-л."},
    {n:45,ctx:"Seifenblasen haben Architekten bei der Entwicklung leichter Kuppelkonstruktionen ___",
     opts:["a) angeregt","b) bewogen","c) geleitet","d) inspiriert"],ans:"d) inspiriert",
     exp:"<strong>d) inspiriert</strong> — <em>jmdn. zu etw. inspirieren</em> = вдохновлять кого-л. на что-л. Контекст творческого вдохновения.",
     rule:"<em>inspirieren</em> = вдохновлять. <em>anregen</em> = побуждать (менее эмоционально). Здесь подходит <em>inspiriert</em>."},
    {n:46,ctx:"Die Bionik ist damit ___ eine der spannendsten Schnittstellen",
     opts:["a) also","b) daher","c) folglich","d) somit"],ans:"d) somit",
     exp:"<strong>d) somit</strong> — <em>somit</em> = таким образом, следовательно. Делает вывод из всего вышесказанного. Формальнее чем <em>also</em>.",
     rule:"<em>somit</em> = таким образом (формальный вывод, C1) > <em>also</em> = итак (разговорнее)."}
  ],
  vocab:["sich bewähren — оправдывать себя","haftenbleiben — прилипать, удерживаться","nutzbar machen — делать пригодным","sich übertragen auf — переноситься на","sich durchsetzen — утверждаться, побеждать","frei gesagt — откровенно говоря","sich als etw. erweisen — оказываться чем-л.","somit — таким образом (вывод)"]
};
