// test-lv3i.js — Leseverstehen Teil 3
window.TELC_TEST = {
  id:"lv3i", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Zweisprachig aufwachsen — Fluch oder Segen?",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Über 60 Millionen Menschen in Deutschland leben in mehrsprachigen Familien. Kinder, die von Geburt an mit zwei oder mehr Sprachen aufwachsen, gelten in der Forschung als simultan mehrsprachig. Lange Zeit glaubten viele Eltern, Erzieher und sogar Ärzte, dass Mehrsprachigkeit Kinder verwirre und ihre Sprachentwicklung verzögere. Diese Ansicht gilt heute als wissenschaftlich überholt.",
    "<strong>Abs.2:</strong> Neuere Studien zeigen: Kinder, die mehrere Sprachen gleichzeitig lernen, entwickeln bestimmte kognitive Fähigkeiten schneller als einsprachige Gleichaltrige. Dazu gehören vor allem die sogenannte exekutive Kontrolle — also die Fähigkeit, Aufmerksamkeit zu steuern und irrelevante Informationen auszublenden — sowie ein ausgeprägtes Metasprachbewusstsein. Zweisprachige Kinder wissen früher, dass Sprache ein System mit Regeln ist.",
    "<strong>Abs.3:</strong> Allerdings hat Mehrsprachigkeit auch ihre Schattenseiten. Der Wortschatz in jeder einzelnen Sprache ist anfangs oft geringer als bei einsprachigen Kindern. Dieser Unterschied gleicht sich jedoch bis zum Schulalter in der Regel aus. Außerdem kann es bei sehr kleinen Kindern zu einem sogenannten Code-Switching kommen — dem unbewussten Wechsel zwischen den Sprachen mitten im Satz. Das ist entwicklungspsychologisch normal und kein Zeichen von Verwirrung.",
    "<strong>Abs.4:</strong> Entscheidend für den Erfolg der Mehrsprachigkeit ist, welche Sprachen das Kind hört und wie oft. Kinder lernen Sprachen vor allem durch lebendige, emotionale Kommunikation — nicht durch Sprachkurse oder Apps. Wenn ein Elternteil konsequent eine Sprache spricht und das Kind diese Sprache regelmäßig in bedeutsamen Situationen hört, wird es sie aktiv erwerben. Das Prinzip «eine Person — eine Sprache» gilt in der Forschung als besonders wirksam.",
    "<strong>Abs.5:</strong> Im Schulalter beginnen viele zweisprachige Kinder, eine Sprache zu bevorzugen — meist die Sprache der Schule und der Peers. Die Minderheitensprache, oft die Sprache der Großeltern oder des Herkunftslandes, droht zu verblassen. Eltern können gegensteuern, indem sie Bücher, Filme und persönliche Kontakte in der Minderheitensprache fördern. Sprachreisen in das Herkunftsland können ebenfalls helfen.",
    "<strong>Abs.6:</strong> Mehrsprachigkeit bietet langfristig erhebliche Vorteile: bessere Berufschancen, kulturelle Flexibilität und nachweislich einen späteren Einsatz von Demenzerkrankungen im Alter. Neurowissenschaftler gehen davon aus, dass das ständige Jonglieren zweier Sprachsysteme das Gehirn trainiert und seine Reservekapazitäten stärkt. Zweisprachigkeit ist damit nicht nur ein kommunikativer Vorteil, sondern eine Art lebenslange mentale Fitness."
  ],
  qs:[
    {n:13, t:"Die Vorstellung, dass Mehrsprachigkeit Kindern schadet, ist heute wissenschaftlich anerkannt.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.1: «Diese Ansicht gilt heute als wissenschaftlich überholt.» — das Gegenteil ist der Fall.",
     textref:"«Diese Ansicht gilt heute als wissenschaftlich überholt.»",
     rule:"<em>überholt</em> = устаревший, опровергнутый ≠ anerkannt. Direkter Widerspruch."},
    {n:14, t:"Zweisprachige Kinder entwickeln bestimmte Denkfähigkeiten früher als einsprachige.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.2: «entwickeln bestimmte kognitive Fähigkeiten schneller als einsprachige Gleichaltrige.»",
     textref:"«entwickeln bestimmte kognitive Fähigkeiten schneller als einsprachige Gleichaltrige.»",
     rule:"Direkte Paraphrase: kognitive Fähigkeiten = Denkfähigkeiten, schneller = früher."},
    {n:15, t:"Code-Switching bei kleinen Kindern ist ein Hinweis auf Sprachstörungen.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: «Das ist entwicklungspsychologisch normal und kein Zeichen von Verwirrung.»",
     textref:"«Das ist entwicklungspsychologisch normal und kein Zeichen von Verwirrung.»",
     rule:"normal ≠ Hinweis auf Störungen. Direkter Widerspruch."},
    {n:16, t:"Der geringere Wortschatz in jeder Einzelsprache bleibt bei zweisprachigen Kindern dauerhaft bestehen.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: «Dieser Unterschied gleicht sich jedoch bis zum Schulalter in der Regel aus.»",
     textref:"«Dieser Unterschied gleicht sich jedoch bis zum Schulalter in der Regel aus.»",
     rule:"<em>sich ausgleichen</em> = выравниваться ≠ dauerhaft bestehen bleiben."},
    {n:17, t:"Sprachkurse und Apps gelten als effektivste Methode für den Spracherwerb bei Kindern.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.4: «Kinder lernen Sprachen vor allem durch lebendige, emotionale Kommunikation — nicht durch Sprachkurse oder Apps.»",
     textref:"«nicht durch Sprachkurse oder Apps.»",
     rule:"Direkter Widerspruch: «nicht durch» = именно НЕ через курсы и приложения."},
    {n:18, t:"Das Prinzip «eine Person — eine Sprache» wird von der Forschung empfohlen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «Das Prinzip ‹eine Person — eine Sprache› gilt in der Forschung als besonders wirksam.»",
     textref:"«Das Prinzip ‹eine Person — eine Sprache› gilt in der Forschung als besonders wirksam.»",
     rule:"<em>gilt als besonders wirksam</em> = считается особенно эффективным = wird empfohlen."},
    {n:19, t:"Im Schulalter neigen zweisprachige Kinder dazu, beide Sprachen gleich stark zu nutzen.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.5: «beginnen viele zweisprachige Kinder, eine Sprache zu bevorzugen» — eine Sprache wird bevorzugt.",
     textref:"«beginnen viele zweisprachige Kinder, eine Sprache zu bevorzugen — meist die Sprache der Schule.»",
     rule:"bevorzugen = предпочитать ≠ gleich stark nutzen."},
    {n:20, t:"Sprachreisen können dabei helfen, die schwächere Sprache zu erhalten.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.5: «Sprachreisen in das Herkunftsland können ebenfalls helfen.»",
     textref:"«Sprachreisen in das Herkunftsland können ebenfalls helfen.»",
     rule:"Direkte Aussage im Text."},
    {n:21, t:"Mehrsprachigkeit kann den Beginn von Demenzerkrankungen hinauszögern.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.6: «nachweislich einen späteren Einsatz von Demenzerkrankungen im Alter.»",
     textref:"«nachweislich einen späteren Einsatz von Demenzerkrankungen im Alter.»",
     rule:"<em>später</em> = позже = hinauszögern. Direkte Paraphrase."},
    {n:22, t:"Zweisprachige Kinder haben von Anfang an in jeder Sprache denselben Wortschatz wie Einsprachige.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: «Der Wortschatz in jeder einzelnen Sprache ist anfangs oft geringer als bei einsprachigen Kindern.»",
     textref:"«Der Wortschatz in jeder einzelnen Sprache ist anfangs oft geringer.»",
     rule:"<em>geringer</em> = меньше ≠ denselben Wortschatz. Direkter Widerspruch."},
    {n:23, t:"Das gleichzeitige Verwenden zweier Sprachen trainiert das Gehirn.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.6: «das ständige Jonglieren zweier Sprachsysteme das Gehirn trainiert.»",
     textref:"«das ständige Jonglieren zweier Sprachsysteme das Gehirn trainiert und seine Reservekapazitäten stärkt.»",
     rule:"Direkte Paraphrase: Jonglieren zweier Sprachen = gleichzeitiges Verwenden."},
    {n:24, t:"Welche Überschrift passt am besten?",
     opts:["a) Zweisprachige Kinder: Warum Apps das Lernen erleichtern","b) Mehrsprachigkeit: Chancen, Herausforderungen und langfristige Vorteile","c) Code-Switching — das größte Problem zweisprachiger Kinder"],
     ans:"b) Mehrsprachigkeit: Chancen, Herausforderungen und langfristige Vorteile",
     exp:"b) deckt alle Abschnitte ab: Vorurteile (Abs.1), kognitive Vorteile (Abs.2), Herausforderungen (Abs.3), Methoden (Abs.4), Schulalter (Abs.5), Langzeitvorteile (Abs.6). a) und c) = zu eng.",
     textref:"Gesamter Text: Mythos → Vorteile → Nachteile → Methoden → Schulalter → Langzeitnutzen.",
     rule:"Makroaufgabe: Überschrift muss ALLE Aspekte abdecken. Chancen + Herausforderungen + Vorteile = alle drei Dimensionen."}
  ],
  vocab:["simultan mehrsprachig — одновременно многоязычный","überholt — устаревший, опровергнутый","die exekutive Kontrolle — исполнительный контроль","das Code-Switching — переключение кодов (языков)","verblassen — блёкнуть, угасать","das Jonglieren — жонглирование","die Reservekapazität — резервная мощность мозга"]
};
