// test-sb2.js — TELC C1
window.TELC_TEST = {
  id:"sb2", type:"Sprachbausteine", kind:"sb",
  title:"Das Gehirn des Rauchers ist weniger flexibel",
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Raucher denken weniger flexibel, sie reagieren weniger stark auf alternative Handlungsszenarien. Genau diese Erkenntnis erklärt auch, warum es Rauchern oftmals so schwerfällt, von ihrer Sucht <strong>(25)</strong>. Dies sind die Resultate einer neuen Studie <strong>(26)</strong> Hirnforscher. Die Ergebnisse dieser Studie wurden nun auch im Fachmagazin &bdquo;Nature Neuroscience" <strong>(27)</strong>. Wir wollen hier das Wichtigste <strong>(28)</strong>.</p><p>Süchtige sehen die Welt anders – das ist <strong>(29)</strong> nur eine subjektive Behauptung, sondern nun auch wissenschaftlich belegt. Dabei beeinflusst die Sucht das Verhalten der Betroffenen <strong>(30)</strong> vielfältige Weise. Süchtige lassen sich zum Beispiel schwerer sättigen, sie machen exzessiv mit einem Verhalten weiter, wenn andere längst <strong>(31)</strong>.</p><p>Ziel der Forscher war es, die Sucht der Raucher <strong>(32)</strong>. Rauchen verändert die Wahrnehmung – das war bekannt. Beim Rauchen werden Belohnungszentren im Gehirn aktiviert, beim Nichtrauchen fehlt ihm dieser Reiz, was <strong>(33)</strong> zu Schmerzen führen kann.</p><p>Jetzt entdeckten die Hirnforscher: Raucher lassen sich nicht davon <strong>(34)</strong>, was hätte sein können, wenn sie eine andere Entscheidung <strong>(35)</strong> – wenn sie zum Beispiel die letzte Zigarette nicht gebraucht hätten.</p><p>Die Forscher <strong>(36)</strong> Raucher und Nichtraucher an einem Börsenspiel teilnehmen. Die Spieler erhielten jeweils 100 Dollar. Nach jedem Spielzug <strong>(37)</strong> die Spieler, wie sie mehr Geld hätten gewinnen können. Am Ende <strong>(38)</strong> Raucher und Nichtraucher zwar gleich gut ab, doch sie <strong>(39)</strong> unterschiedliche Spielstrategien. Nichtraucher änderten oft ihre Spielweise, sobald sie erfuhren, dass sie in der Vergangenheit mit einer <strong>(40)</strong> Strategie mehr Geld gewonnen hätten. Raucher dagegen <strong>(41)</strong> dem keine Beachtung und spielten weiter. Die Forscher führen dies auf eine Unfähigkeit der Raucher <strong>(42)</strong>, auf alternative Szenarien zu reagieren.</p><p>Um den Unterschied zu erklären, wurde während des Versuchs auch <strong>(43)</strong> die Gehirnaktivität aufgezeichnet. Die Forscher leiteten <strong>(44)</strong> ab, dass Raucher mit denselben Informationen anders umgehen als Nichtraucher: Raucher <strong>(45)</strong> sie einfach. Dies kann auch das Aufhören selbst <strong>(46)</strong>: Für Raucher ist es schwerer, die Vorteile des Nichtrauchens zu erkennen.</p>',
  qs:[
    {n:25,ctx:"warum es Rauchern schwerfällt, von ihrer Sucht ___",
     opts:["a) abzulassen","b) aufzuhören","c) wegzulassen","d) zu beenden"],ans:"a) abzulassen",
     exp:"<strong>a) abzulassen</strong> — <em>von etw. ablassen</em> = отказаться от чего-л. Фиксированная предлог: <em>von</em>. <em>Aufhören</em> требует <em>mit</em>, не <em>von</em>.",
     rule:"<em>von etw. ablassen</em> (von + Dativ) = отказываться от чего-л., бросать (книжн.)"},
    {n:26,ctx:"Resultate einer neuen Studie ___ Hirnforscher",
     opts:["a) drei amerikanischer","b) dreien amerikanischer","c) dreier amerikanischen","d) dreier amerikanischer"],ans:"d) dreier amerikanischer",
     exp:"<strong>d) dreier amerikanischer</strong> — Genitiv Plural после числительного. <em>Drei → dreier</em> (Gen.). Прилагательное без артикля в Gen.Pl.: <em>amerikanischer</em>.",
     rule:"Genitiv Plural без артикля: <em>dreier amerikanischer Hirnforscher</em> = троих американских исследователей мозга"},
    {n:27,ctx:"wurden im Fachmagazin ___ (veröffentlicht)",
     opts:["a) angekündigt","b) geschrieben","c) publiziert","d) weitergegeben"],ans:"c) publiziert",
     exp:"<strong>c) publiziert</strong> = опубликован (в журнале). <em>Veröffentlichen/publizieren</em> = синонимы для научного контекста.",
     rule:"<em>publizieren</em> = публиковать (формально, научный контекст) = <em>veröffentlichen</em>"},
    {n:28,ctx:"Wir wollen hier das Wichtigste ___",
     opts:["a) kurznachfassen","b) kurz zusammenfassen","c) kutz zusammenlegen","d) kurzfassen"],ans:"b) kurz zusammenfassen",
     exp:"<strong>b) kurz zusammenfassen</strong> = кратко резюмировать. <em>Kurzfassen</em> не существует как Kompositum.",
     rule:"<em>kurz zusammenfassen</em> = кратко резюмировать (два слова, не сложное!)"},
    {n:29,ctx:"das ist ___ nur eine subjektive Behauptung, sondern auch wissenschaftlich belegt",
     opts:["a) in keinen Fällen","b) keinfalls","c) keineswegs","d) ohnegleichen"],ans:"c) keineswegs",
     exp:"<strong>c) keineswegs</strong> = ни в коем случае, отнюдь не. Сочетание с <em>nicht nur … sondern auch</em>.",
     rule:"<em>keineswegs</em> = ни в коем случае, отнюдь не (C1, книжн.) = auf keinen Fall"},
    {n:30,ctx:"beeinflusst die Sucht das Verhalten der Betroffenen ___ vielfältige Weise",
     opts:["a) an","b) auf","c) in","d) über"],ans:"b) auf",
     exp:"<strong>b) auf</strong> — <em>auf vielfältige Weise</em> = самыми разными способами. Фиксированная конструкция.",
     rule:"Фиксация: <em>auf + Adjektiv + Weise</em> = каким-л. образом"},
    {n:31,ctx:"wenn andere längst ___",
     opts:["a) aufhören müssten","b) aufhören sollten","c) aufgehört hätten","d) aufzuhören haben"],ans:"c) aufgehört hätten",
     exp:"<strong>c) aufgehört hätten</strong> — Konjunktiv II Perfekt = уже бы бросили (гипотетическое прошлое).",
     rule:"Konj.II Perfekt: <em>hätten + Partizip II</em> = гипотетическое действие в прошлом"},
    {n:32,ctx:"Ziel der Forscher war es, die Sucht der Raucher ___",
     opts:["a) abzuschaffen","b) abzuwägen","c) einzusehen","d) zu verstehen"],ans:"d) zu verstehen",
     exp:"<strong>d) zu verstehen</strong> = понять (суть никотиновой зависимости). <em>Einsehen</em> = признать, <em>abschaffen</em> = отменить.",
     rule:"<em>etw. verstehen</em> = понимать. Infinitiv mit zu после <em>es war das Ziel</em>"},
    {n:33,ctx:"was ___ zu Schmerzen führen kann",
     opts:["a) daraus","b) darüber","c) durchaus","d) hindurch"],ans:"c) durchaus",
     exp:"<strong>c) durchaus</strong> = вполне, очень даже (усилитель). <em>Was durchaus zu Schmerzen führen kann</em> = что вполне может вызвать боль.",
     rule:"<em>durchaus</em> = вполне, совершенно (усилитель утверждения, C1)"},
    {n:34,ctx:"Raucher lassen sich nicht davon ___, was hätte sein können",
     opts:["a) begleiten","b) folgen","c) leiten","d) zeigen"],ans:"c) leiten",
     exp:"<strong>c) leiten</strong> — <em>sich von etw. leiten lassen</em> = руководствоваться чем-л., поддаваться влиянию.",
     rule:"<em>sich von etw. leiten lassen</em> = руководствоваться, поддаваться влиянию чего-л."},
    {n:35,ctx:"wenn sie eine andere Entscheidung ___ – wenn sie die Zigarette nicht gebraucht hätten",
     opts:["a) getroffen hätten","b) trafen","c) treffen werden","d) treffen würden"],ans:"a) getroffen hätten",
     exp:"<strong>a) getroffen hätten</strong> — Konjunktiv II Perfekt для гипотетической ситуации в прошлом. <em>Eine Entscheidung treffen</em> = принять решение.",
     rule:"<em>eine Entscheidung treffen</em> = принять решение · Konj.II Perf.: <em>hätten getroffen</em>"},
    {n:36,ctx:"Die Forscher ___ Raucher und Nichtraucher an einem Börsenspiel teilnehmen",
     opts:["a) brauchten","b) hatten","c) ließen","d) veranlassten"],ans:"c) ließen",
     exp:"<strong>c) ließen</strong> — Kausativkonstruktion: <em>jmdn. etw. tun lassen</em> = заставить/позволить участвовать. Без zu!",
     rule:"Kausativ: <em>jmdn. etw. tun lassen</em> = заставить/позволить сделать (без zu у Infinitiv!)"},
    {n:37,ctx:"Nach jedem Spielzug ___ die Spieler, wie sie mehr Geld hätten gewinnen können",
     opts:["a) erfuhren","b) einheiten","c) realisierten","d) träumten"],ans:"a) erfuhren",
     exp:"<strong>a) erfuhren</strong> = узнали (Präteritum von erfahren). <em>Erfuhren, wie…</em> = узнали о том, как.",
     rule:"<em>erfahren</em> = узнавать (новую информацию) · Prät.: <em>erfuhren</em>"},
    {n:38,ctx:"Am Ende ___ Raucher und Nichtraucher zwar gleich gut ab",
     opts:["a) liefen","b) trennten","c) schnitten","d) machten"],ans:"c) schnitten",
     exp:"<strong>c) schnitten ab</strong> — Prät. von <em>abschneiden</em>: gut/schlecht abschneiden = показать хорошие/плохие результаты.",
     rule:"<em>gut/schlecht abschneiden</em> = показать хорошие/плохие результаты (тест, экзамен и т.д.)"},
    {n:39,ctx:"doch sie ___ unterschiedliche Spielstrategien",
     opts:["a) nahmen","b) unternahmen","c) verbrauchten","d) verfolgten"],ans:"d) verfolgten",
     exp:"<strong>d) verfolgten</strong> — <em>eine Strategie verfolgen</em> = придерживаться стратегии.",
     rule:"<em>eine Strategie / ein Ziel verfolgen</em> = придерживаться стратегии / следовать цели"},
    {n:40,ctx:"mit einer ___ Strategie mehr Geld gewonnen hätten",
     opts:["a) anderen als die gewählte","b) anderen als der gewählten","c) gewählten als der anderen","d) gewählten anderen"],ans:"b) anderen als der gewählten",
     exp:"<strong>b) anderen als der gewählten</strong> = с другой стратегией, чем выбранная. <em>Als</em> при компаративе + Dativ.",
     rule:"Сравнение с атрибутом: <em>einer anderen als der gewählten</em> = другой, чем выбранная (Dat. после als)"},
    {n:41,ctx:"Raucher dagegen ___ dem keine Beachtung und spielten weiter",
     opts:["a) entrichteten","b) gaben","c) schenkten","d) zählten"],ans:"c) schenkten",
     exp:"<strong>c) schenkten</strong> — <em>keine Beachtung schenken</em> = не обращать внимания. Фиксированная конструкция.",
     rule:"Фиксация: <em>jmdm. Beachtung schenken / keine Beachtung schenken</em> = уделять/не уделять внимание"},
    {n:42,ctx:"Unfähigkeit der Raucher ___, auf alternative Szenarien zu reagieren",
     opts:["a) heraus","b) hinzu","c) nach","d) zurück"],ans:"d) zurück",
     exp:"<strong>d) zurück</strong> — <em>etw. auf etw. zurückführen</em> = объяснять чем-л. Здесь: <em>auf eine Unfähigkeit zurückführen</em>.",
     rule:"<em>etw. auf etw. zurückführen</em> = объяснять что-л. чем-л., относить к причине"},
    {n:43,ctx:"wurde während des Versuchs auch ___ die Gehirnaktivität aufgezeichnet",
     opts:["a) fortgegangen","b) fortgehen","c) fortgelaufen","d) fortlaufend"],ans:"d) fortlaufend",
     exp:"<strong>d) fortlaufend</strong> = непрерывно, постоянно (как наречие). <em>Fortlaufend aufgezeichnet</em> = непрерывно записывалась.",
     rule:"<em>fortlaufend</em> = непрерывно, постоянно (наречие, C1)"},
    {n:44,ctx:"Die Forscher leiteten ___ ab, dass Raucher anders umgehen",
     opts:["a) dadurch","b) danach","c) daraus","d) dazu"],ans:"c) daraus",
     exp:"<strong>c) daraus</strong> — <em>daraus ableiten</em> = сделать вывод из этого. <em>da + aus</em> = из этого.",
     rule:"<em>daraus ableiten</em> = делать вывод из этого (da + aus = из этого)"},
    {n:45,ctx:"Raucher ___ sie einfach",
     opts:["a) berücksichtigen","b) beziehen","c) ignorieren","d) vermeiden"],ans:"c) ignorieren",
     exp:"<strong>c) ignorieren</strong> = игнорировать. Рауклеры просто игнорируют информацию.",
     rule:"<em>ignorieren</em> = игнорировать · <em>nicht beachten</em> = не обращать внимания (синоним)"},
    {n:46,ctx:"Dies kann auch das Aufhören selbst ___",
     opts:["a) bekämpfen","b) beschweren","c) erschweren","d) vermeiden"],ans:"c) erschweren",
     exp:"<strong>c) erschweren</strong> = затруднять. <em>Das Aufhören erschweren</em> = затруднять отказ от курения.",
     rule:"<em>erschweren</em> = затруднять · <em>erleichtern</em> = облегчать (антоним)"}
  ],
  vocab:["von etw. ablassen — отказаться от чего-л.","keineswegs — ни в коем случае","auf … Weise — каким-л. образом","sich von etw. leiten lassen — руководствоваться чем-л.","gut abschneiden — показать хорошие результаты","eine Strategie verfolgen — придерживаться стратегии","Beachtung schenken — уделять внимание","daraus ableiten — делать вывод из этого","erschweren — затруднять"]
};
