// test-lv3k.js — Leseverstehen Teil 3
window.TELC_TEST = {
  id:"lv3k", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Geisteswissenschaften — ein Studium ohne Zukunft?",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> «Was willst du denn damit werden?» — Diese Frage kennt wohl jeder, der sich für Germanistik, Geschichte oder Philosophie eingeschrieben hat. Das schlechte Image der Geisteswissenschaften auf dem Arbeitsmarkt hält sich hartnäckig. Dabei zeigt ein genauerer Blick auf die Statistiken ein differenzierteres Bild, als die gängigen Vorurteile vermuten lassen.",
    "<strong>Abs.2:</strong> Die Arbeitslosenquote unter Geisteswissenschaftlern liegt tatsächlich etwas höher als bei Ingenieuren oder Informatikern. Allerdings ist der Unterschied geringer als oft angenommen: Laut Bundesagentur für Arbeit sind etwa 4,5 Prozent der Geisteswissenschaftler arbeitslos — im Vergleich zu 2,8 Prozent bei MINT-Absolventen. Beide Werte liegen deutlich unter dem nationalen Durchschnitt von rund 5,5 Prozent.",
    "<strong>Abs.3:</strong> Der Einstieg in den Beruf dauert für Geisteswissenschaftler oft länger, und das erste Gehalt ist im Schnitt niedriger. Jedoch gleichen sich die Einkommensverhältnisse im Laufe der Karriere zunehmend an. Eine Studie des Instituts der deutschen Wirtschaft zeigt: Geisteswissenschaftler, die zehn oder mehr Jahre im Beruf sind, verdienen im Median nur geringfügig weniger als vergleichbare MINT-Absolventen.",
    "<strong>Abs.4:</strong> Was Geisteswissenschaftler auszeichnet, sind sogenannte Soft Skills: kritisches Denken, Kommunikationsfähigkeit, kulturelles Verständnis und die Fähigkeit, komplexe Texte zu analysieren und verständlich aufzubereiten. In einer zunehmend digitalisierten Arbeitswelt, in der Algorithmen Routineaufgaben übernehmen, gewinnen genau diese Fähigkeiten an Bedeutung. Viele Unternehmen suchen gezielt nach Absolventen, die vernetzt denken und kommunizieren können.",
    "<strong>Abs.5:</strong> Die häufigste Kritik lautet: Geisteswissenschaften bereiten nicht auf konkrete Berufe vor. Das stimmt — aber nur bedingt. Wer Medien, Verlagswesen, Kulturmanagement, Bildung oder den öffentlichen Dienst anstrebt, ist mit einem geisteswissenschaftlichen Abschluss gut aufgestellt. Problematisch wird es, wenn Studierende ohne Berufsvorstellung ins Studium starten und keine Praktika oder Zusatzqualifikationen erwerben.",
    "<strong>Abs.6:</strong> Entscheidend für den Berufserfolg ist letztendlich weniger das Fach als die Eigeninitiative. Wer während des Studiums Netzwerke aufbaut, Auslandserfahrungen sammelt und gezielt Praktika absolviert, hat auch als Geisteswissenschaftler sehr gute Chancen. Das bestätigt eine Umfrage unter Personalverantwortlichen: 78 Prozent gaben an, Bewerber primär nach Persönlichkeit und Zusatzerfahrungen zu beurteilen — nicht nach dem Studienabschluss."
  ],
  qs:[
    {n:13, t:"Die Arbeitslosenquote von Geisteswissenschaftlern liegt über dem nationalen Durchschnitt.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.2: «Beide Werte liegen deutlich unter dem nationalen Durchschnitt von rund 5,5 Prozent.» — 4,5% < 5,5%.",
     textref:"«Beide Werte liegen deutlich unter dem nationalen Durchschnitt von rund 5,5 Prozent.»",
     rule:"4,5% Geisteswiss. < 5,5% national. <em>unter</em> ≠ über. Direkter Widerspruch."},
    {n:14, t:"Der Gehaltsunterschied zwischen Geisteswissenschaftlern und MINT-Absolventen verschwindet mit der Zeit.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.3: «gleichen sich die Einkommensverhältnisse im Laufe der Karriere zunehmend an.»",
     textref:"«gleichen sich die Einkommensverhältnisse im Laufe der Karriere zunehmend an.»",
     rule:"<em>sich angleichen</em> = сближаться, выравниваться = verschwindet mit der Zeit."},
    {n:15, t:"Geisteswissenschaftliche Abschlüsse werden von Personalverantwortlichen grundsätzlich abgelehnt.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.6: «78 Prozent beurteilen Bewerber primär nach Persönlichkeit und Zusatzerfahrungen» — kein Hinweis auf Ablehnung.",
     textref:"«78 Prozent gaben an, Bewerber primär nach Persönlichkeit … zu beurteilen — nicht nach dem Studienabschluss.»",
     rule:"Grundsätzliche Ablehnung = im Text nicht belegt. x wäre auch möglich, aber Text widerspricht aktiv."},
    {n:16, t:"Kommunikationsfähigkeit und kritisches Denken werden in der digitalen Arbeitswelt wichtiger.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «In einer … digitalisierten Arbeitswelt … gewinnen genau diese Fähigkeiten an Bedeutung.»",
     textref:"«In einer zunehmend digitalisierten Arbeitswelt … gewinnen genau diese Fähigkeiten an Bedeutung.»",
     rule:"<em>an Bedeutung gewinnen</em> = становиться важнее. Direkte Aussage."},
    {n:17, t:"Geisteswissenschaften bereiten auf keinerlei konkrete Berufe vor.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.5: «Wer Medien, Verlagswesen, Kulturmanagement … anstrebt, ist mit einem geisteswissenschaftlichen Abschluss gut aufgestellt.»",
     textref:"«Wer Medien, Verlagswesen … anstrebt, ist … gut aufgestellt.»",
     rule:"<em>keinerlei</em> = абсолютно никаких. Text nennt konkrete Berufsfelder — Widerspruch."},
    {n:18, t:"Praktika und Auslandserfahrungen erhöhen die Berufschancen von Geisteswissenschaftlern.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.6: «Wer … Praktika absolviert, hat auch als Geisteswissenschaftler sehr gute Chancen.»",
     textref:"«Wer … Auslandserfahrungen sammelt und gezielt Praktika absolviert, hat auch als Geisteswissenschaftler sehr gute Chancen.»",
     rule:"Direkte Aussage im Text."},
    {n:19, t:"Geisteswissenschaftler finden sofort nach dem Studium genauso schnell Arbeit wie Ingenieure.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.3: «Der Einstieg in den Beruf dauert für Geisteswissenschaftler oft länger.»",
     textref:"«Der Einstieg in den Beruf dauert für Geisteswissenschaftler oft länger.»",
     rule:"<em>dauert länger</em> ≠ genauso schnell. Direkter Widerspruch."},
    {n:20, t:"Algorithmen übernehmen zunehmend Routineaufgaben in der Arbeitswelt.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.4: «in der … Algorithmen Routineaufgaben übernehmen.»",
     textref:"«in einer zunehmend digitalisierten Arbeitswelt, in der Algorithmen Routineaufgaben übernehmen.»",
     rule:"Direkte Aussage im Text."},
    {n:21, t:"Das Studium der Philosophie ist in Deutschland verboten.", opts:["+","-","x"], ans:"-",
     exp:"Falsch (-). Abs.1: Philosophie wird als mögliches Studienfach erwähnt — kein Hinweis auf Verbot.",
     textref:"«Germanistik, Geschichte oder Philosophie» — als normale Studienfächer genannt.",
     rule:"Verbot = im Text nicht erwähnt. Philosophie wird als normales Fach behandelt."},
    {n:22, t:"Das Ansehen von Geisteswissenschaften auf dem Arbeitsmarkt ist pauschal negativ, obwohl die Statistiken ein anderes Bild zeigen.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.1: «Das schlechte Image … hält sich hartnäckig. Dabei zeigt ein genauerer Blick … ein differenzierteres Bild.»",
     textref:"«Das schlechte Image … hält sich hartnäckig. Dabei zeigt ein genauerer Blick … ein differenzierteres Bild.»",
     rule:"Kontrast: negatives Image vs. bessere Realität. Beide Aspekte direkt im Text."},
    {n:23, t:"Personalverantwortliche legen mehr Wert auf Persönlichkeit als auf den Studienabschluss.", opts:["+","-","x"], ans:"+",
     exp:"Richtig (+). Abs.6: «78 Prozent … Bewerber primär nach Persönlichkeit … beurteilen — nicht nach dem Studienabschluss.»",
     textref:"«78 Prozent gaben an, Bewerber primär nach Persönlichkeit und Zusatzerfahrungen zu beurteilen — nicht nach dem Studienabschluss.»",
     rule:"<em>primär nach Persönlichkeit … nicht nach Abschluss</em> = Persönlichkeit > Abschluss."},
    {n:24, t:"Welche Überschrift passt am besten?",
     opts:["a) Geisteswissenschaften sind nutzlos — Statistiken beweisen es","b) Zwischen Vorurteil und Realität: Geisteswissenschaftler auf dem Arbeitsmarkt","c) Warum Soft Skills wichtiger sind als technisches Wissen"],
     ans:"b) Zwischen Vorurteil und Realität: Geisteswissenschaftler auf dem Arbeitsmarkt",
     exp:"b) deckt alle Abschnitte ab: Image (Abs.1), Statistiken (Abs.2,3), Fähigkeiten (Abs.4), Berufsfelder (Abs.5), Eigeninitiative (Abs.6). a) ist falsch, c) ist zu eng.",
     textref:"Gesamter Text: negatives Image vs. differenzierte Realität = Kernthema.",
     rule:"Makroaufgabe: Überschrift mit Kontrast (<em>zwischen … und</em>) passt zum Gesamtthema."}
  ],
  vocab:["hartnäckig — упорно, настойчиво","gängig — распространённый","die Arbeitslosenquote — уровень безработицы","sich angleichen — сближаться, выравниваться","geringfügig — незначительно","die Eigeninitiative — собственная инициатива","der Personalverantwortliche — сотрудник по персоналу"]
};
