// test-lv3e.js — TELC C1
window.TELC_TEST = {
  id:"lv3_5", type:"Leseverstehen Teil 3", kind:"lv3",
  title:"Alter ist nicht gleich Alter",
  desc:"11 Aussagen + Makroaufgabe · C1",
  textps:[
    "<strong>Abs.1:</strong> Was bedeutet es, alt zu sein? In unserer Gesellschaft gilt, wer das Rentenalter erreicht hat, als alt. Doch Gerontologen — Wissenschaftler, die das Altern erforschen — widersprechen dieser vereinfachenden Sichtweise. Das kalendarische Alter, also die Anzahl der gelebten Jahre, sagt wenig über den tatsächlichen Gesundheitszustand oder die Leistungsfähigkeit eines Menschen aus.",
    "<strong>Abs.2:</strong> Forscher unterscheiden heute zwischen verschiedenen Dimensionen des Alters: dem biologischen, dem psychologischen und dem sozialen Alter. Das biologische Alter beschreibt den Zustand von Organen und Zellen. Das psychologische Alter bezieht sich auf geistige Leistungsfähigkeit und emotionale Reife. Das soziale Alter schließlich definiert sich über gesellschaftliche Rollen und Erwartungen.",
    "<strong>Abs.3:</strong> Besonders das biologische Alter kann erheblich vom kalendarischen abweichen. Studien zeigen, dass regelmäßige körperliche Aktivität das biologische Alter um bis zu zehn Jahre senken kann. Wer also mit 60 Jahren dreimal pro Woche Sport treibt, hat möglicherweise das biologische Alter eines 50-Jährigen. Ernährung, Schlaf und soziale Kontakte spielen ebenfalls eine entscheidende Rolle.",
    "<strong>Abs.4:</strong> Auch das Gehirn altert nicht so unausweichlich, wie lange angenommen. Neue Erkenntnisse der Neurowissenschaft zeigen: Das Gehirn ist lebenslang formbar — ein Phänomen, das als Neuroplastizität bezeichnet wird. Wer geistig aktiv bleibt, neue Sprachen lernt oder Musikinstrumente spielt, kann den kognitiven Abbau deutlich verlangsamen.",
    "<strong>Abs.5:</strong> Das soziale Alter hingegen ist stark kulturell geprägt. In manchen Gesellschaften gelten ältere Menschen als Autoritäten und Weisheitsträger, während sie in anderen eher an den Rand gedrängt werden. In Deutschland hat sich das Bild des Alters in den letzten Jahrzehnten gewandelt: Die sogenannten «aktiven Senioren» widerlegen das Klischee vom gebrechlichen alten Menschen.",
    "<strong>Abs.6:</strong> Wissenschaftler fordern deshalb, das Rentenalter nicht mehr als starren Grenzwert zu betrachten. Stattdessen plädieren sie für flexible Modelle, die individuelle Leistungsfähigkeit berücksichtigen. Das würde nicht nur den Betroffenen zugutekommen, sondern auch dem Arbeitsmarkt, der angesichts des demografischen Wandels dringend auf erfahrene Kräfte angewiesen ist."
  ],
  qs:[
    {n:13,t:"Das kalendarische Alter bestimmt zuverlässig den Gesundheitszustand eines Menschen.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.1: «sagt wenig über den tatsächlichen Gesundheitszustand … aus» = Gegenteil.",
     textref:"«Das kalendarische Alter … sagt wenig über den tatsächlichen Gesundheitszustand oder die Leistungsfähigkeit … aus.»",
     rule:"<em>wenig aussagen über</em> = мало говорить о чём-л. ≠ zuverlässig bestimmen."},
    {n:14,t:"Gerontologen unterscheiden mindestens drei Arten von Alter.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.2: biologisches + psychologisches + soziales Alter = mindestens drei Dimensionen.",
     textref:"«das biologische, dem psychologischen und dem sozialen Alter.»",
     rule:"Drei namentlich genannte Dimensionen = mindestens drei Arten."},
    {n:15,t:"Das psychologische Alter lässt sich ausschließlich durch Intelligenztests messen.",opts:["+","-","x"],ans:"x",
     exp:"Nicht im Text (x). Abs.2 beschreibt psychologisches Alter, aber Intelligenztests werden nicht erwähnt.",
     textref:"«Das psychologische Alter bezieht sich auf geistige Leistungsfähigkeit und emotionale Reife.»",
     rule:"x = Intelligenztests kommen im Text nicht vor."},
    {n:16,t:"Regelmäßiger Sport kann das biologische Alter positiv beeinflussen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.3: «regelmäßige körperliche Aktivität das biologische Alter um bis zu zehn Jahre senken kann.»",
     textref:"«regelmäßige körperliche Aktivität das biologische Alter um bis zu zehn Jahre senken kann.»",
     rule:"Direkte Aussage. Paraphrase: senken = positiv beeinflussen."},
    {n:17,t:"Das Gehirn kann sich auch im Alter noch verändern und anpassen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «Das Gehirn ist lebenslang formbar» — Neuroplastizität.",
     textref:"«Das Gehirn ist lebenslang formbar — ein Phänomen, das als Neuroplastizität bezeichnet wird.»",
     rule:"<em>lebenslang formbar</em> = kann sich auch im Alter noch verändern = Neuroplastizität."},
    {n:18,t:"In allen Kulturen weltweit werden ältere Menschen gleichermaßen respektiert.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «In manchen Gesellschaften gelten ältere Menschen als Autoritäten … während sie in anderen eher an den Rand gedrängt werden.» = unterschiedlich!",
     textref:"«In manchen Gesellschaften gelten … als Autoritäten … während sie in anderen eher an den Rand gedrängt werden.»",
     rule:"<em>in manchen … während in anderen</em> = Kontrast zwischen Kulturen. Nicht überall gleich."},
    {n:19,t:"Das Bild älterer Menschen in Deutschland hat sich in den letzten Jahrzehnten kaum verändert.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.5: «hat sich das Bild des Alters in den letzten Jahrzehnten gewandelt» = Gegenteil!",
     textref:"«In Deutschland hat sich das Bild des Alters in den letzten Jahrzehnten gewandelt.»",
     rule:"<em>gewandelt</em> = verändert ≠ kaum verändert. Direkter Widerspruch."},
    {n:20,t:"Wissenschaftler befürworten flexiblere Regelungen beim Renteneintrittsalter.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.6: «plädieren sie für flexible Modelle» beim Rentenalter.",
     textref:"«plädieren sie für flexible Modelle, die individuelle Leistungsfähigkeit berücksichtigen.»",
     rule:"<em>plädieren für</em> = выступать за = befürworten. Direkte Paraphrase."},
    {n:21,t:"Flexible Rentenmodelle würden dem Arbeitsmarkt schaden.",opts:["+","-","x"],ans:"-",
     exp:"Falsch (-). Abs.6: «Das würde nicht nur den Betroffenen zugutekommen, sondern auch dem Arbeitsmarkt.» = Gegenteil!",
     textref:"«das würde nicht nur den Betroffenen zugutekommen, sondern auch dem Arbeitsmarkt.»",
     rule:"<em>zugutekommen</em> = идти на пользу ≠ schaden. Direkter Widerspruch."},
    {n:22,t:"Musikinstrumente spielen kann den geistigen Abbau verlangsamen.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.4: «neue Sprachen lernt oder Musikinstrumente spielt, kann den kognitiven Abbau deutlich verlangsamen.»",
     textref:"«Wer geistig aktiv bleibt, neue Sprachen lernt oder Musikinstrumente spielt, kann den kognitiven Abbau deutlich verlangsamen.»",
     rule:"Direkte Aussage im Text."},
    {n:23,t:"Der demografische Wandel macht erfahrene ältere Arbeitnehmer besonders wertvoll.",opts:["+","-","x"],ans:"+",
     exp:"Richtig (+). Abs.6: «angesichts des demografischen Wandels dringend auf erfahrene Kräfte angewiesen ist.»",
     textref:"«dem Arbeitsmarkt, der angesichts des demografischen Wandels dringend auf erfahrene Kräfte angewiesen ist.»",
     rule:"<em>angewiesen sein auf</em> = зависеть от, нуждаться в = besonders wertvoll."},
    {n:24,t:"Welche Überschrift passt am besten?",
     opts:["a) Rente mit 67: Wissenschaftler fordern Abschaffung","b) Verschiedene Dimensionen des Alters und ihre Bedeutung für die Gesellschaft","c) Neuroplastizität: Das Gehirn bleibt ewig jung"],
     ans:"b) Verschiedene Dimensionen des Alters und ihre Bedeutung für die Gesellschaft",
     exp:"b) deckt alle Themen ab: drei Alterdimensionen (bio/psych/sozial) + Gesellschaft (Rente, Arbeitsmarkt, Kulturvergleich). a) zu eng, c) nur Abs.4.",
     textref:"Gesamter Text: verschiedene Altersdimensionen + gesellschaftliche Konsequenzen.",
     rule:"Makroaufgabe: Überschrift muss ALLE Abschnitte abdecken. Кратко и точно."}
  ],
  vocab:["der Gerontologe — геронтолог","kalendarisch — календарный","die Neuroplastizität — нейропластичность","formbar — пластичный, поддающийся изменению","plädieren für — выступать за, ратовать за","zugutekommen — идти на пользу","angewiesen sein auf — зависеть от, нуждаться в"]
};
