// test-sb1.js — TELC C1
window.TELC_TEST = {
  id:"sb1", type:"Sprachbausteine", kind:"sb",
  title:'Wer hat das "Handy" erfunden?',
  desc:"22 Lücken · Grammatik & Lexik · C1",
  text:'<p>Jeder kennt es, fast jeder Deutsche hat auch <strong>(25)</strong>: das Mobiltelefon oder eben &bdquo;Handy&rdquo;. Ob auf der Straße, in Bus oder Bahn hört man überall Sätze wie &bdquo;Gib mir mal das Handy!" – &bdquo;Handy&rdquo; gehört inzwischen zur deutschen Sprache. Oder?</p><p>Eine Umfrage hat gezeigt: Die meisten Deutschen (76 %) sind der <strong>(26)</strong>, dass der Begriff &bdquo;Handy&rdquo; aus dem Englischen <strong>(27)</strong>. Das ist jedoch falsch. Tatsächlich sind die <strong>(28)</strong> Sprechenden die einzigen, die ihr Mobiltelefon als Handy bezeichnen. Und das Wort <strong>(29)</strong> keineswegs aus dem Englischen – dort <strong>(30)</strong> man das kleine Telefon meist als &bdquo;mobile phone". Dass die Deutschen sich eines englisch klingenden Phantasiewortes <strong>(31)</strong>, wird von Kulturpessimisten gern als &bdquo;ins Absurde <strong>(32)</strong> Anglomanie" bezeichnet. Der Begriff &bdquo;Handy&rdquo; verdanke sich in Wirklichkeit allein der <strong>(33)</strong>, der Sprache Luthers und Goethes fehlten im Zeitalter der globalen Kommunikation die Worte. Nun kann man darüber <strong>(34)</strong>, wie Luther sein Mobiltelefon genannt hätte – vermutlich <strong>(35)</strong> zu keinem vernünftigen Ergebnis in diesem Punkt gelangen.</p><p>Sicher ist jedoch, dass der Begriff &bdquo;Handy&rdquo; keine <strong>(36)</strong> Schöpfung ist. Um dem Ursprung dieses Begriffs etwas <strong>(37)</strong>, muss man sich ein wenig mit der Sprachgeschichte befassen und zurückschauen in die 1930er Jahre. Zu jener Zeit wurden – zunächst <strong>(38)</strong> für den militärischen Einsatz – kleine tragbare Funkgeräte entwickelt. Es <strong>(39)</strong> sich bei diesen Geräten um eine Weiterentwicklung der sogenannten &bdquo;Walkie Talkies". Während <strong>(40)</strong> meist rucksackgroße Geräte waren, konnte man die neuen Funkgeräte ganz einfach in eine Tasche stecken oder <strong>(41)</strong> in der Hand tragen. Diese Geräte wurden von Soldaten als &bdquo;Handie Talkies" bezeichnet, und einige amerikanische Soldaten sollen diesen Ausdruck <strong>(42)</strong> sogar zu &bdquo;Handy&rdquo; <strong>(43)</strong>.</p><p>Im deutschen Sprachraum tauchte das Handy dann erstmals in einer Anzeige von 1986 auf und <strong>(44)</strong> damals noch ein kleines Amateurfunkgerät, bevor sich die <strong>(45)</strong> dann ab 1990 für Mobiltelefone durchsetzte. Der <strong>(46)</strong> des Handys konnte nicht mehr aufgehalten werden.</p>',
  qs:[
    {n:25,ctx:"fast jeder Deutsche hat auch ___: das Mobiltelefon",
     opts:["a) das","b) ein","c) eines","d) es"],ans:"c) eines",
     exp:"<strong>c) eines</strong> — unbestimmtes Pronomen Neutr. (= один такой предмет). <em>Ein</em> — Artikel vor Nomen, nicht Pronomen. <em>es</em> — Personalpronomen.",
     rule:"<em>eines</em> = неопределённое местоимение ср.р.: «hat auch <strong>eines</strong>» = имеет (один такой предмет). Стоит без существительного."},
    {n:26,ctx:"sind der ___, dass der Begriff aus dem Englischen kommt",
     opts:["a) Auffassung","b) Aufnahme","c) Auslegung","d) Behauptung"],ans:"a) Auffassung",
     exp:"<strong>a) Auffassung</strong> — фиксированная конструкция: <em>der Auffassung sein, dass…</em> = быть того мнения, что. Требует Genitiv.",
     rule:"Фиксация: <em>der Auffassung / Meinung / Ansicht sein</em> = придерживаться мнения (C1). Всегда с Genitiv!"},
    {n:27,ctx:"dass der Begriff aus dem Englischen ___",
     opts:["a) ableitet","b) entlehnt","c) herleitet","d) stammt"],ans:"d) stammt",
     exp:"<strong>d) stammt</strong> — <em>aus etw. stammen</em> = происходить из. <em>Ableiten / herleiten</em> требуют <em>sich</em> (reflexiv).",
     rule:"<em>stammen aus + Dativ</em> = происходить из чего-л. Без Reflexivpronomen!"},
    {n:28,ctx:"sind die ___ Sprechenden die einzigen",
     opts:["a) Deutsch","b) Deutsche","c) Deutschen","d) Deutsches"],ans:"a) Deutsch",
     exp:"<strong>a) Deutsch</strong> — здесь название языка как атрибут к Partizip I: <em>die Deutsch Sprechenden</em> = говорящие по-немецки. Нет артикля → нет окончания.",
     rule:"<em>die Deutsch Sprechenden</em> = субстантивированное Partizip I. Ср.: <em>die Deutschen</em> = немцы (национальность) — другое значение!"},
    {n:29,ctx:"das Wort ___ keineswegs aus dem Englischen",
     opts:["a) entreißt","b) entsteht","c) folgt","d) stammt"],ans:"d) stammt",
     exp:"<strong>d) stammt</strong> — <em>aus etw. stammen</em> = происходить из. Фиксированная предлог: <em>aus</em>.",
     rule:"<em>stammen aus</em> = происходить из · <em>kommen aus</em> = аналогично, но разговорнее"},
    {n:30,ctx:"dort ___ man das kleine Telefon meist als &bdquo;mobile phone&rdquo;",
     opts:["a) bedrückt","b) bezeichnet","c) definiert","d) deutet"],ans:"b) bezeichnet",
     exp:"<strong>b) bezeichnet</strong> — <em>etw. als etw. bezeichnen</em> = называть что-л. чем-л. Фиксированная структура с <em>als</em>.",
     rule:"<em>als etw. bezeichnen / nennen / betrachten</em> — всегда с <em>als</em> + Nominativ"},
    {n:31,ctx:"Dass die Deutschen sich eines Phantasiewortes ___",
     opts:["a) bedienen","b) benutzen","c) gebrauchen","d) verdienen"],ans:"a) bedienen",
     exp:"<strong>a) bedienen</strong> — <em>sich einer Sache bedienen</em> (Genitiv!) = пользоваться чем-л. (книжн.). <em>Benutzen/gebrauchen</em> → Akkusativ.",
     rule:"<em>sich einer Sache bedienen</em> (Gen.) = пользоваться чем-л. — ВАЖНО: требует Genitiv, не Akkusativ!"},
    {n:32,ctx:"gern als &bdquo;ins Absurde ___ Anglomanie&rdquo; bezeichnet",
     opts:["a) gerächte","b) geführte","c) getriebene","d) geworfene"],ans:"b) geführte",
     exp:"<strong>b) geführte</strong> — <em>ins Absurde führen</em> = доводить до абсурда → Partizip II как атрибут: <em>die ins Absurde geführte Anglomanie</em>.",
     rule:"Partizip II как атрибут перед существительным. Слабое склонение после определённого артикля (Akk. fem. → -e)."},
    {n:33,ctx:"verdanke sich allein der ___, der Sprache fehlten die Worte",
     opts:["a) Annahme","b) Einstellung","c) Stellungnahme","d) Verstellung"],ans:"a) Annahme",
     exp:"<strong>a) Annahme</strong> = предположение. <em>Einstellung</em> = отношение/установка. <em>Stellungnahme</em> = позиция/заявление.",
     rule:"<em>die Annahme</em> = предположение / <em>die Einstellung</em> = отношение / <em>die Stellungnahme</em> = официальное заявление"},
    {n:34,ctx:"Nun kann man darüber ___, wie Luther sein Mobiltelefon genannt hätte",
     opts:["a) ausbrüten","b) denken","c) grübeln","d) lifteln"],ans:"c) grübeln",
     exp:"<strong>c) grübeln</strong> = ломать голову над чем-л. <em>Über etw. grübeln, wie…</em> — идеально подходит.",
     rule:"<em>über etw. grübeln</em> = раздумывать, ломать голову (книжн.)"},
    {n:35,ctx:"vermutlich ___ zu keinem vernünftigen Ergebnis gelangen",
     opts:["a) aber man wird","b) man aber wird","c) wird man aber","d) wird aber man"],ans:"c) wird man aber",
     exp:"<strong>c) wird man aber</strong> — наречие <em>vermutlich</em> на Pos.1 → глагол на Pos.2 → подлежащее → частица. Порядок: vermutlich | wird | man | aber.",
     rule:"Порядок слов: Наречие (Pos.1) + Глагол (Pos.2) + Подлежащее + Частица"},
    {n:36,ctx:"der Begriff &bdquo;Handy&rdquo; keine ___ Schöpfung ist",
     opts:["a) rein deutsche","b) reindeutsche","c) reine deutsche","d) reine Deutsche"],ans:"a) rein deutsche",
     exp:"<strong>a) rein deutsche</strong> — <em>rein</em> как наречие (= purely/чисто) перед прилагательным. Оба слова строчные. <em>reine Deutsche</em> = чистокровная немка (существительное).",
     rule:"<em>rein</em> как наречие + прилагательное: <em>rein deutsch</em> = чисто немецкий. Склоняется только последнее прилагательное."},
    {n:37,ctx:"Um dem Ursprung dieses Begriffs etwas ___",
     opts:["a) klarzukommen","b) näherzukommen","c) zu klären","d) zu nähern"],ans:"b) näherzukommen",
     exp:"<strong>b) näherzukommen</strong> — <em>einer Sache näherkommen</em> = приближаться к пониманию чего-л. Отделяемый глагол: <em>zu</em> стоит МЕЖДУ приставкой и глаголом.",
     rule:"Отделяемые глаголы + zu: <em>näher|kommen → näher<strong>zu</strong>kommen</em>. zu всегда между приставкой и глаголом!"},
    {n:38,ctx:"zunächst ___ für den militärischen Einsatz",
     opts:["a) vorbildlich","b) vorgezogen","c) vornehmlich","d) vortrefflich"],ans:"c) vornehmlich",
     exp:"<strong>c) vornehmlich</strong> = hauptsächlich = главным образом, прежде всего. <em>Vorbildlich</em> = образцово, <em>vortrefflich</em> = превосходно.",
     rule:"<em>vornehmlich</em> = hauptsächlich = прежде всего, главным образом (типично для C1)"},
    {n:39,ctx:"Es ___ sich bei diesen Geräten um eine Weiterentwicklung",
     opts:["a) belief","b) ergab","c) ging","d) handelte"],ans:"d) handelte",
     exp:"<strong>d) handelte</strong> — <em>es handelt sich um + Akk.</em> = речь идёт о. Фиксированная безличная конструкция!",
     rule:"ФИКСАЦИЯ: <em>es handelt sich um + Akk.</em> = речь идёт о (ОЧЕНЬ ВАЖНО для C1!)"},
    {n:40,ctx:"Während ___ meist rucksackgroße Geräte waren",
     opts:["a) Letztere","b) letztgesagte","c) letztlich","d) zuletzt"],ans:"a) Letztere",
     exp:"<strong>a) Letztere</strong> (Plural) = последние из упомянутых (Walkie Talkies). Субстантивация, склоняется как прилагательное.",
     rule:"<em>Erstere/Letztere</em> = первые/последние (из упомянутых) — субстантивация"},
    {n:41,ctx:"konnte man in eine Tasche stecken oder ___ in der Hand tragen",
     opts:["a) also","b) eben","c) genau","d) gerade"],ans:"b) eben",
     exp:"<strong>b) eben</strong> = просто так, вот так (модальная частица). <em>Also</em> = итак, <em>gerade</em> = как раз/именно сейчас.",
     rule:"<em>eben</em> как частица = просто, именно так (Modalpartikel C1)"},
    {n:42,ctx:"einige Soldaten sollen diesen Ausdruck ___ sogar zu &bdquo;Handy&rdquo; abgekürzt haben",
     opts:["a) dadurch","b) dagegen","c) daraufhin","d) dennoch"],ans:"c) daraufhin",
     exp:"<strong>c) daraufhin</strong> = вследствие этого, затем. Каузальное наречие, стоит на Pos.1.",
     rule:"<em>daraufhin</em> = вследствие этого, затем → всегда на Pos.1 во втором предложении"},
    {n:43,ctx:"zu &bdquo;Handy\" ___ haben",
     opts:["a) abgekürzt","b) abkürzen","c) gekürzt","d) kürzer gemacht"],ans:"a) abgekürzt",
     exp:"<strong>a) abgekürzt</strong> — Partizip II от <em>abkürzen</em> (отделяемый: ab|kürzen). Инфинитив Перфект с Modalverb: <em>sollen + abgekürzt haben</em>.",
     rule:"Отделяемые глаголы Partizip II: <em>ab|kürzen → abgekürzt</em>. Инфинитив Перфект: <em>abgekürzt haben</em>"},
    {n:44,ctx:"tauchte in einer Anzeige von 1986 auf und ___ damals noch ein Amateurfunkgerät",
     opts:["a) bezeichnete","b) hieß","c) klassifizierte","d) nannte"],ans:"a) bezeichnete",
     exp:"<strong>a) bezeichnete</strong> = обозначало (формально). <em>Hieß</em> тоже возможно, но <em>bezeichnen</em> — формальнее для C1-текстов.",
     rule:"<em>bezeichnen</em> = обозначать (формально) / <em>heißen</em> = называться (разговорнее)"},
    {n:45,ctx:"bevor sich die ___ dann ab 1990 für Mobiltelefone durchsetzte",
     opts:["a) Wörterererschöpfung","b) Worterschopfung","c) Wörterschöpfung","d) Wortschöpfung"],ans:"d) Wortschöpfung",
     exp:"<strong>d) Wortschöpfung</strong> = словотворчество, неологизм. Сложное слово: Wort + Schöpfung. Без умлаута в первой части.",
     rule:"<em>die Wortschöpfung</em> = словотворчество / <em>die Schöpfung</em> = творение, создание"},
    {n:46,ctx:"Der ___ des Handys konnte nicht mehr aufgehalten werden",
     opts:["a) Gewinn","b) Siegeszug","c) Trumpf","d) Vollzug"],ans:"b) Siegeszug",
     exp:"<strong>b) Siegeszug</strong> = триумфальное шествие. <em>Vollzug</em> = исполнение (юрид.).",
     rule:"<em>der Siegeszug</em> = триумфальное шествие / <em>den Siegeszug antreten</em> = начать победное шествие"}
  ],
  vocab:["die Auffassung — мнение, точка зрения","sich einer Sache bedienen (Gen.) — пользоваться чем-л.","es handelt sich um + Akk. — речь идёт о","vornehmlich — главным образом","der Siegeszug — триумфальное шествие","stammen aus — происходить из","daraufhin — вследствие этого"]
};
